/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 06/07/2021
 */

drop table if exists locales;
CREATE TABLE IF NOT EXISTS locales(
  id int(11) NOT NULL AUTO_INCREMENT,
  nombre varchar(255),
  url_logo varchar(255),
  aforo_max int(11),
  aforo_actual int(11) default 0,
  usuario varchar(255),
  passw varchar(255),
  directorio varchar(255),
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
INSERT INTO `locales` VALUES (1,'Oficina','https://ichef.bbci.co.uk/news/976/cpsprodpb/3066/production/_111609321_1-1.jpg',100,0,'ofi','a',NULL,'2021-09-30 14:39:28'),(2,'Luna Azul','https://www.pikpng.com/pngl/m/429-4298683_media-luna-azul-png-imagenes-de-media-luna.png',100,0,'lunaazul','a',NULL,'2021-09-30 14:39:53');

drop table if exists camaras;
CREATE TABLE IF NOT EXISTS camaras(
  id int(11) NOT NULL AUTO_INCREMENT,
  local_id int(11) default 0,
  descripcion varchar(1024),
  directorio varchar(255),
  url_conexion varchar(255),
  sistema int(11) default 0, /*0 son las ip, 1 de grabador*/
  x int(11) default 0,
  y int(11) default 0,
  puerta int(11) default 0,
  salida int(11) default 0,
  encendida int(11) default 0,
  ipcamlive_alias varchar(255),
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);


drop table if exists nodos;
CREATE TABLE IF NOT EXISTS nodos(
  id int(11) NOT NULL AUTO_INCREMENT,
  camara_id1 int(11) default 0,
  camara_id2 int(11) default 0,
  x int(11) default 0,
  y int(11) default 0,
  orden int(11) default 0,
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

drop table if exists lineas;
CREATE TABLE IF NOT EXISTS lineas(
  id int(11) NOT NULL AUTO_INCREMENT,
  camara_id int(11) default 0,
  nombre varchar(255),
  x1 float default 0,
  y1 float default 0,
  x2 float default 0,
  y2 float default 0,
  eliminada int(11) default 0,
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

alter table camaras add url_desdeserver varchar(255);




drop table if exists personas;
CREATE TABLE IF NOT EXISTS personas(
  id int(11) NOT NULL AUTO_INCREMENT,
  local_id varchar(255),
  nombre varchar(1024) default '',
  cod_interno varchar(255),
  trabajador int(11) default 0,
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

drop table if exists estancias;
CREATE TABLE IF NOT EXISTS estancias(
  id int(11) NOT NULL AUTO_INCREMENT,
  persona_id int(11) default 0,
  camara_id int(11) default 0,
  fecha_ini timestamp default CURRENT_TIMESTAMP,
  fecha_fin timestamp default CURRENT_TIMESTAMP,
  notificacion_vista int(11) default 0,
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);


drop table if exists fotos;
CREATE TABLE IF NOT EXISTS fotos(
  id int(11) NOT NULL AUTO_INCREMENT,
  estancia_id int(11) default 0,
  nombre_real_antesconversion varchar(255),
  identificador_unico varchar(255),
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);



drop table if exists cruces_lineas;
CREATE TABLE IF NOT EXISTS cruces_lineas(
  id int(11) NOT NULL AUTO_INCREMENT,
  linea_id int(11) default 0,
  fecha timestamp default CURRENT_TIMESTAMP,
  direccion int(11) default 0, /*1: #de derexa de la panatalla hacia la izquierda;;;;2:#de izquierda de la panatalla hacia la derexa*/
  x_cruce int(11) default 0,
  y_cruce int(11) default 0,
  identificador varchar(255),
  created timestamp DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);



