<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 06/07/2021
 */
//python3.7 motor/guarda_movimientos.py 217.61.112.100 testuser prueba123 'rtsp://admin:bakcAse4@172.16.51.52:554/cam/realmonitor?channel=1&subtype=0' 3 3
//HCVR_ch1_main_20210726000000_20210726015959.dav

$local_id="";
if(isset($argv[1]) and $argv[1]!=""){
    $local_id=$argv[1];    
}

$desde="local";
if(isset($argv[2]) and $argv[2]!=""){
    $desde="server";
}


//define("INTERVAL", 60*10 ); // 5 minutes


require_once("config/rutas.php");
require_once("libs/Jos_thread.class.php");


$threads=[];


//$nextTime   = microtime(true) + INTERVAL;


$primera=[];

while(true){
    //echo "paso1\n";


    if($local_id!=""){
        $params= "accion=consultar&tabla=camaras&condicion=".urlencode("sistema=0 and encendida=1 and local_id=".$local_id)."&orden=".urlencode("id asc");
    }else{
        $params= "accion=consultar&tabla=camaras&condicion=".urlencode("sistema=0 and encendida=1")."&orden=".urlencode("id asc");    
    }
    
    
    $url=URL_BASE_SERVER."ws.php?".$params;
    //echo $url."\n\n"; exit;
    $data= json_decode(file_get_contents($url),true);
    //var_dump($data); exit;
   
    if($data["cod"]==200){
        for($i=0;$i<count($data["valores"]);$i++){
            
            if($desde=="local"){
                $cadena_conexion=$data["valores"][$i]["url_conexion"];
            }else{ //$desde=="server"
                $cadena_conexion=$data["valores"][$i]["url_desdeserver"];
            }
            
          
            
            $segundos_analizar=$data["valores"][$i]["segundos_analizar"];
            $porcentaje_mov=$data["valores"][$i]["porcentaje_mov"];
            $dontCare=$data["valores"][$i]["dontCare"];
            $fps=$data["valores"][$i]["fps"];
            $maximo_videos=$data["valores"][$i]["maximo_videos"];
            $redimesionframe=$data["valores"][$i]["redimesionframe"]/100;
            $sensibilidad=$data["valores"][$i]["sensibilidad"];
            
        
            
        
            $cmd="python3.7 motor/guarda_movimientosV2.py ".FTP_SERVER." ".FTP_USER." ".FTP_PASS." '".$cadena_conexion;
            $cmd.="' ".$data["valores"][$i]["local_id"]." ".$data["valores"][$i]["id"]." ";
            $cmd.=$segundos_analizar." ";
            $cmd.=$porcentaje_mov." ";
            $cmd.=$dontCare." ";
            $cmd.=$fps." ";
            $cmd.=$maximo_videos." ";
            $cmd.=$redimesionframe." ";
            $cmd.=$sensibilidad." ";

            $cmd.="";

            echo "cmd1->".$cmd."\n\n";
            //exit;

          
            if(!isset($threads[$data["valores"][$i]["id"]]) or $threads[$data["valores"][$i]["id"]]==NULL){
                echo "No existia el proceso, es una camara nueva encendida\n";
                $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                $threads[$data["valores"][$i]["id"]]->start();
            }else{
                
                echo "El proceso ya estaba en marcha\n";
                if(!$threads[$data["valores"][$i]["id"]]->isrunning()){
                    echo "Pero se habia parado\n";
                    
                    $threads[$data["valores"][$i]["id"]]->stop();
                    $threads[$data["valores"][$i]["id"]]=NULL;
                    sleep(3);
                    $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                    $threads[$data["valores"][$i]["id"]]->start();
                    echo "Camara ".$data["valores"][$i]["id"]." reiniciada2\n";
                    
                }
            }
        
            
            $tiempo_final = microtime(true);
            
            //echo "tiempo_final:".$tiempo_final."\n";
            //echo "tiempo_inicial:".$threads[$data["valores"][$i]["id"]]->tiempo_inicial."\n";
            
            
            $tiempo = $tiempo_final - $threads[$data["valores"][$i]["id"]]->tiempo_inicial; 
            echo "tiempo en marcha:".$tiempo."\n";


            if($tiempo>CONFIG_TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS){
                echo "\n\nSupero el tiempo maximo\n\n";
                //$threads[$data["valores"][$i]["id"]]->tiempo_inicial = microtime(true);
                
                
                $threads[$data["valores"][$i]["id"]]->stop();
                $threads[$data["valores"][$i]["id"]]=NULL;
                sleep(3);
                $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                $threads[$data["valores"][$i]["id"]]->start();
                echo "Camara ".$data["valores"][$i]["id"]." reiniciada\n";
            }

        }
    }
    //exit;
   

    //echo "Numero de procesos creados:".count($threads)."\n\n";
    sleep(10);
    

}
    




