<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 06/07/2021
 */
//python3.7 motor/guarda_movimientos.py 217.61.112.100 testuser prueba123 'rtsp://admin:bakcAse4@172.16.51.52:554/cam/realmonitor?channel=1&subtype=0' 3 3
//HCVR_ch1_main_20210726000000_20210726015959.dav

$local_id="";
if(isset($argv[1]) and $argv[1]!=""){
    $local_id=$argv[1];    
}

$desde="local";
if(isset($argv[2]) and $argv[2]!=""){
    $desde="server";
}


//define("INTERVAL", 60*10 ); // 5 minutes


require_once("config/rutas.php");
require_once("libs/Jos_thread.class.php");


$threads=[];


//$nextTime   = microtime(true) + INTERVAL;


$primera=[];

while(true){
    //echo "paso1\n";

    
    if($local_id!=""){
        $params= "accion=consultar&tabla=camaras&condicion=".urlencode("sistema=0 and encendida=1 and local_id=".$local_id)."&orden=".urlencode("id asc");
    }else{
        $params= "accion=consultar&tabla=camaras&condicion=".urlencode("sistema=0 and encendida=1")."&orden=".urlencode("id asc");    
    }
    
    
    
    $url=URL_BASE_SERVER."ws.php?".$params;
    //echo $url."\n\n"; exit;
    $data= json_decode(file_get_contents($url),true);
    //var_dump($data); exit;
    
    if($data["cod"]==200){
        for($i=0;$i<count($data["valores"]);$i++){
            
            if($desde=="local"){
                $cadena_conexion=$data["valores"][$i]["url_conexion"];
            }else{ //$desde=="server"
                $cadena_conexion=$data["valores"][$i]["url_desdeserver"];
            }
            
            $cmd="python3.7 motor/guarda_movimientos.py ".FTP_SERVER." ".FTP_USER." ".FTP_PASS." '".$cadena_conexion;
            $cmd.="' ".$data["valores"][$i]["local_id"]." ".$data["valores"][$i]["id"]." ";
            $cmd.=CONFIG_VAR1." ";
            $cmd.=CONFIG_VAR2." ";
            $cmd.=CONFIG_VAR3." ";
            $cmd.=CONFIG_VAR4." ";
            $cmd.=CONFIG_contourArea." ";
            $cmd.=CONFIG_maximo_videos." ";
            $cmd.=CONFIG_frames_a_analizar." ";
            $cmd.=CONFIG_frames_con_movimiento." ";
            $cmd.=CONFIG_FRAMES_DESPUES." ";
            $cmd.=CONFIG_frames_guardados." ";
            $cmd.=CONFIG_REDIMENSIONFRAME." ";
            $cmd.=CONFIG_FPS;



            $cmd.="";
//python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@172.16.51.52:554/cam/realmonitor?channel=1&subtype=0' 1 1 21 21 42 255 1200 60 30 24 100 120 0.60 10.0
        
            
        /*    
python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@nouesmalt.duckdns.org:779/cam/realmonitor?channel=1&subtype=0' 1 1 21 21 42 255 1300 60 30 24 100 120 0.60 10.0

python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@nouesmalt.duckdns.org:777/cam/realmonitor?channel=1&subtype=0' 1 2 21 21 42 255 1300 60 30 24 100 120 0.60 10.0

python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@nouesmalt.duckdns.org:778/cam/realmonitor?channel=1&subtype=0' 1 3 21 21 42 255 1300 60 30 24 100 120 0.60 10.0

python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@nouesmalt.duckdns.org:780/cam/realmonitor?channel=1&subtype=0' 1 4 21 21 42 255 1300 60 30 24 100 120 0.60 10.0

python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@nouesmalt.duckdns.org:781/cam/realmonitor?channel=1&subtype=0' 1 5 21 21 42 255 1300 60 30 24 100 120 0.60 10.0

python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@nouesmalt.duckdns.org:782/cam/realmonitor?channel=1&subtype=0' 1 6 21 21 42 255 1300 60 30 24 100 120 0.60 10.0
*/
            

            echo $cmd."\n\n";
  

            
            if(!isset($threads[$data["valores"][$i]["id"]]) or $threads[$data["valores"][$i]["id"]]==NULL){
                echo "No existia el proceso, es una camara nueva encendida\n";
                echo $cmd."\n\n";
                $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                $threads[$data["valores"][$i]["id"]]->start();
            }
            
            
            $tiempo_final = microtime(true);
            
            //echo "tiempo_final:".$tiempo_final."\n";
            //echo "tiempo_inicial:".$threads[$data["valores"][$i]["id"]]->tiempo_inicial."\n";
            
            
            $tiempo = $tiempo_final - $threads[$data["valores"][$i]["id"]]->tiempo_inicial; 
            //echo "tiempo en marcha:".$tiempo."\n";

            if($tiempo>CONFIG_TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS){
                echo "\n\nSupero el tiempo maximo\n\n";
                //$threads[$data["valores"][$i]["id"]]->tiempo_inicial = microtime(true);
                
                
                $threads[$data["valores"][$i]["id"]]->stop();
                $threads[$data["valores"][$i]["id"]]=NULL;
                sleep(3);
                $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                $threads[$data["valores"][$i]["id"]]->start();
                echo "Camara ".$data["valores"][$i]["id"]." reiniciada\n";
            }
            
            
            
            
            /*
            if(!isset($threads[$data["valores"][$i]["id"]]) or $threads[$data["valores"][$i]["id"]]==NULL){
                echo "No existia el proceso, es una camara nueva encendida\n";
                $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                $threads[$data["valores"][$i]["id"]]->start();
            }else{
                if(!$threads[$data["valores"][$i]["id"]]->isrunning()){
                    $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                    $threads[$data["valores"][$i]["id"]]->start();
                }else{
                    echo "El proceso sigue en marcha\n";
                    
                    $tiempo_final = microtime(true);
                    $tiempo = $tiempo_final - $threads[$data["valores"][$i]["id"]]->tiempo_inicial; 
                    echo "tiempo en marcha:".$tiempo."\n";
                    
                    if($tiempo>CONFIG_TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS){
                        echo "\n\nSupero el tiempo maximo\n\n";
                        //$threads[$data["valores"][$i]["id"]]->tiempo_inicial = microtime(true);
                        $threads[$data["valores"][$i]["id"]]->stop();
                        $threads[$data["valores"][$i]["id"]]=NULL;
                        sleep(3);
                        $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                        $threads[$data["valores"][$i]["id"]]->start();
                        echo "Camara ".$data["valores"][$i]["id"]." reiniciada\n";
                    }
                    
                }
            }
             * 
             */
            
        }
    }
    //exit;
    
    /*
    foreach($threads as $camara_id=>$th){

        $params= "accion=consultar&tabla=camaras&condicion=".urlencode("id=".$camara_id)."&orden=".urlencode("id asc");
        $url=URL_BASE_SERVER."ws.php?".$params;
        $data= json_decode(file_get_contents($url),true);
        $sistema=$data["valores"][0]["sistema"];
        $encendida=$data["valores"][0]["encendida"];

        echo "camara_id:".$camara_id."\n";
        echo "sistema:".$sistema."\n";
        echo "encendida:".$encendida."\n";

        if($sistema==0 and $encendida==1){
            echo "sigue encendida!\n";
            if(!$th->isrunning()){
                
                if($desde=="local"){
                    $cadena_conexion=$data["valores"][$i]["url_conexion"];
                }else{ //$desde=="server"
                    $cadena_conexion=$data["valores"][$i]["url_desdeserver"];
                }
            
            
                echo "Se ha parado el proceso\n";
                $cmd="python3.7 motor/guarda_movimientos.py ".FTP_SERVER." ".FTP_USER." ".FTP_PASS." ".$cadena_conexion;
                $cmd.=" ".$data["valores"][0]["local_id"]." ".$data["valores"][0]["id"];
                $threads[$camara_id]=new Jos_Thread($camara_id,$cmd,true);
                $threads[$camara_id]->start();
            }else{
                echo "El proceso sigue en marcha\n";
            }
        }else{
            echo "Como ya no esta encendida o ha cambiado de sistema, paramos el proceso\n";
            $th->stop();
        }

    }
     * 
     */
    //echo "Numero de procesos creados:".count($threads)."\n\n";
    sleep(10);
    
    
    /*
    $tiempo_final = microtime(true);
    $tiempo = $tiempo_final - $tiempo_inicial; 
    echo "tiempo en marcha:".$tiempo."\n";

    if($tiempo>CONFIG_TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS){
        echo "\n\nSupero el tiempo maximo\n\n";
        $tiempo_inicial = microtime(true);
        foreach($threads as $camara_id=>$th){
            $th->stop();
            sleep(1);
            $threads[$camara_id]=NULL;
            sleep(1);
            
        }
        unset($threads);
        $threads=[];
        echo "Camaras reiniciadas\n";
        sleep(10);
    }
    
    
    if (microtime(true) >= $nextTime) {
        foreach($threads as $camara_id=>$th){
            $th->stop();
            $threads[$camara_id]=NULL;
        }    
        $nextTime = microtime(true) + INTERVAL;
        $threads=[];
    }*/
}
    




