<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 06/07/2021
 */
//python3.7 motor/guarda_movimientos.py 217.61.112.100 testuser prueba123 'rtsp://admin:bakcAse4@172.16.51.52:554/cam/realmonitor?channel=1&subtype=0' 3 3
//HCVR_ch1_main_20210726000000_20210726015959.dav

$local_id="";
if(isset($argv[1]) and $argv[1]!=""){
    $local_id=$argv[1];    
}

$desde="local";
if(isset($argv[2]) and $argv[2]!=""){
    $desde="server";
}


//define("INTERVAL", 60*10 ); // 5 minutes


require_once("config/rutas.php");
require_once("libs/Jos_thread.class.php");


$threads=[];


//$nextTime   = microtime(true) + INTERVAL;


$primera=[];

while(true){
    //echo "paso1\n";


    if($local_id!=""){
        $params= "accion=consultar&tabla=camaras&condicion=".urlencode("sistema=0 and encendida=1 and local_id=".$local_id)."&orden=".urlencode("id asc");
    }else{
        $params= "accion=consultar&tabla=camaras&condicion=".urlencode("sistema=0 and encendida=1")."&orden=".urlencode("id asc");    
    }
    
    
    
    $url=URL_BASE_SERVER."ws.php?".$params;
    //echo $url."\n\n"; exit;
    $data= json_decode(file_get_contents($url),true);
    //var_dump($data); exit;
    
    if($data["cod"]==200){
        for($i=0;$i<count($data["valores"]);$i++){
            
            if($desde=="local"){
                $cadena_conexion=$data["valores"][$i]["url_conexion"];
            }else{ //$desde=="server"
                $cadena_conexion=$data["valores"][$i]["url_desdeserver"];
            }
            
            /*
            $sensibilidad_movimiento=$data["valores"][$i]["sensibilidad_movimiento"];
            //$sensibilidad1=round($sensibilidad_movimiento*CONFIG_VAR3_MAXIMO/100);
            //$sensibilidad2=round($sensibilidad_movimiento*CONFIG_contourArea_MAXIMO/100);
            //$sensibilidad2=$sensibilidad_movimiento;
            
            
            $rango1=CONFIG_VAR3_MAXIMO-CONFIG_VAR3_MINIMO;
            //echo "rango1:".$rango1."\n";
            $calculo1=$rango1*$sensibilidad_movimiento/100;
            //echo "calculo1:".$calculo1."\n";
            //$calculo1_masminimo=$calculo1+CONFIG_VAR3_MINIMO;
            //echo "calculo1_masminimo:".$calculo1_masminimo."\n";
            //$invertido1=CONFIG_VAR3_MAXIMO-$calculo1_masminimo;
            //echo "invertido1:".$invertido1."\n";
            $invertido2_sinminimo=CONFIG_VAR3_MAXIMO-$calculo1;
            //echo "invertido2_sinminimo:".$invertido2_sinminimo."\n";
            $sensibilidad1=round($invertido2_sinminimo);
            
            
            $rango2=CONFIG_contourArea_MAXIMO-CONFIG_contourArea_MINIMO;
            //echo "rango2:".$rango2."\n";
            $calculo2=$rango2*$sensibilidad_movimiento/100;
            //echo "calculo2:".$calculo2."\n";
            $calculo2_masminimo=$calculo2+CONFIG_contourArea_MINIMO;
            //echo "calculo2_masminimo:".$calculo2_masminimo."\n";
            $sensibilidad2=round($calculo2_masminimo);
            //echo "sensibilidaddefinitiva:".$sensibilidad2."\n";
            */
            
            
            $segundos_analizar=$data["valores"][$i]["segundos_analizar"];
            $porcentaje_mov=$data["valores"][$i]["porcentaje_mov"];
            $dontCare=$data["valores"][$i]["dontCare"];
            $fps=$data["valores"][$i]["fps"];
            $maximo_videos=$data["valores"][$i]["maximo_videos"];
            $redimesionframe=$data["valores"][$i]["redimesionframe"]/100;
            $sensibilidad=$data["valores"][$i]["sensibilidad"];
            
            /*
            $cmd="python3.7 motor/guarda_movimientos.py ".FTP_SERVER." ".FTP_USER." ".FTP_PASS." '".$cadena_conexion;
            $cmd.="' ".$data["valores"][$i]["local_id"]." ".$data["valores"][$i]["id"]." ";
            $cmd.=CONFIG_VAR1." ";
            $cmd.=CONFIG_VAR2." ";
            //$cmd.=CONFIG_VAR3." ";
            $cmd.=$sensibilidad1." ";
            $cmd.=CONFIG_VAR4." ";
            //$cmd.=CONFIG_contourArea." ";
            $cmd.=$sensibilidad2." ";
            $cmd.=CONFIG_maximo_videos." ";
            $cmd.=CONFIG_frames_a_analizar." ";
            $cmd.=CONFIG_frames_con_movimiento." ";
            $cmd.=CONFIG_FRAMES_DESPUES." ";
            $cmd.=CONFIG_frames_guardados." ";
            $cmd.=CONFIG_REDIMENSIONFRAME." ";
            $cmd.=CONFIG_FPS;
            */
            
            
        
            $cmd="python3.7 motor/guarda_movimientosV2.py ".FTP_SERVER." ".FTP_USER." ".FTP_PASS." '".$cadena_conexion;
            $cmd.="' ".$data["valores"][$i]["local_id"]." ".$data["valores"][$i]["id"]." ";
            $cmd.=$segundos_analizar." ";
            $cmd.=$porcentaje_mov." ";
            $cmd.=$dontCare." ";
            $cmd.=$fps." ";
            $cmd.=$maximo_videos." ";
            $cmd.=$redimesionframe." ";
            $cmd.=$sensibilidad." ";
            
            
/*
python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@172.16.51.52:554/cam/realmonitor?channel=1&subtype=0' 1 1 21 21 X 255 X 60 30 24 100 120 0.60 10.0
        
python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@172.16.51.52:554/cam/realmonitor?channel=1&subtype=0' 1 1 21 21 20 255 1500 60 30 24 100 120 0.60 10.0
127


(el 1º cuanto mas bajo mas sensible es)
20-110
 * 
(el 2º cuanto mas alto mas sensible es)
1-1500

(el mas influyente de los es el 1º)

50sens
 * 
 * 
python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@172.16.51.223:554/cam/realmonitor?channel=1&subtype=0' 1 1 21 21 110 255 2 60 30 24 100 120 0.60 10.0
 * 
python3.7 motor/guarda_movimientos.py reconocimien.vps.webdock.cloud testuser prueba123 'rtsp://admin:bakcAse4@172.16.51.223:554/cam/realmonitor?channel=1&subtype=0' 1 1 21 21 200 255 2 60 30 24 100 120 0.60 10.0
 */
            $cmd.="";

            

            echo $cmd."\n\n";
            //exit;

/*          
            if(!isset($threads[$data["valores"][$i]["id"]]) or $threads[$data["valores"][$i]["id"]]==NULL){
                echo "No existia el proceso, es una camara nueva encendida\n";
                echo $cmd."\n\n";
                $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                $threads[$data["valores"][$i]["id"]]->start();
            }
        
            
            $tiempo_final = microtime(true);
            
            //echo "tiempo_final:".$tiempo_final."\n";
            //echo "tiempo_inicial:".$threads[$data["valores"][$i]["id"]]->tiempo_inicial."\n";
            
            
            $tiempo = $tiempo_final - $threads[$data["valores"][$i]["id"]]->tiempo_inicial; 
            //echo "tiempo en marcha:".$tiempo."\n";


            if($tiempo>CONFIG_TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS){
                echo "\n\nSupero el tiempo maximo\n\n";
                //$threads[$data["valores"][$i]["id"]]->tiempo_inicial = microtime(true);
                
                
                $threads[$data["valores"][$i]["id"]]->stop();
                $threads[$data["valores"][$i]["id"]]=NULL;
                sleep(3);
                $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                $threads[$data["valores"][$i]["id"]]->start();
                echo "Camara ".$data["valores"][$i]["id"]." reiniciada\n";
            }
*/
            
            
            
            /*
            if(!isset($threads[$data["valores"][$i]["id"]]) or $threads[$data["valores"][$i]["id"]]==NULL){
                echo "No existia el proceso, es una camara nueva encendida\n";
                $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                $threads[$data["valores"][$i]["id"]]->start();
            }else{
                if(!$threads[$data["valores"][$i]["id"]]->isrunning()){
                    $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                    $threads[$data["valores"][$i]["id"]]->start();
                }else{
                    echo "El proceso sigue en marcha\n";
                    
                    $tiempo_final = microtime(true);
                    $tiempo = $tiempo_final - $threads[$data["valores"][$i]["id"]]->tiempo_inicial; 
                    echo "tiempo en marcha:".$tiempo."\n";
                    
                    if($tiempo>CONFIG_TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS){
                        echo "\n\nSupero el tiempo maximo\n\n";
                        //$threads[$data["valores"][$i]["id"]]->tiempo_inicial = microtime(true);
                        $threads[$data["valores"][$i]["id"]]->stop();
                        $threads[$data["valores"][$i]["id"]]=NULL;
                        sleep(3);
                        $threads[$data["valores"][$i]["id"]]=new Jos_Thread($data["valores"][$i]["id"],$cmd,true);
                        $threads[$data["valores"][$i]["id"]]->start();
                        echo "Camara ".$data["valores"][$i]["id"]." reiniciada\n";
                    }
                    
                }
            }
             * 
             */
            
        }
    }
    exit;
    
    /*
    foreach($threads as $camara_id=>$th){

        $params= "accion=consultar&tabla=camaras&condicion=".urlencode("id=".$camara_id)."&orden=".urlencode("id asc");
        $url=URL_BASE_SERVER."ws.php?".$params;
        $data= json_decode(file_get_contents($url),true);
        $sistema=$data["valores"][0]["sistema"];
        $encendida=$data["valores"][0]["encendida"];

        echo "camara_id:".$camara_id."\n";
        echo "sistema:".$sistema."\n";
        echo "encendida:".$encendida."\n";

        if($sistema==0 and $encendida==1){
            echo "sigue encendida!\n";
            if(!$th->isrunning()){
                
                if($desde=="local"){
                    $cadena_conexion=$data["valores"][$i]["url_conexion"];
                }else{ //$desde=="server"
                    $cadena_conexion=$data["valores"][$i]["url_desdeserver"];
                }
            
            
                echo "Se ha parado el proceso\n";
                $cmd="python3.7 motor/guarda_movimientos.py ".FTP_SERVER." ".FTP_USER." ".FTP_PASS." ".$cadena_conexion;
                $cmd.=" ".$data["valores"][0]["local_id"]." ".$data["valores"][0]["id"];
                $threads[$camara_id]=new Jos_Thread($camara_id,$cmd,true);
                $threads[$camara_id]->start();
            }else{
                echo "El proceso sigue en marcha\n";
            }
        }else{
            echo "Como ya no esta encendida o ha cambiado de sistema, paramos el proceso\n";
            $th->stop();
        }

    }
     * 
     */
    //echo "Numero de procesos creados:".count($threads)."\n\n";
    sleep(10);
    
    
    /*
    $tiempo_final = microtime(true);
    $tiempo = $tiempo_final - $tiempo_inicial; 
    echo "tiempo en marcha:".$tiempo."\n";

    if($tiempo>CONFIG_TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS){
        echo "\n\nSupero el tiempo maximo\n\n";
        $tiempo_inicial = microtime(true);
        foreach($threads as $camara_id=>$th){
            $th->stop();
            sleep(1);
            $threads[$camara_id]=NULL;
            sleep(1);
            
        }
        unset($threads);
        $threads=[];
        echo "Camaras reiniciadas\n";
        sleep(10);
    }
    
    
    if (microtime(true) >= $nextTime) {
        foreach($threads as $camara_id=>$th){
            $th->stop();
            $threads[$camara_id]=NULL;
        }    
        $nextTime = microtime(true) + INTERVAL;
        $threads=[];
    }*/
}
    




