<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 08-jul-2021, 12:35:07.
 */

//para cada video le paso el reconocedor, y creo las imagenes sumando los segundos pasados del video con su tiempo y borro el video luego
//para cada imagen generada tendremos que pertenece a una persona, compruebo qe para esa persona y esa camara haga mas de X segundos qe no se haya guardado y la guardo

require_once("config/rutas.php");
require_once("libs/Jos_thread.class.php");
require_once("libs/mysql.class.php");

$sql=new Conectar();
$tmp=new Conectar();
$tmp2=new Conectar();

$threads=[];

$ram=new Jos_Thread(0,"",true);

/*
if($ram->queda_ram()){
    echo "\nqueda ram\n";
}else{
    echo "\nNO queda ram\n";
}
exit;
*/


while(true){
    
    /*
    if(!$ram->queda_espacio()){
        $ram->libera_espacio();  //borro los videos a pelo, entonces me estoy perdiendo movimientos...
    }
    */
    
    //recorro los locales con camaras encendidas
    $sql->Consultar("locales", "*", "id>0", "id asc", false);
    if($sql->num>0){
        do{
            $tmp->Consultar("camaras", "*", "local_id=".$sql->row["id"]." and encendida=1", "id asc", true);
            if($tmp->num>0){
                
                echo "el local ".$tmp->row["id"]." tiene camaras encendidas\n";
                
                do{
                    /*--INI--procesa_fotos_def_borrosaparteV2*/
/*
                    $params="";
                    $params.=CONFIG_umbral_parecidosentresi." ";
                    $params.=CONFIG_umbral." ";
                    $params.=CONFIG_umbral_solounaodos." ";
                    $params.=CONFIG_umbral_delasmedias." ";
                    $params.=CONFIG_umbral_segurisimo." ";
                    $params.=CONFIG_veces_umbral_medias_augmenta." ";
                    $params.=CONFIG_umbral_junto." ";
                    $params.=CONFIG_umbral_junto2." ";
                    $params.=CONFIG_porcentaje_veces_supera." ";
                    $params.=CONFIG_umbral_enfocado." ";
                    $params.=CONFIG_umbral_solounaodos_enfocado." ";
                    $params.=CONFIG_umbral_delasmedias_enfocado." ";
                    $params.=CONFIG_umbral_segurisimo_enfocado." ";
                    $params.=CONFIG_veces_umbral_medias_augmenta_enfocado." ";
                    $params.=CONFIG_umbral_junto_enfocado." ";
                    $params.=CONFIG_umbral_junto2_enfocado." ";
                    $params.=CONFIG_porcentaje_veces_supera_enfocado." ";
                    $params.=CONFIG_umbral_desenfocado." ";
                    $params.=CONFIG_umbral_solounaodos_desenfocado." ";
                    $params.=CONFIG_umbral_delasmedias_desenfocado." ";
                    $params.=CONFIG_umbral_segurisimo_desenfocado." ";
                    $params.=CONFIG_veces_umbral_medias_augmenta_desenfocado." ";
                    $params.=CONFIG_umbral_junto_desenfocado." ";
                    $params.=CONFIG_umbral_junto2_desenfocado." ";
                    $params.=CONFIG_porcentaje_veces_supera_desenfocado." ";
                    $params.=CONFIG_umbral_desenfocado_globales." ";
                    $params.=CONFIG_umbral_solounaodos_desenfocado_globales." ";
                    $params.=CONFIG_umbral_delasmedias_desenfocado_globales." ";
                    $params.=CONFIG_umbral_segurisimo_desenfocado_globales." ";
                    $params.=CONFIG_veces_umbral_medias_augmenta_desenfocado_globales." ";
                    $params.=CONFIG_umbral_junto_desenfocado_globales." ";
                    $params.=CONFIG_umbral_junto2_desenfocado_globales." ";
                    $params.=CONFIG_porcentaje_veces_supera_desenfocado_globales." ";
                    $params.=CONFIG_DIFERENCIA_PROMERO_Y_SEGUNDO." ";
                    $params.=CONFIG_MAXIMAS_REPETICIONES_GUARDADO." ";
                    $params.=CONFIG_DIFERENCIA_ANCHO_OJOS." ";
                    $params.=CONFIG_DIFERENCIA_ALTURAS." ";
                    $params.=CONFIG_UMBRAL_ENFOQUE." ";
                    $params.=CONFIG_UMBRAL_ENFOQUE_MAXIMO." ";
                    $params.=CONFIG_UMBRAL_ENFOQUE_MAXIMO_CARA_procesafoto." ";
                    $params.=CONFIG_UMBRAL_DIFERENCIA_ENFOQUE." ";
                    $params.=CONFIG_UMBRAL_ENFOQUE_GLOBALES;

                    
                    $cmd="python3.7 motor/procesa_fotos_def_borrosaparteV2.py ".$sql->row["id"]." ".$tmp->row["id"]." ".$params;
                    
                    if(!isset($threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]) or $threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]==NULL){
                        echo "No existia el proceso:"."pf_".$sql->row["id"]."_".$tmp->row["id"]."\n";
                        $threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]=new Jos_Thread("pf_".$sql->row["id"]."_".$tmp->row["id"],$cmd,true);
                        $threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]->start();
                    }else{
                        echo "Ya existia:"."pf_".$sql->row["id"]."_".$tmp->row["id"]."\n";
                        if(!$threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]->isrunning()){
                            echo "Y se ha parado, lo voy a parar del todo y reencender\n";
                            $threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]->stop();
                            $threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]=NULL;
                            
                            $threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]=new Jos_Thread("pf_".$sql->row["id"]."_".$tmp->row["id"],$cmd,true);
                            $threads["pf_".$sql->row["id"]."_".$tmp->row["id"]]->start();
                        }
                    }
*/
                    /*--FIN--procesa_fotos_def_borrosaparteV2*/
                    
                    
                    
                    /*--INI--procesa_videosV6*/    
                    $directorio_videos=URL_FTP_BASE.'motor/videos/'.$sql->row["id"].'/'.$tmp->row["id"].'/';
                    $pesos=[];
                    $dir = opendir($directorio_videos);
                    while ($elemento = readdir($dir)){
                        if( $elemento != "." && $elemento != ".."){
                            $pesos[$elemento]=filesize($directorio_videos.$elemento);
                        }
                    }
                    sleep(6);
                    $subidos=[];
                    $dir = opendir($directorio_videos);
                    while ($elemento = readdir($dir)){
                        if( $elemento != "." && $elemento != ".."){
                            if($pesos[$elemento]==filesize($directorio_videos.$elemento)){
                                echo "Video completamente subido:".$elemento."\n";
                                $subidos[]=$elemento;
                            }
                        }
                    }

                    for($s=0;$s<count($subidos);$s++){
                        //cuando un video empieza a procesarse, creara este fichero, luego se borra al final del propio procesa_videosV6.py
                        
                        if(file_exists("./aux/".$subidos[$s].".txt")){ 
                            echo "Aun se esta procesando el video:".$subidos[$s]."\n";
                        }else{


                            $numero_videos=0;
                            $dir = opendir("./aux");
                            while ($elemento = readdir($dir)){
                                if( $elemento != "." && $elemento != ".."){
                                    $pos= strpos($elemento, "procesar");
                                    if($pos===false){
                                        $numero_videos++;
                                    }
                                }
                            }
                            if($numero_videos<CONFIG_LIMITE_VIDEOS){

                                if($ram->queda_ram(CONFIG_LIMITE_RAM)){ //antes de lanzar 1 video a analizar, veo si queda ram
                                    
                                    $cmd1="echo '".date("Y-m-d H:i:s")."' > ./aux/".$subidos[$s].".txt";
                                    echo $cmd1."\n";
                                    exec($cmd1);
                                    $cmd1="chmod -R 777 ./aux/".$subidos[$s].".txt";
                                    echo $cmd1."\n";
                                    exec($cmd1);

                                    $cmd1="echo '".date("Y-m-d H:i:s")." - ".$subidos[$s]."' >> ./aux/procesar_".$sql->row["id"]."_".$tmp->row["id"].".txt";
                                    echo $cmd1."\n";
                                    exec($cmd1);


                                    $params="";
                                    $params.=CONFIG_desiredFaceWidth." ";
                                    $params.=CONFIG_margen_cruce_linea." ";
                                    $params.=CONFIG_frame_rate." ";
                                    $params.=CONFIG_redimensionVideoWidth." ";
                                    $params.=CONFIG_redimensionVideoHeight." ";
                                    $params.=CONFIG_analisisLineasImagenWidth." ";
                                    $params.=CONFIG_analisisLineasImagenHeight." ";
                                    $params.=CONFIG_margenGrosorLinea." ";
                                    $params.=CONFIG_contornoAreaCruceLinea." ";
                                    $params.=CONFIG_MinimoContornoConsiderarloCruce." ";
                                    $params.=CONFIG_TiempoTrascurridoUltimoCruce." ";
                                    $params.=CONFIG_TiempoDeCruce." ";
                                    $params.=CONFIG_redimension_imagen_captura_caras_w." ";
                                    $params.=CONFIG_redimension_imagen_captura_caras_h." ";
                                    $params.=CONFIG_scale_factor." ";
                                    $params.=CONFIG_resize_w." ";
                                    $params.=CONFIG_resize_h." ";
                                    $params.=CONFIG_mean1." ";
                                    $params.=CONFIG_mean2." ";
                                    $params.=CONFIG_mean3." ";
                                    $params.=CONFIG_recuadro_tamanyo_rostro." ";
                                    $params.=CONFIG_redimension_rostro;

                                    $cmd1=RUTA_PYTHON." ".RUTA_PROYECTO."motor/procesa_videosV6.py ".$sql->row["id"]." ".$tmp->row["id"]." '".$subidos[$s]."'"." '".RUTA_PROYECTO."' ".CONFIG_SENSIBILIDAD_ES_CARA." '".URL_FTP_BASE."' ".$params." > /dev/null 2>/dev/null &";
                                    echo $cmd1."\n";
                                    //exit;
                                    //exec($cmd1);
                                }else{
                                    echo "No queda RAM para entrar a analizar otro video, esperare unos 20 segundos antes de seguir\n";
                                    
                                    $intentos=0;
                                    while(!$ram->queda_ram(CONFIG_LIMITE_RAM) and $intentos<4){
                                        sleep(5);
                                        $intentos++;
                                        echo "Esperando(".($intentos*5)." segs).. no queda ram...\n";
                                    }
                                }

                            }else{
                                echo "Muchos videos en cola (".$numero_videos."), espero y sigo...\n";
                                sleep(1);
                            }

                        }

                    }
                    echo "fin de procesa_videosV6\n";
                    exit;
                    /*--FIN--procesa_videosV6*/

                
                    


                    
                    /*--INI--cruza_lineas*/    
/*
                    $tmp2->Consultar("lineas", "*", "camara_id=".$tmp->row["id"]." and eliminada=0", "id asc", false);
                    if($tmp2->num>0){
                        echo "la camara ".$tmp->row["id"]." tiene lineas\n";
                        do{
                            $cmd="python3.7 motor/cruza_lineas.py ".$sql->row["id"]." ".$tmp->row["id"]." ".$tmp2->row["id"]." ".$tmp2->row["x1"]." ".$tmp2->row["y1"]." ".$tmp2->row["x2"]." ".$tmp2->row["y2"];
                            
                            $nombre_proceso="cl_".$sql->row["id"]."_".$tmp->row["id"]."_".$tmp2->row["id"];
                            
                            if(!isset($threads[$nombre_proceso]) or $threads[$nombre_proceso]==NULL){
                                echo "No existia el proceso de linea:".$nombre_proceso."\n";
                                $threads[$nombre_proceso]=new Jos_Thread($nombre_proceso,$cmd,true);
                                $threads[$nombre_proceso]->start();
                            }else{
                                echo "Ya existia el proceso de linea:".$nombre_proceso."\n";
                                if(!$threads[$nombre_proceso]->isrunning()){
                                    echo "Y se ha parado, lo voy a reanudar\n";
                                    
                                    $threads[$nombre_proceso]->stop();
                                    $threads[$nombre_proceso]=NULL;
                                    
                                    $threads[$nombre_proceso]=new Jos_Thread($nombre_proceso,$cmd,true);
                                    $threads[$nombre_proceso]->start();
                                }else{
                                    echo "El proceso de linea ".$nombre_proceso." sigue en marcha\n";
                                }
                            }
                            

                        }while($tmp2->Siguiente());
                    }
*/
                    /*--FIN--cruza_lineas*/

                
                }while($tmp->Siguiente());
                
            }
        }while($sql->Siguiente());
    }    
    
    
    
    //recorro los threads por si hay alguno qe apagar qe ya no esta encendida la camara, o que no exista la linea o la camara
    echo "\n\nrecorro los threads por si hay alguno qe apagar qe ya no esta encendida la camara, o que no exista la linea o la camara\n";
    $sql->Consultar("camaras", "*", "encendida=0", "id asc", false);
    if($sql->num>0){
        do{
            $camara_id=$sql->row["id"];
            echo "esta camara esta apagada:".$camara_id."\n";
            $aux= explode("_", $identificador);
            $camara_id_proceso=$aux[2];

            if($camara_id==$camara_id_proceso){
                echo "Teniamos un procesos de esa camara, su identificador es:->".$identificador."<- vamos a pararlo\n";
                $th->stop();
                $threads[$identificador]=NULL;
                echo "OK, parado!\n";
            }
        }while($sql->Siguiente());
    }
    
    /*
    //NO, esta version es viejo
    foreach($threads as $identificador=>$th){
        $aux= explode("_", $identificador);
        
        $camara_id=$aux[2];
        
        if(count($aux)==2){

            $sql->Consultar("camaras", "*", "id=".$camara_id." and encendida=1", "id asc", false);
            if($sql->num==0){
                $th->stop();
                $threads[$camara_id."_".$i]=NULL;
            }
        }elseif(count($aux)==4){
            $linea_id=$aux[3];
            
            $sql->Consultar("camaras", "*", "id=".$camara_id." and encendida=1", "id asc", false);
            if($sql->num==0){
                
                $tmp->Consultar("lineas", "*", "id=".$linea_id, "id asc", false);
                if($tmp->num>0){
                    $th->stop();
                    $threads[$camara_id."_".$linea_id."_".$i]=NULL;
                }
            }
        }
    }
    */
    
    
    
    echo "TODO EL RECORRIDO TERMINADO, ESPERO 1 SEGUNDITO Y VUELVO A LANZAR!!\n";
    sleep(1);
    //exit;
}

