<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 08-jul-2021, 12:35:07.
 */

//para cada video le paso el reconocedor, y creo las imagenes sumando los segundos pasados del video con su tiempo y borro el video luego
//para cada imagen generada tendremos que pertenece a una persona, compruebo qe para esa persona y esa camara haga mas de X segundos qe no se haya guardado y la guardo


define("LIMITE_RAM",85);
define("LIMITE_VIDEOS",25);



require_once("includes/rutas.php");
require_once("libs/Jos_thread.class.php");
require_once("libs/mysql.class.php");

$sql=new Conectar();
$tmp=new Conectar();
$tmp2=new Conectar();

$threads=[];

$ram=new Jos_Thread(0,"",true);

/*
if($ram->queda_ram()){
    echo "\nqueda ram\n";
}else{
    echo "\nNO queda ram\n";
}
exit;
*/

define("TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS",60*10); //10 minutos

while(true){
    
    
    if(!$ram->queda_espacio()){
        $ram->libera_espacio();
    }
    
    //recorro los locales con camaras encendidas
    $sql->Consultar("locales", "*", "id>0", "id asc", false);
    if($sql->num>0){
        do{
            $tmp->Consultar("camaras", "*", "local_id=".$sql->row["id"]." and encendida=1", "id asc", false);
            if($tmp->num>0){
                
                echo "el local ".$sql->row["id"]." tiene camaras encendidas\n";
                
                do{
                    
                    $cmd=[];
                    /*
                    switch($tmp->row["sistema"]){
                        case 0: //0 son las ip
                            $cmd[]="python3.7 motor/procesa_videosV5.py ".$sql->row["id"]." ".$tmp->row["id"];
                            break;
                        case 1: //1 de grabador
                            $cmd[]="python3.7 motor/procesa_videosV4.py ".$sql->row["id"]." ".$tmp->row["id"]." ".$tmp->row["url_conexion"];
                            break;
                    }
                     */



                    
                    $cmd[]="python3.7 motor/procesa_fotos_def_borrosaparteV2.py ".$sql->row["id"]." ".$tmp->row["id"];
                    //$cmd[]="python3.7 motor/cruza_lineas_V2.py ".$sql->row["id"]." ".$tmp->row["id"];
                    //var_dump($cmd);
                    //exit;
                    for($i=0;$i<count($cmd);$i++){
                        echo $cmd[$i]."\n";
                        

                        if(!isset($threads[$tmp->row["id"]."_".$i]) or $threads[$tmp->row["id"]."_".$i]==NULL){
                            echo "No existia el proceso:".$tmp->row["id"]."_".$i."\n";
                            $threads[$tmp->row["id"]."_".$i]=new Jos_Thread($tmp->row["id"]."_".$i,$cmd[$i],true);
                            $threads[$tmp->row["id"]."_".$i]->start();
                        }else{
                            echo "Ya existia\n";
                            if(!$threads[$tmp->row["id"]."_".$i]->isrunning()){
                                echo "Y se ha parado, lo voy a reanudar\n";
                                $threads[$tmp->row["id"]."_".$i]=new Jos_Thread($tmp->row["id"]."_".$i,$cmd[$i],true);
                                $threads[$tmp->row["id"]."_".$i]->start();
                            }else{
                                echo "-El proceso sigue en marcha\n";
                                
                                $tiempo_final = microtime(true);
                                $tiempo = $tiempo_final - $tiempo_inicial; 

                                if($tiempo>TIEMPO_MAXIMO_CAMARAS_ENCENDIDAS){
                                    echo "Supero el tiempo maximo\n";
                                    $tiempo_inicial = microtime(true);
                                    $threads[$tmp->row["id"]."_".$i]->stop();
                                    sleep(2);
                                    $threads[$tmp->row["id"]."_".$i]->start();
                                    echo "Camaras reiniciadas\n";
                                }
                            }
                        }
                    }
                    //exit;
                    

                    if($ram->queda_ram(LIMITE_RAM)){
                        
                        $directorio_videos='/home/testuser/motor/videos/'.$sql->row["id"].'/'.$tmp->row["id"].'/';
                        $pesos=[];
                        $dir = opendir($directorio_videos);
                        while ($elemento = readdir($dir)){
                            if( $elemento != "." && $elemento != ".."){
                                $pesos[$elemento]=filesize($directorio_videos.$elemento);
                            }
                        }
                        sleep(6);
                        $subidos=[];
                        $dir = opendir($directorio_videos);
                        while ($elemento = readdir($dir)){
                            if( $elemento != "." && $elemento != ".."){
                                if($pesos[$elemento]==filesize($directorio_videos.$elemento)){
                                    echo "Video completamente subido:".$elemento."\n";
                                    $subidos[]=$elemento;
                                }
                            }
                        }
                        
                        for($s=0;$s<count($subidos);$s++){
                            if(file_exists("./aux/".$subidos[$s].".txt")){
                                echo "Aun se esta procesando el video:".$subidos[$s]."\n";
                            }else{
                                
                                

                                $numero_videos=0;
                                $dir = opendir("./aux");
                                while ($elemento = readdir($dir)){
                                    if( $elemento != "." && $elemento != ".."){
                                        $pos= strpos($elemento, "procesar");
                                        if($pos===false){
                                            $numero_videos++;
                                        }
                                    }
                                }
                                if($numero_videos<LIMITE_VIDEOS){

                                    while(!$ram->queda_ram(LIMITE_RAM)){
                                        echo "Esperando.. no queda ram...\n";
                                        sleep(5);
                                    }

                                    $cmd1="echo '".date("Y-m-d H:i:s")."' > ./aux/".$subidos[$s].".txt";
                                    echo $cmd1."\n";
                                    exec($cmd1);
                                    $cmd1="chmod -R 777 ./aux/".$subidos[$s].".txt";
                                    echo $cmd1."\n";
                                    exec($cmd1);

                                    $cmd1="echo '".date("Y-m-d H:i:s")." - ".$subidos[$s]."' >> ./aux/procesar_".$sql->row["id"]."_".$tmp->row["id"].".txt";
                                    echo $cmd1."\n";
                                    exec($cmd1);


                                    $cmd1="python3.7 /var/www/html/reconocimientoFacial/proyecto_definitivo/motor/procesa_videosV6.py ".$sql->row["id"]." ".$tmp->row["id"]." '".$subidos[$s]."'"." > /dev/null 2>/dev/null &";
                                    echo $cmd1."\n";
                                    exec($cmd1);
                                    //exit;
                                    
                                }else{
                                    echo "Muchos videos en cola (".$numero_videos."), espero y sigo...\n";
                                    //sleep(10);
                                }

                            }
                            
                        }
                        
        
                    }else{
                        echo "NO queda ram\n";
                    }
                    
                    
                    /*
                    $tmp2->Consultar("lineas", "*", "camara_id=".$tmp->row["id"]." and eliminada=0", "id asc", false);
                    if($tmp2->num>0){
                        echo "la camara ".$tmp->row["id"]." tiene lineas\n";
                        do{
                            $cmd="python3.7 motor/cruza_lineas.py ".$sql->row["id"]." ".$tmp->row["id"]." ".$tmp2->row["id"]." ".$tmp2->row["x1"]." ".$tmp2->row["y1"]." ".$tmp2->row["x2"]." ".$tmp2->row["y2"];
                            
                            
                            if(!isset($threads[$tmp->row["id"]."_".$tmp2->row["id"]."_".$i]) or $threads[$tmp->row["id"]."_".$tmp2->row["id"]."_".$i]==NULL){
                                echo "No existia el proceso de linea:".$tmp->row["id"]."_".$tmp2->row["id"]."_".$i."\n";
                                $threads[$tmp->row["id"]."_".$tmp2->row["id"]."_".$i]=new Jos_Thread($tmp->row["id"]."_".$tmp2->row["id"]."_".$i,$cmd,true);
                                $threads[$tmp->row["id"]."_".$tmp2->row["id"]."_".$i]->start();
                            }else{
                                echo "Ya existia el proceso de linea\n";
                                if(!$threads[$tmp->row["id"]."_".$tmp2->row["id"]."_".$i]->isrunning()){
                                    echo "Y se ha parado, lo voy a reanudar\n";
                                    $threads[$tmp->row["id"]."_".$tmp2->row["id"]."_".$i]=new Jos_Thread($tmp->row["id"]."_".$tmp2->row["id"]."_".$i,$cmd,true);
                                    $threads[$tmp->row["id"]."_".$tmp2->row["id"]."_".$i]->start();
                                }else{
                                    echo "El proceso sigue en marcha\n";
                                }
                            }
                            

                        }while($tmp2->Siguiente());
                    }
                    */

                
                }while($tmp->Siguiente());
                
            }
        }while($sql->Siguiente());
    }    
    
    //recorro los threads por si hay alguno qe apagar qe ya no esta encendido
    foreach($threads as $identificador=>$th){
        $aux= explode("_", $identificador);
        
        if(count($aux)==2){
            $camara_id=$aux[0];
            $i=$aux[1];

            $sql->Consultar("camaras", "*", "id=".$camara_id." and encendida=1", "id asc", false);
            if($sql->num==0){
                $th->stop();
                $threads[$camara_id."_".$i]=NULL;
            }
        }elseif(count($aux)==3){
            $camara_id=$aux[0];
            $linea_id=$aux[1];
            $i=$aux[2];
            
            $sql->Consultar("camaras", "*", "id=".$camara_id." and encendida=1", "id asc", false);
            if($sql->num==0){
                
                $tmp->Consultar("lineas", "*", "id=".$linea_id, "id asc", false);
                if($tmp->num>0){
                    $th->stop();
                    $threads[$camara_id."_".$linea_id."_".$i]=NULL;
                }
            }
        }
    }
    sleep(10);
    //exit;
}

