<?php
/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07-jul-2021, 13:03:01.
 */

$id=$argv[1];
$i=0;
while($i<$id){
    //file_put_contents("test.txt", $id." - ".$i."\n",FILE_APPEND);    
    $i++;
    sleep(1);
}




