/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 12/03/2020
 */

rtsp://admin:bakcAse4@172.16.51.223/cam/realmonitor?channel=1&subtype=0
rtsp://admin:bakcAse4@93.176.162.71:901/cam/realmonitor?channel=1&subtype=0
 

	
cam_lorenzo
172.16.51.223
	901 	554 	
	
cam_adrian
172.16.51.221
	902 	554 	
	
cam_fran
172.16.51.222
	903 	554 	
	
cam_laura
172.16.51.224
	904 	554 	
	
cam_recepcion
172.16.51.225
	905 	554 	
	
cam_archivo
172.16.51.226
	906 	554 	
	
cam_oscar
172.16.51.227
	907 	554 	
	
cam_escalera
172.16.51.228
	908 	554 	
	
cam_pepe
172.16.51.229
	909 	554 	
	
cam_juntas
172.16.51.231
	910 	554 	
	
cam_pasillo
172.16.51.232
	911 	554 	
	
cam_puerta
172.16.51.233
	912 	554

172.16.51.221 adrian
172.16.51.222 fran
172.16.51.223 lorenzo
172.16.51.224 laura
172.16.51.225 recepcion
172.16.51.226 archivo
172.16.51.227 oscar
172.16.51.228 escalera
172.16.51.229 pepe
172.16.51.231 sala juntas
172.16.51.232 pasillo
172.16.51.233 puerta acceso

insert into locales (id,nombre,url_logo,aforo_max,aforo_actual,usuario,passw,directorio) 
values (1,'Oficina','https://ichef.bbci.co.uk/news/976/cpsprodpb/3066/production/_111609321_1-1.jpg',100,0,'ofi','admin','oficina');

insert into locales (id,nombre,url_logo,aforo_max,aforo_actual,usuario,passw,directorio) 
values (2,'Luna Azul','https://www.pikpng.com/pngl/m/429-4298683_media-luna-azul-png-imagenes-de-media-luna.png',100,0,'lunaazul','admin','lunaazul');

insert into locales (id,nombre,url_logo,aforo_max,aforo_actual,usuario,passw,directorio) 
values (3,'New Sala Maxx','https://www.newsalamaxx.com/wp-content/uploads/2019/03/Logo_Maxx-logo_240-fondo-oscuro.png',100,0,'maxx','admin','maxx');

insert into locales (id,nombre,url_logo,aforo_max,aforo_actual,usuario,passw,directorio) 
values (4,'Sala Kixx','https://salakixx.com/wp-content/uploads/2019/06/Logo_Sala_Kixx-mobile.png',100,0,'kixx','admin','kixx');



/*
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (1,1,'Camara fichador','1','rtsp://admin:bakcAse4@172.16.51.51:554/cam/realmonitor?channel=1&subtype=0',0,0,0,1,1,1,'6127533b4ad3a');
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (2,1,'Camara pasillo','2','rtsp://admin:bakcAse4@172.16.51.50:554/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,1,'6127537f6d995');
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (3,1,'Camara josue','3','rtsp://admin:bakcAse4@172.16.51.52:554/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,1,'6127513fc0071');
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (4,1,'Camara salida','4','rtsp://admin:bakcAse4@172.16.51.53:554/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,1,'612753bda0320');
*/

insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (1,1,'Camara fichador','1','rtsp://admin:bakcAse4@nouesmalt.duckdns.org:778/cam/realmonitor?channel=1&subtype=0',0,0,0,1,1,1,'6127533b4ad3a');
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (2,1,'Camara pasillo','2','rtsp://admin:bakcAse4@nouesmalt.duckdns.org:777/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,1,'6127537f6d995');
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (3,1,'Camara josue','3','rtsp://admin:bakcAse4@nouesmalt.duckdns.org:779/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,1,'6127513fc0071');
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (4,1,'Camara salida','4','rtsp://admin:bakcAse4@nouesmalt.duckdns.org:780/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,1,'612753bda0320');
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida,ipcamlive_alias) 
values (5,1,'Camara entrada','5','rtsp://admin:bakcAse4@nouesmalt.duckdns.org:781/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,1,'');


insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida) 
values (5,2,'Habitaciones','5','rtsp://admin:bakcAse4@lunaxilxes.duckdns.org:777/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,0);
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida) 
values (6,2,'Recepcion','6','rtsp://admin:bakcAse4@lunaxilxes.duckdns.org:778/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,0);
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida) 
values (7,2,'Arriba','7','rtsp://admin:bakcAse4@lunaxilxes.duckdns.org:779/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,0);
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida) 
values (8,2,'Pasillo','8','rtsp://admin:bakcAse4@lunaxilxes.duckdns.org:780/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,0);


insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida) 
values (5,2,'Habitaciones','5','rtsp://admin:bakcAse4@192.168.31.210:554/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,0);
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida) 
values (6,2,'Recepcion','6','rtsp://admin:bakcAse4@192.168.31.211:554/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,0);
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida) 
values (7,2,'Arriba','7','rtsp://admin:bakcAse4@192.168.31.212:554/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,0);
insert into camaras (id,local_id,descripcion,directorio,url_conexion,sistema,x,y,puerta,salida,encendida) 
values (8,2,'Pasillo','8','rtsp://admin:bakcAse4@192.168.31.213:554/cam/realmonitor?channel=1&subtype=0',0,0,0,0,0,0);



insert into lineas (camara_id,nombre,x1,y1,x2,y2) values (1,'prueba1',470,244,496,565);
insert into lineas (camara_id,nombre,x1,y1,x2,y2) values (1,'prueba2',76,120,296,328);
  



insert into personas (id,local_id,cod_interno) values (1,3,'1234567890');
insert into personas (id,local_id,cod_interno) values (2,3,'1235235623523');



insert into estancias (id,persona_id,camara_id,fecha_ini,fecha_fin) values (1,1,1,'2021-07-09 13:35:23.330041','2021-07-09 13:35:23.330041');
insert into estancias (id,persona_id,camara_id,fecha_ini,fecha_fin) values (2,2,1,'2021-07-09 13:36:23.330041','2021-07-09 13:36:23.330041');

insert into fotos (id,estancia_id) values (1,1);
insert into fotos (id,estancia_id) values (2,2);


select * from estancias where fecha_fin>='2021-07-09 13:35:22.330041' and fecha_fin<='2021-07-09 13:35:25.330041';

select * from estancias where fecha_fin>='2021-07-09 13:35:24.330041' and fecha_fin<='2021-07-09 13:35:25.330041';
