<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 08-jul-2021, 9:45:16.
 */
if (isset($_GET["debug"]) and $_GET["debug"] == 1) {
    error_reporting(E_ALL);
    ini_set('display_errors', '1');
} else {
    ini_set('display_errors', '0');
}


require_once("includes/rutas.php");
require_once("libs/mysql.class.php");

$sql=new Conectar();

if(isset($_GET["accion"]) and $_GET["accion"]!=""){
    $accion=$_GET["accion"];
}
if(isset($argv[1]) and $argv[1]!=""){
    $accion=$argv[1];
}

$return=[
    "cod" => "",
    "resp" => "",
    "valores" => "",
];
switch($accion){
    case "consultar":
        $tabla= urldecode($_GET["tabla"]);
        //echo "tabla:".$tabla."\n";
        $condicion=urldecode($_GET["condicion"]);
        //echo "condicion:".$condicion."\n";
        $orden=urldecode($_GET["orden"]);
        //echo "orden:".$orden."\n";
        
        $sql->Consultar ( $tabla, "*", $condicion, $orden, false);
        $return["cod"]="200";
        if($sql->num>0){
            $return["valores"]=[];
            do{
                $return["valores"][]=$sql->row;
            }while($sql->Siguiente());
        }else{
            $return["resp"]="No hay datos consultados";
        }
        echo json_encode($return);
        break;
    case "nombreunico":
        $codigos=[
            "a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",
            "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z",
            "0","1","2","3","4","5","6","7","8","9"
        ];
        $repetido=true;
        $nombre="";
        while($repetido){
            $nombre="";
            for($i=0;$i<25;$i++){
                $nombre.=$codigos[rand(0,count($codigos)-1)];
            }
            $sql->Consultar("personas", "cod_interno", "cod_interno='".$nombre."'", "id=asc", false);
            if($sql->num==0){
                $repetido=false;
            }
        }
        echo $nombre;
        break;
        
    case "fotos_identificadorunico":
        $codigos=[
            "a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",
            "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z",
            "0","1","2","3","4","5","6","7","8","9"
        ];
        $repetido=true;
        $nombre="";
        while($repetido){
            $nombre="";
            for($i=0;$i<25;$i++){
                $nombre.=$codigos[rand(0,count($codigos)-1)];
            }
            $sql->Consultar("fotos", "identificador_unico", "identificador_unico='".$nombre."'", "id=asc", false);
            if($sql->num==0){
                $repetido=false;
            }
        }
        echo $nombre;
        break;
        
     
        
    case "guarda_cruce":
        
        $linea_id=$argv[2];
        $fecha=$argv[3];        
        $direccion=$argv[4]; /*1: #de derexa de la panatalla hacia la izquierda;;;;2:#de izquierda de la panatalla hacia la derexa*/
        $x_cruce=$argv[5];
        $y_cruce=$argv[6];
        $identificador=$argv[7];        
        
        $campos=["linea_id","fecha","direccion","x_cruce","y_cruce","identificador"];
        $valores=[$linea_id,$fecha,$direccion,$x_cruce,$y_cruce,$identificador];
                
        $sql->Insertar("cruces_lineas", $campos, $valores, false);
        
        break;
        
    case "listado_lineas":
        $camara_id=$argv[2];
        $sql->Consultar("lineas", "id", "camara_id=".$camara_id, "id");
        if($sql->num>0){
            $i=0;
            do{
                echo $sql->row["id"];
                if($i!=($sql->num-1)){
                    echo ",";
                }
                $i++;
            }while($sql->Siguiente());
        }
        
        break;
        
    case "lineas_identificadorunico":
        $codigos=[
            "a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",
            "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z",
            "0","1","2","3","4","5","6","7","8","9"
        ];
        $repetido=true;
        $nombre="";
        while($repetido){
            $nombre="";
            for($i=0;$i<25;$i++){
                $nombre.=$codigos[rand(0,count($codigos)-1)];
            }
            $sql->Consultar("cruces_lineas", "identificador", "identificador='".$nombre."'", "id=asc", false);
            if($sql->num==0){
                $repetido=false;
            }
        }
        echo $nombre;
        break;    
        
        
    case "coordenadas_linea":
        $linea_id=$argv[2];
        $sql->Consultar("lineas", "*", "id=".$linea_id, "id");
        if($sql->num>0){
            echo $sql->row["x1"].",".$sql->row["y1"].",".$sql->row["x2"].",".$sql->row["y2"];
        }
        break;
        
        
    default:
        $return["cod"]="200";
        $return["resp"]="La accion solicitada no puede ser procesada";
        break;
}

$sql->Desconectar();
