<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07/08/2020
 * Nota UI: el zoom con transform:scale() se sustituyó por el lightbox global
 * verFoto()/rfLightbox() (definido en files/ui-common.js). Lógica de filtros intacta.
 */

?>

<script>
   function buscar(descargar=0){
       camara=document.getElementById("camara").value;
       desde=document.getElementById("desde").value;
       hasta=document.getElementById("hasta").value;
       persona_id=document.getElementById("persona_id").value;
       
       url='?page=accesos&buscar=1&camara='+encodeURIComponent(camara)+'&desde='+encodeURIComponent(desde)+'&hasta='+encodeURIComponent(hasta)+'&persona_id='+encodeURIComponent(persona_id);
       if(descargar>0){
           url+="&descargar="+descargar;
       }
       location.href=url;
       
   }

   /* Filtro rápido "Hoy": fechas de hoy estrictas, mantiene cámara/persona y lanza la consulta. */
   function buscarHoy(){
       var d=new Date();
       document.getElementById("desde").value=(d.getMonth()+1)+"/"+d.getDate()+" 12:00 AM";
       document.getElementById("hasta").value=(d.getMonth()+1)+"/"+d.getDate()+" 11:59 PM";
       buscar();
   }
   
   function sleep(ms) {
     return new Promise(resolve => setTimeout(resolve, ms));
   }
</script>
