<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07/08/2020
 * Nota UI: el zoom con transform:scale() se sustituyó por el lightbox global
 * verFoto()/rfLightbox() (definido en files/ui-common.js). Lógica de filtros intacta.
 */

?>

<script>
   function buscar(descargar=0){
       camara=document.getElementById("camara").value;
       desde=document.getElementById("desde").value;
       hasta=document.getElementById("hasta").value;
       persona_id=document.getElementById("persona_id").value;
       
       url='?page=accesos&buscar=1&camara='+camara+'&desde='+desde+'&hasta='+hasta+'&persona_id='+persona_id;
       if(descargar>0){
           url+="&descargar="+descargar;
       }
       location.href=url;
       
   } 
   
   function sleep(ms) {
     return new Promise(resolve => setTimeout(resolve, ms));
   }
</script>
