<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07/08/2020
 */

?>


<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Listado Movimientos 
    </h2>
    <div class="w-full sm:w-auto flex mt-4 sm:mt-0" >
        
    Cámara:&nbsp;
    <select class="input border mr-2" id="camara" >
        <option value="-" <?php if(!isset($_GET["camara"]) or $_GET["camara"]=="-"){ echo "selected='selected'"; } ?>>Todas</option>
        <?php
        $sql->Consultar('camaras','*',"local_id=".$_SESSION["local_id"]);
        if($sql->num>0){
            do {
                echo '<option ';
                if(isset($_GET["camara"]) and $_GET["camara"]==$sql->row["id"]){ echo "selected='selected'"; } 
                echo ' value="'.$sql->row["id"].'">'.$sql->row["descripcion"].'</option>';
            }while($sql->Siguiente());
        }
        ?>
    </select>    
    Persona:&nbsp;
    <select class="input border mr-2" id="persona_id" >
        <option value="-" <?php if(!isset($_GET["persona_id"]) or $_GET["persona_id"]=="-"){ echo "selected='selected'"; } ?>>Todos</option>
        <?php
        $sql->Consultar('personas','*',"id in (select id from estancias where camara_id in (select id from camaras where local_id=".$_SESSION["local_id"]."))","nombre asc, cod_interno asc");
        if($sql->num>0){
            do {
                echo '<option ';
                if(isset($_GET["persona_id"]) and $_GET["persona_id"]==$sql->row["id"]){ echo "selected='selected'"; } 
                echo ' value="'.$sql->row["id"].'">'.$sql->row["cod_interno"].' - '.$sql->row["nombre"].'</option>';
            }while($sql->Siguiente());
        }
        ?>
    </select>  
    <?php
    $horas=array("01"=>"13","02"=>"14","03"=>"15","04"=>"16","05"=>"17","06"=>"18","07"=>"19","08"=>"20","09"=>"21","10"=>"22","11"=>"23","12"=>"00");
            
    if(isset($_GET["desde"]) and $_GET["desde"]!=""){
        $desde=$_GET["desde"];
            
        $v_fecha= explode(" ", $desde);
        $v_fecha2= explode("/",$v_fecha[0] );
        $mes=$v_fecha2[0];
        $dia=$v_fecha2[1];
        
        $v_fecha2= explode(":",$v_fecha[1] );
        $hora=$v_fecha2[0];
        $minuto=$v_fecha2[1];
        
        $rango=$v_fecha[0];

        if($mes<10){ $mes="0".$mes; }    
        if($rango=="PM"){ $hora=$horas[$hora]; }
        
        $desde_sql=date("Y")."-".$mes."-".$dia." 00:00:00";
        
        
    }else{
        $desde=date("n/d")." 12:01 AM";
        $desde_sql=date("Y-m-d 00:00:00");
    }
    if(isset($_GET["hasta"]) and $_GET["hasta"]!=""){
        $hasta=$_GET["hasta"];
           
        $v_fecha= explode(" ", $hasta);
        $v_fecha2= explode("/",$v_fecha[0] );
        $mes=$v_fecha2[0];
        $dia=$v_fecha2[1];
        
        $v_fecha2= explode(":",$v_fecha[1] );
        $hora=$v_fecha2[0];
        $minuto=$v_fecha2[1];
        
        $rango=$v_fecha[0];

        if($mes<10){ $mes="0".$mes; }    
        if($rango=="PM"){ $hora=$horas[$hora]; }
        
        $hasta_sql=date("Y")."-".$mes."-".$dia." 23:59:59";
    }else{
        $hasta=date("n/d")." 12:59 PM";
        $hasta_sql=date("Y-m-d 23:59:59");
    }
    ?>
    Desde:&nbsp;<input data-timepicker="true" class="datepicker input border mx-auto" id="desde" value="<?= $desde; ?>" style="width:120px">
    Hasta:&nbsp;<input data-timepicker="true" class="datepicker input border mx-auto" id="hasta" value="<?= $hasta; ?>" style="width:120px">
    <button class="button text-white bg-theme-1 shadow-md mr-2" onclick="buscar()">Buscar</button>
        
        
  
        
    </div>
</div>
<!-- BEGIN: Datatable -->
<div class="intro-y datatable-wrapper box p-5 mt-5">
    
    
    <table class="table table-report table-report--bordered display datatable w-full dataTable no-footer dtr-inline" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info" style="width: 792px;">
        <thead>
            <tr role="row">
                <th class="border-b-2 text-center whitespace-no-wrap " tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 10%;" aria-label="ACTIONS: activate to sort column descending">HORA</th>
                <th class="border-b-2 text-center whitespace-no-wrap " tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 30%;" aria-label="">PERSONA</th>
                <th class="border-b-2 text-center whitespace-no-wrap " tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 20%;" aria-label="">CÁMARA</th>
                <th class="border-b-2 text-center whitespace-no-wrap " tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 20%;" aria-label="">FOTOS</th>
                
                <th class="border-b-2 text-center whitespace-no-wrap " tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 10%;" aria-label="">TIEMPO</th>
            <th class="border-b-2 text-center whitespace-no-wrap " tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 20%;" aria-label="">ACCIONES</th></tr>
        </thead>
        
        
        
        <tbody>
        <?php
           
        
        $where="fecha_ini>='".$desde_sql."' and fecha_ini<='".$hasta_sql."'";
        
        if($_GET["camara"]!="" and $_GET["camara"]!="-"){
            $where.=" and camara_id=".$_GET["camara"];
        }else{
            $where.=" and camara_id in (select id from camaras where local_id=".$_SESSION["local_id"].")";
        }
        if($_GET["persona_id"]!="" and $_GET["persona_id"]!="-"){
            $where.=" and persona_id=".$_GET["persona_id"];
        }
        
        $sql->Consultar("estancias", "*", $where, "fecha_ini desc",false);
            
        if($sql->num>0){
            $par="odd";
            do{
                
                //echo "->".$sql->row["fecha_fin"]."<-";
                
                
                $tiempo = strtotime($sql->row["fecha_fin"]) - strtotime($sql->row["fecha_ini"]);
                if($tiempo==0){
                   $tiempo=1; 
                }
                $tiempo.="&nbsp;s";
                
                $tmp->Consultar("personas","*","id=".$sql->row["persona_id"]);
                $cod_interno=$tmp->row["cod_interno"];
                $nombre=$tmp->row["nombre"];
                if($nombre==""){
                    $nombre=$cod_interno;
                }
                
                
                $tmp->Consultar("camaras","*","id=".$sql->row["camara_id"]);
                $descripcion_camara=$tmp->row["descripcion"];
                
                $tmp->Consultar("fotos","id","estancia_id=".$sql->row["id"],"id desc",false);
                $imagen1="";
                $imagen2="";
                if($tmp->num>0){
                    $primera=true;
                    do{
                        if($primera){
                            $primera=false;
                            $imagen1="./caras_procesadas/".$tmp->row["id"].".jpg";
                        }else{
                            $imagen2="./caras_procesadas/".$tmp->row["id"].".jpg";
                        }
                    }while($tmp->Siguiente());
                }
                /*
                if($imagen2=="" or $imagen2=="../images/tmps/_0.jpg"){
                   $imagen2=$imagen1; 
                }
                 */
                
        ?>
            
        <tr role="row" class="<?= $par; ?>">
                            
                <td class="border-b sorting_1" tabindex="0" align="center">
                    <div class="font-medium whitespace-no-wrap"><?= $sql->row["fecha_ini"]; ?></div>
                </td>
            
                <td class="border-b sorting_1" tabindex="0" align="center">
                    <div class="font-medium whitespace-no-wrap">
                    <?= $nombre; ?><br />
                    </div>
                </td>
                <td class="border-b sorting_1" tabindex="0" align="center">
                    <div class="font-medium whitespace-no-wrap"><?= $descripcion_camara; ?></div>
                </td>
            
            
                <td class="text-center border-b">
                    
                           
                    <div class="flex sm:justify-center">
                        <div class="intro-x w-10 h-10 image-fit">
                            
                            <img alt="" id="<?= $imagen1; ?>" onclick="scale(this,this.id,1)" class="rounded-full" src="<?= $imagen1 ?>" style="position:relative;left:-10px">
                            <img alt="" id="<?= $imagen2; ?>" onclick="scale(this,this.id,2)" class="rounded-full" src="<?= $imagen2 ?>" style="position:relative;left:30px;top:-40px">
                        </div>
                        
                    </div>
                </td>

                
                
                <td class="border-b sorting_1" tabindex="0" align="center">
                    <div class="font-medium whitespace-no-wrap"><?= $tiempo; ?></div>
                </td>
                
                
                

                <td class="border-b w-5">
                    <div class="flex sm:justify-center items-center">
                        <a class="flex items-center mr-3" href="#" onclick="buscar(<?= $sql->row["id"]; ?>)"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-square w-4 h-4 mr-1"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg> Descargar </a>
                      
                        
                    </div>
                </td>
        </tr>
        <?php    
            if($par=="odd"){
                $par="pair";
            }else{
               $par="odd";
            }
            }while($sql->Siguiente());
        }    
        ?>

            
            
        </tbody>
    </table>            </div>
<!-- END: Datatable -->

