<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 19/08/2020
 */

include "javascript.php";

switch($_GET["mode"]){
    case "listar":
        include "list.php";
        break;
    default:
        include "list.php";
        break;
    
}