<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07/08/2020
 */

switch($_GET["mode"]){
    case "editar":
        include "edit.php";
        break;
    case "listar":
        include "list.php";
        break;
    default:
        include "list.php";
        break;
    
}