<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 11/08/2020
 */


$extensiones=["jpg","jpeg","png","bmp"];


switch($_GET["accion"]){
    case "crear":
        /*
        if($_GET["puerta"]==1){
            $sql->Actualizar("camaras",["puerta"],[0],"id>0");
        }
        if($_GET["salida"]==1){
            $sql->Actualizar("camaras",["salida"],[0],"id>0");
        }
        */
        
        $url_conexion= str_replace("--jos--", "&", $_GET["url_conexion"]);
        
        
        $campos=["local_id","descripcion","url_conexion","sistema","puerta","salida","encendida","ipcamlive_alias"];
        
        $valores=[$_SESSION["local_id"],$_GET["nombre_nueva"],$url_conexion,$_GET["sistema"],$_GET["puerta"],$_GET["salida"],$_GET["encendida_nueva"],$_GET["ipcamlive_alias"]];
        $sql->Insertar("camaras",$campos,$valores,false);
        
        $cmds=[];
        
        echo "<br />Sistema:".$_GET["sistema"]."<-<br />";
        
        if($_GET["sistema"]==0){
            $cmds[]="mkdir ".URL_FTP_BASE."motor/videos/".$_SESSION["local_id"]."/".$sql->id;
            $cmds[]="chmod -R 777 ".URL_FTP_BASE."motor/videos/".$_SESSION["local_id"]."/".$sql->id;
            $cmds[]="mkdir ".URL_FTP_BASE."motor/videos_lineas/".$_SESSION["local_id"]."/".$sql->id;
            $cmds[]="chmod -R 777 ".URL_FTP_BASE."motor/videos_lineas/".$_SESSION["local_id"]."/".$sql->id;
        }
        $cmds[]="mkdir ".RUTA_PROYECTO."motor/caras/".$_SESSION["local_id"]."/".$sql->id;
        $cmds[]="mkdir ".RUTA_PROYECTO."motor/caras/sinclasificar/".$_SESSION["local_id"]."/".$sql->id;
        
        $cmds[]="chmod -R 777 ".RUTA_PROYECTO."motor/caras/".$_SESSION["local_id"]."/".$sql->id;
        $cmds[]="chmod -R 777 ".RUTA_PROYECTO."motor/caras/sinclasificar/".$_SESSION["local_id"]."/".$sql->id;
        
        
        echo "<br />-----EJECUTAR---<br /><br />";
        for($i=0;$i<count($cmds);$i++){
            echo $cmds[$i]."<br />";
            exec($cmds[$i]);
            sleep(1);
        }
        echo "<br />----------------<br />";
        
        
        break;
    case "guardar":
        /*        
        if($_GET["puerta"]==1){
            $sql->Actualizar("camaras",["puerta"],[0],"id>0");
        }
        */
        
        $url_conexion= str_replace("--jos--", "&", $_GET["url_conexion"]);
        $url_desdeserver= str_replace("--jos--", "&", $_GET["url_desdeserver"]);
        
        $campos=["local_id","descripcion","url_conexion","sistema","puerta","salida","encendida","x","y","ipcamlive_alias","url_desdeserver","sensibilidad_movimiento"];
        $valores=[$_SESSION["local_id"],$_GET["nombre"],$url_conexion,$_GET["sistema"],$_GET["puerta"],$_GET["salida"],$_GET["encendida"],$_GET["x"],$_GET["y"],$_GET["ipcamlive_alias"],$url_desdeserver,$_GET["sensibilidad_movimiento"]];
        
        $sql->Actualizar("camaras",$campos,$valores,"id=".$_GET["camara"],false);
        
        
        break;
    case "plano":
        
        for($i=0;$i<count($extensiones);$i++){
            if(file_exists("pages/config/planos/plano_".$_SESSION["local_id"].".".$extensiones[$i])){
                unlink("pages/config/planos/plano_".$_SESSION["local_id"].".".$extensiones[$i]);
            }
        }        
        
        $fileName = $_FILES['plano']['name'];
        $fileNameCmps = explode(".", $fileName);
        $fileExtension = strtolower(end($fileNameCmps));

        //echo "->".$_FILES['plano']['tmp_name']."<-<br />";
        //echo "->"."../images/plano_".$_SESSION["local_id"].".".$fileExtension."<-<br />";
        
        if(move_uploaded_file($_FILES['plano']['tmp_name'], "pages/config/planos/plano_".$_SESSION["local_id"].".".$fileExtension))
        {
          echo 'File is successfully uploaded.';
        }
        else
        {
          echo 'There was some error moving the file to upload directory. Please make sure the upload directory is writable by web server.';
        }
        break;
        
    case "eliminar_nodos":
        
        $sql->Eliminar("nodos","camara_id1=".$_GET["camara1"]." and camara_id2=".$_GET["camara2"]);
        
        break;
    
    case "guardar_lineas":
        
        $lasx=$_GET["lasx"];
        $lasy=$_GET["lasy"];
        $losnombres=$_GET["losnombres"];
        $losids=$_GET["losids"];
        $camara_id=$_GET["camara_id"];
        
        $v_lasx= explode(",,,", $lasx);
        $v_lasy=explode(",,,", $lasy);
        $v_losnombres=explode(",,,", $losnombres);
        $v_losids=explode(",,,", $losids);

        for($i=0;$i<count($v_losids);$i++){
            if($v_losids[$i]==0){
                
                $x1=$v_lasx[$i*2];
                $y1=$v_lasy[$i*2];
                $x2=$v_lasx[($i*2)+1];
                $y2=$v_lasy[($i*2)+1];
                        
                if(strpos($x1, ".")){ $aux= explode(".", $x1); $x1=$aux[0]; }
                if(strpos($y1, ".")){ $aux= explode(".", $y1); $y1=$aux[0]; }
                if(strpos($x2, ".")){ $aux= explode(".", $x2); $x2=$aux[0]; }
                if(strpos($y2, ".")){ $aux= explode(".", $y2); $y2=$aux[0]; }
                        
                $sql->Insertar("lineas",["camara_id","nombre","x1","y1","x2","y2"],[$camara_id,$v_losnombres[$i],$x1,$y1,$x2,$y2]);
              
                exec("mkdir ".URL_FTP_BASE."motor/videos_lineas/".$_SESSION["local_id"]."/".$camara_id."/".$sql->id);
                exec("chmod -R 777 ".URL_FTP_BASE."motor/videos_lineas/".$_SESSION["local_id"]."/".$camara_id."/".$sql->id);
            
                
                $cmd="mkdir ".RUTA_PROYECTO."motor/fotos_lineas/".$sql->id;
                //echo $cmd."<br />";
                exec($cmd);
                $cmd="chmod -R 777 ".RUTA_PROYECTO."motor/fotos_lineas/".$sql->id;
                //echo $cmd."<br />";
                exec($cmd);
                //exit;
                
            }else{
                $sql->Actualizar("lineas",["nombre"],[$v_losnombres[$i]],"id=".$v_losids[$i]);
            }
        }


        
        break;
    
    case "eliminar_linea":
        $id_linea=$_GET["id_linea"];
        $sql->Actualizar("lineas",["eliminada"],[1],"id=".$id_linea);    
        break;
        
    case "editar_lineas":
        
       
        $lasx=$_GET["lasx"];
        $lasy=$_GET["lasy"];
        $losnombres=$_GET["losnombres"];
        $losids=$_GET["losids"];
        $linea_id=$_GET["linea_id"];
        
        $v_lasx= explode(",,,", $lasx);
        $v_lasy=explode(",,,", $lasy);
        $v_losnombres=explode(",,,", $losnombres);
        $v_losids=explode(",,,", $losids);

        for($i=0;$i<count($v_losids);$i++){
               
            $x1=$v_lasx[$i*2];
            $y1=$v_lasy[$i*2];
            $x2=$v_lasx[($i*2)+1];
            $y2=$v_lasy[($i*2)+1];

            if(strpos($x1, ".")){ $aux= explode(".", $x1); $x1=$aux[0]; }
            if(strpos($y1, ".")){ $aux= explode(".", $y1); $y1=$aux[0]; }
            if(strpos($x2, ".")){ $aux= explode(".", $x2); $x2=$aux[0]; }
            if(strpos($y2, ".")){ $aux= explode(".", $y2); $y2=$aux[0]; }

            $sql->Actualizar("lineas",["x1","y1","x2","y2"],[$x1,$y1,$x2,$y2],"id=".$linea_id);
              
        }

        
        
        
        break;
}   