<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07/08/2020
 */

include "acciones.php";
include "javascript.php";

switch($_GET["mode"]){
    case "editar":
        include "edit.php";
        break;
    default:
        include "edit.php";
        break;
    
}