<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 11/08/2020
 *
 * REFACTOR 2026-08-19 (La Forja):
 *  - El Yunque (tab=plano) tiene su PROPIO lienzo (canvasID): plano grande,
 *    cámaras arrastrables desde la barra lateral, líneas colocables y grafo
 *    de senderos (recto/ortogonal/curvo).
 *  - El trazador de líneas (tab=lineas) usa un modal con canvasLineas sobre el
 *    snapshot de la cámara (miniaturas en vez de desplegable).
 *  - Se elimina la lógica de nodos cámara→cámara y el lienzo persistente.
 */

require_once __DIR__ . "/../../../libs/db.php";
require_once __DIR__ . "/../../../libs/planos.php";
require_once __DIR__ . "/../../../libs/lineas_plano.php";
require_once __DIR__ . "/../../../libs/plano_estado.php";
require_once __DIR__ . "/../../../libs/etiquetas.php";

$local_id_js = (int)($_SESSION["local_id"] ?? 0);
$plano_activo_url = plano_url($local_id_js);
$plano_dibujo_url = plano_dibujo_url($local_id_js);

/* Normalizador latin1→UTF-8 para json_encode (la BD es latin1). */
$rf_utf8 = function ($v) {
    $v = (string)$v;
    return ($v !== "" && function_exists("mb_check_encoding") && !mb_check_encoding($v, "UTF-8"))
        ? mb_convert_encoding($v, "UTF-8", "latin1")
        : $v;
};

/* Cámaras enriquecidas con estado de completado. */
$cams_estado = camaras_con_estado($local_id_js);
$cams_json = [];
foreach ($cams_estado as $c) {
    $cams_json[] = [
        "id"              => (int)$c["id"],
        "x"               => (int)$c["x"],
        "y"               => (int)$c["y"],
        "desc"            => camara_label($rf_utf8($c["descripcion"])),
        "colocada"        => (int)($c["colocada"] ?? 0),
        "num_lineas"      => (int)$c["num_lineas"],
        "num_lineas_plano"=> (int)$c["num_lineas_plano"],
        "completa"        => (bool)$c["completa"],
        "puerta"          => (int)$c["puerta"],
        "salida"          => (int)$c["salida"],
    ];
}

/* Líneas de cámara (triples sobre foto) del local. */
$lineas_json = DB::select(
    "SELECT l.id, l.camara_id, l.nombre, l.x1, l.y1, l.x2, l.y2
     FROM lineas l
     JOIN camaras c ON c.id = l.camara_id
     WHERE c.local_id = ? AND l.eliminada = 0
     ORDER BY l.id ASC",
    [$local_id_js]
);
$lineas_json = array_map(function ($l) use ($rf_utf8) {
    return [
        "id"        => (int)$l["id"],
        "camara_id" => (int)$l["camara_id"],
        "nombre"    => $rf_utf8($l["nombre"]),
        "x1"        => (int)$l["x1"], "y1" => (int)$l["y1"],
        "x2"        => (int)$l["x2"], "y2" => (int)$l["y2"],
    ];
}, $lineas_json);

/* Líneas del plano (con su vínculo a línea de cámara). */
$lineas_plano_json = lineas_plano_del_local($local_id_js);
$lineas_plano_json = array_map(function ($lp) use ($rf_utf8) {
    return [
        "id"        => (int)$lp["id"],
        "camara_id" => (int)$lp["camara_id"],
        "linea_id"  => (int)($lp["linea_id"] ?? 0),
        "nombre"    => $rf_utf8($lp["nombre"]),
        "x1"        => (int)$lp["x1"], "y1" => (int)$lp["y1"],
        "x2"        => (int)$lp["x2"], "y2" => (int)$lp["y2"],
    ];
}, $lineas_plano_json);

/* Nodos y senderos del grafo. */
$nodos_json = nodos_del_local($local_id_js);
$nodos_json = array_map(function ($n) use ($rf_utf8) {
    $n["nombre"] = $rf_utf8($n["nombre"]);
    return $n;
}, $nodos_json);

$senderos_json = senderos_del_local($local_id_js);
$senderos_json = array_map(function ($s) use ($rf_utf8) {
    $s["nombre"] = $rf_utf8($s["nombre"]);
    return $s;
}, $senderos_json);

$plano_completo = plano_completo($local_id_js);
?>
<script>

var PLANO_ACTIVO_URL = <?= json_encode($plano_activo_url ?? ""); ?>;
var PLANO_DIBUJO_URL = <?= json_encode($plano_dibujo_url ?? ""); ?>;
var LOCAL_ID = <?= $local_id_js; ?>;
var FORGE_TAB = <?= json_encode($tab); ?>;
var FORGE_SUB = <?= json_encode($sub); ?>;
var FORGE_CAMS = <?= json_encode($cams_json, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>;
var FORGE_LINEAS = <?= json_encode($lineas_json, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>;
var FORGE_LINEAS_PLANO = <?= json_encode($lineas_plano_json, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>;
var FORGE_NODOS = <?= json_encode($nodos_json, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>;
var FORGE_SENDEROS = <?= json_encode($senderos_json, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>;
var FORGE_PLANO_COMPLETO = <?= $plano_completo ? "true" : "false"; ?>;

var COLOR_CAM_OK = "#2e9e44";
var COLOR_CAM_KO = "#e0563c";
var COLOR_LINEA_PLANO = "#ffed00";
var COLOR_NODO_CAMARA = "#d22829";
var COLOR_NODO_LINEA = "#2596be";
var COLOR_SENDERO = "#9a6bff";

/* =========================================================================
 * Utilidades
 * ========================================================================= */
function ForgeCoord(canvas, e) {
    var r = canvas.getBoundingClientRect();
    return {
        x: (e.clientX - r.left) * canvas.width / r.width,
        y: (e.clientY - r.top) * canvas.height / r.height
    };
}
function ForgeCamById(id) {
    for (var i = 0; i < FORGE_CAMS.length; i++) if (FORGE_CAMS[i].id === id) return FORGE_CAMS[i];
    return null;
}
function ForgeLineaPlanoById(id) {
    for (var i = 0; i < FORGE_LINEAS_PLANO.length; i++) if (FORGE_LINEAS_PLANO[i].id === id) return FORGE_LINEAS_PLANO[i];
    return null;
}
function ForgeNodoByRef(tipo, ref_id) {
    for (var i = 0; i < FORGE_NODOS.length; i++) {
        var n = FORGE_NODOS[i];
        if (n.tipo === tipo && n.ref_id === ref_id) return n;
    }
    return null;
}
function ForgeSenderoById(id) {
    for (var i = 0; i < FORGE_SENDEROS.length; i++) if (FORGE_SENDEROS[i].id === id) return FORGE_SENDEROS[i];
    return null;
}
function ForgeEsc(s) {
    return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}
function ForgeLineasDeCamara(camId) {
    var out = [];
    for (var i = 0; i < FORGE_LINEAS.length; i++) if (FORGE_LINEAS[i].camara_id === camId) out.push(FORGE_LINEAS[i]);
    return out;
}
function ForgeLineaPlanoDeLinea(lineaId) {
    for (var i = 0; i < FORGE_LINEAS_PLANO.length; i++) if (FORGE_LINEAS_PLANO[i].linea_id === lineaId) return FORGE_LINEAS_PLANO[i];
    return null;
}

/* =========================================================================
 * El Yunque — lienzo de disposición del plano
 * ========================================================================= */
var Yunque = {
    canvas: null, ctx: null, planoImg: null, baseCache: null,
    camDrag: null,            // cámara colocada en arrastre: {index}
    camSeleccionada: null,    // id de cámara seleccionada (panel de líneas)
    lineDrag: null,           // arrastre de extremo de línea del plano: {i, ext}
    nodoSel1: null,           // {tipo, ref_id} primer nodo (senderos)
    senderoDrag: null,        // arrastre de punto intermedio de sendero: {sid, pi}
    modoSenderos: false,
    estilo: "recto",
};

/* Dibuja el plano base + cámaras + líneas + nodos + senderos en cache. */
function YunquePintarBase(bctx) {
    bctx.clearRect(0, 0, Yunque.canvas.width, Yunque.canvas.height);

    // cámaras colocadas (2 estados: completa vs no completada)
    for (var i = 0; i < FORGE_CAMS.length; i++) {
        var c = FORGE_CAMS[i];
        if (!c.colocada) continue;
        var col = c.completa ? COLOR_CAM_OK : COLOR_CAM_KO;
        bctx.fillStyle = col;
        bctx.fillRect(c.x, c.y, 12, 12);
        bctx.strokeStyle = c.completa ? "#0e5c1f" : "#7a1f0e";
        bctx.lineWidth = 2;
        bctx.strokeRect(c.x - 3, c.y - 3, 18, 18);
        if (!c.completa) {
            bctx.save();
            bctx.strokeStyle = "#ffffff";
            bctx.setLineDash([3, 3]);
            bctx.strokeRect(c.x - 5, c.y - 5, 22, 22);
            bctx.restore();
        }
        bctx.font = "11px Arial";
        bctx.fillText(c.desc, c.x, c.y - 8);
    }

    // líneas del plano (rallitas + nombre + rayo de enfoque)
    for (var li = 0; li < FORGE_LINEAS_PLANO.length; li++) {
        var L = FORGE_LINEAS_PLANO[li];
        bctx.strokeStyle = COLOR_LINEA_PLANO;
        bctx.lineWidth = 2;
        bctx.beginPath();
        bctx.moveTo(L.x1, L.y1);
        bctx.lineTo(L.x2, L.y2);
        bctx.stroke();
        bctx.fillStyle = COLOR_LINEA_PLANO;
        bctx.fillRect(L.x1 - 3, L.y1 - 3, 6, 6);
        bctx.fillRect(L.x2 - 3, L.y2 - 3, 6, 6);
        bctx.fillText(L.nombre, L.x1, L.y1 - 6);
        var cam = ForgeCamById(L.camara_id);
        if (cam && cam.colocada) {
            bctx.save();
            bctx.strokeStyle = "#ff9500";
            bctx.lineWidth = 1;
            bctx.setLineDash([4, 4]);
            bctx.beginPath();
            bctx.moveTo(cam.x + 6, cam.y + 6);
            bctx.lineTo((L.x1 + L.x2) / 2, (L.y1 + L.y2) / 2);
            bctx.stroke();
            bctx.restore();
        }
    }

    // nodos (cámara = rojo cuadrado, línea = azul círculo en punto medio)
    for (var ni = 0; ni < FORGE_NODOS.length; ni++) {
        var n = FORGE_NODOS[ni];
        if (n.tipo === "camara") {
            bctx.fillStyle = COLOR_NODO_CAMARA;
            bctx.fillRect(n.x - 4, n.y - 4, 8, 8);
        } else {
            bctx.fillStyle = COLOR_NODO_LINEA;
            bctx.beginPath();
            bctx.arc(n.x, n.y, 5, 0, Math.PI * 2);
            bctx.fill();
        }
        bctx.fillStyle = "#bbbbbb";
        bctx.font = "10px Arial";
        bctx.fillText(n.nombre, n.x + 7, n.y + 3);
    }

    // senderos
    for (var si = 0; si < FORGE_SENDEROS.length; si++) {
        YunquePintarSendero(bctx, FORGE_SENDEROS[si]);
    }
}

function YunquePintarSendero(bctx, s) {
    var a = ForgeNodoByRef(s.origen_tipo, s.origen_id);
    var b = ForgeNodoByRef(s.destino_tipo, s.destino_id);
    if (!a || !b) return;
    var pts = [{ x: a.x, y: a.y }];
    for (var i = 0; i < s.puntos.length; i++) pts.push({ x: s.puntos[i][0], y: s.puntos[i][1] });
    pts.push({ x: b.x, y: b.y });

    bctx.save();
    bctx.strokeStyle = COLOR_SENDERO;
    bctx.lineWidth = 3;
    bctx.beginPath();
    bctx.moveTo(pts[0].x, pts[0].y);
    if (s.estilo === "curvo" && pts.length > 2) {
        for (var j = 1; j < pts.length - 1; j++) {
            var mx = (pts[j].x + pts[j + 1].x) / 2, my = (pts[j].y + pts[j + 1].y) / 2;
            bctx.quadraticCurveTo(pts[j].x, pts[j].y, mx, my);
        }
        bctx.lineTo(pts[pts.length - 1].x, pts[pts.length - 1].y);
    } else {
        for (var k = 1; k < pts.length; k++) bctx.lineTo(pts[k].x, pts[k].y);
    }
    bctx.stroke();
    bctx.restore();

    // asas de los puntos intermedios
    bctx.fillStyle = COLOR_SENDERO;
    for (var h = 0; h < s.puntos.length; h++) {
        bctx.fillRect(s.puntos[h][0] - 4, s.puntos[h][1] - 4, 8, 8);
    }
}

function YunqueDibujar() {
    if (!Yunque.canvas) return;
    var ctx = Yunque.ctx, W = Yunque.canvas.width, H = Yunque.canvas.height;
    if (!Yunque.baseCache) {
        Yunque.baseCache = document.createElement("canvas");
        Yunque.baseCache.width = W; Yunque.baseCache.height = H;
    }
    var bctx = Yunque.baseCache.getContext("2d");
    bctx.clearRect(0, 0, W, H);
    if (Yunque.planoImg && Yunque.planoImg.complete && Yunque.planoImg.naturalWidth > 0) {
        bctx.drawImage(Yunque.planoImg, 0, 0, W, H);
    }
    YunquePintarBase(bctx);
    YunqueRender();
}

function YunqueRender() {
    var ctx = Yunque.ctx;
    ctx.clearRect(0, 0, Yunque.canvas.width, Yunque.canvas.height);
    if (Yunque.baseCache) ctx.drawImage(Yunque.baseCache, 0, 0);

    // resaltado de nodo seleccionado (senderos)
    if (Yunque.nodoSel1) {
        var n = ForgeNodoByRef(Yunque.nodoSel1.tipo, Yunque.nodoSel1.ref_id);
        if (n) {
            ctx.save();
            ctx.strokeStyle = "#ffffff";
            ctx.lineWidth = 3;
            if (n.tipo === "camara") ctx.strokeRect(n.x - 8, n.y - 8, 16, 16);
            else { ctx.beginPath(); ctx.arc(n.x, n.y, 10, 0, Math.PI * 2); ctx.stroke(); }
            ctx.restore();
        }
    }
    // resaltado de cámara seleccionada (panel de líneas)
    if (Yunque.camSeleccionada) {
        var c = ForgeCamById(Yunque.camSeleccionada);
        if (c && c.colocada) {
            ctx.save();
            ctx.strokeStyle = "#ffffff";
            ctx.lineWidth = 3;
            ctx.strokeRect(c.x - 6, c.y - 6, 24, 24);
            ctx.restore();
        }
    }
}

/* Barra lateral: cámaras fuera del plano (colocada=0), arrastrables. */
function YunqueRenderSidebar() {
    var cont = document.getElementById("yunqueCamsFuera");
    if (!cont) return;
    var html = [];
    for (var i = 0; i < FORGE_CAMS.length; i++) {
        var c = FORGE_CAMS[i];
        if (c.colocada) continue;
        html.push('<div class="yunque-cam-fuera" draggable="true" data-cam-id="' + c.id + '">'
            + '<img src="fotos_camara/' + c.id + '.png" onerror="this.onerror=null;this.style.opacity=0.2" alt="">'
            + '<span>' + ForgeEsc(c.desc) + '</span></div>');
    }
    cont.innerHTML = html.length ? html.join("") : '<p class="text-xs text-gray-500 dark:text-gray-600">Todas las cámaras están en el plano.</p>';
}

function YunqueRenderEstado() {
    var el = document.getElementById("yunqueEstado");
    if (!el) return;
    var pendCams = 0, pendLineas = 0;
    for (var i = 0; i < FORGE_CAMS.length; i++) {
        if (!FORGE_CAMS[i].colocada) pendCams++;
        if (!FORGE_CAMS[i].completa) pendLineas++;
    }
    if (FORGE_PLANO_COMPLETO) {
        el.className = "yunque-estado yunque-estado--ok";
        el.innerHTML = "✔ Plano completado";
    } else {
        el.className = "yunque-estado yunque-estado--pend";
        el.innerHTML = "Pendiente · " + pendCams + " cámara(s) sin colocar · " + pendLineas + " cámara(s) con líneas pendientes";
    }
}

/* Panel de líneas de la cámara seleccionada. */
function YunqueRenderLineasPanel() {
    var cont = document.getElementById("yunqueLineasPanel");
    if (!cont) return;
    if (!Yunque.camSeleccionada) { cont.innerHTML = ""; return; }
    var c = ForgeCamById(Yunque.camSeleccionada);
    if (!c) { cont.innerHTML = ""; return; }
    var lineas = ForgeLineasDeCamara(c.id);
    var titulo = document.getElementById("yunqueLineasTitulo");
    if (titulo) titulo.textContent = "Líneas de «" + c.desc + "»";
    if (!lineas.length) {
        cont.innerHTML = '<p class="text-xs text-gray-500 dark:text-gray-600">Esta cámara no tiene líneas configuradas (es un nodo).</p>';
        return;
    }
    var html = [];
    for (var i = 0; i < lineas.length; i++) {
        var L = lineas[i];
        var lp = ForgeLineaPlanoDeLinea(L.id);
        if (lp) {
            html.push('<div class="yunque-linea yunque-linea--ok">'
                + '<span class="yunque-linea__nombre">' + ForgeEsc(L.nombre) + '</span>'
                + '<span class="yunque-linea__estado">✔ en plano</span></div>');
        } else {
            html.push('<div class="yunque-linea yunque-linea--pend" draggable="true" data-linea-id="' + L.id + '">'
                + '<span class="yunque-linea__nombre">' + ForgeEsc(L.nombre) + '</span>'
                + '<span class="yunque-linea__estado">arrastra al plano</span></div>');
        }
    }
    cont.innerHTML = html.join("");
}

/* Arrastre de cámara colocada sobre el lienzo. */
function YunqueCamHitTest(p) {
    var R = 14;
    for (var i = 0; i < FORGE_CAMS.length; i++) {
        var c = FORGE_CAMS[i];
        if (!c.colocada) continue;
        var dx = (c.x + 6) - p.x, dy = (c.y + 6) - p.y;
        if (Math.sqrt(dx * dx + dy * dy) <= R) return i;
    }
    return -1;
}
function YunqueClampCam(c) {
    c.x = Math.max(0, Math.min(Yunque.canvas.width - 12, c.x));
    c.y = Math.max(0, Math.min(Yunque.canvas.height - 12, c.y));
}
function YunqueGuardarCamPos(id, x, y) {
    fetch("pages/config/acciones_ajax.php?a=8", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: id, x: x, y: y })
    }).then(function (r) { return r.text(); }).then(function (t) {
        if (t.indexOf("error") !== -1 && typeof rfToast === "function") rfToast("No se pudo mover la cámara.", "err");
    }).catch(function () {});
}

/* Suelta de una cámara arrastrada desde la barra lateral (HTML5 DnD). */
function YunqueColocarCamara(camId, p) {
    var c = ForgeCamById(camId);
    if (!c) return;
    var x = Math.max(0, Math.min(Yunque.canvas.width - 12, Math.round(p.x - 6)));
    var y = Math.max(0, Math.min(Yunque.canvas.height - 12, Math.round(p.y - 6)));
    fetch("pages/config/acciones_ajax.php?a=8", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: camId, x: x, y: y })
    }).then(function (r) { return r.text(); }).then(function (t) {
        if (t.indexOf("error") !== -1) { if (typeof rfToast === "function") rfToast("No se pudo colocar la cámara.", "err"); return; }
        c.x = x; c.y = y; c.colocada = 1;
        FORGE_PLANO_COMPLETO = false;
        YunqueDibujar(); YunqueRenderSidebar(); YunqueRenderEstado();
        if (typeof rfToast === "function") rfToast("Cámara colocada en el plano.", "ok");
    }).catch(function () {});
}

/* Coloca una línea de cámara en el plano (arrastrada desde el panel). */
function YunqueColocarLinea(lineaId, p) {
    var linea = null;
    for (var i = 0; i < FORGE_LINEAS.length; i++) if (FORGE_LINEAS[i].id === lineaId) { linea = FORGE_LINEAS[i]; break; }
    if (!linea) return;
    var x = Math.round(p.x), y = Math.round(p.y);
    var body = {
        camara_id: linea.camara_id, nombre: linea.nombre,
        x1: Math.max(0, x - 30), y1: y, x2: Math.min(Yunque.canvas.width - 1, x + 30), y2: y,
        linea_id: lineaId
    };
    fetch("pages/config/acciones_ajax.php?a=11", {
        method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body)
    }).then(function (r) { return r.text(); }).then(function (t) {
        if (t.indexOf("ok:") !== 0) { if (typeof rfToast === "function") rfToast("No se pudo colocar la línea.", "err"); return; }
        var id = parseInt(t.slice(3), 10) || 0;
        FORGE_LINEAS_PLANO.push({ id: id, camara_id: linea.camara_id, linea_id: lineaId, nombre: linea.nombre, x1: body.x1, y1: body.y1, x2: body.x2, y2: body.y2 });
        // actualizar completado de la cámara
        var cam = ForgeCamById(linea.camara_id);
        if (cam) { cam.num_lineas_plano++; cam.completa = (cam.num_lineas === cam.num_lineas_plano); }
        FORGE_PLANO_COMPLETO = false;
        YunqueRenderNodos();
        YunqueDibujar(); YunqueRenderLineasPanel(); YunqueRenderEstado();
        if (typeof rfToast === "function") rfToast("Línea colocada. Arrastra sus extremos para ajustarla.", "ok");
    }).catch(function () {});
}

/* Recalcula FORGE_NODOS desde cámaras y líneas del plano (sin recargar). */
function YunqueRenderNodos() {
    var out = [];
    for (var i = 0; i < FORGE_CAMS.length; i++) {
        var c = FORGE_CAMS[i];
        if (c.colocada && c.num_lineas === 0) {
            out.push({ tipo: "camara", ref_id: c.id, x: c.x, y: c.y, nombre: c.desc });
        }
    }
    for (var j = 0; j < FORGE_LINEAS_PLANO.length; j++) {
        var L = FORGE_LINEAS_PLANO[j];
        out.push({ tipo: "linea_plano", ref_id: L.id, x: Math.round((L.x1 + L.x2) / 2), y: Math.round((L.y1 + L.y2) / 2), nombre: L.nombre });
    }
    FORGE_NODOS = out;
}

/* Arrastre de extremos de línea del plano. */
function YunqueLineaHitTest(p) {
    var R = 12;
    for (var i = 0; i < FORGE_LINEAS_PLANO.length; i++) {
        var L = FORGE_LINEAS_PLANO[i];
        if (Math.abs(L.x1 - p.x) <= R && Math.abs(L.y1 - p.y) <= R) return { i: i, ext: 1 };
        if (Math.abs(L.x2 - p.x) <= R && Math.abs(L.y2 - p.y) <= R) return { i: i, ext: 2 };
    }
    return null;
}
function YunqueLineaClamp(L, ext) {
    var mx = Yunque.canvas.width - 1, my = Yunque.canvas.height - 1;
    if (ext === 1) { L.x1 = Math.max(0, Math.min(mx, L.x1)); L.y1 = Math.max(0, Math.min(my, L.y1)); }
    else { L.x2 = Math.max(0, Math.min(mx, L.x2)); L.y2 = Math.max(0, Math.min(my, L.y2)); }
}
function YunqueLineaGuardar(id, x1, y1, x2, y2) {
    fetch("pages/config/acciones_ajax.php?a=12", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: id, x1: x1, y1: y1, x2: x2, y2: y2 })
    }).then(function (r) { return r.text(); }).then(function (t) {
        if (t.indexOf("error") !== -1 && typeof rfToast === "function") rfToast("No se pudo mover la línea.", "err");
    }).catch(function () {});
}

/* Senderos: selección de nodos. */
function YunqueNodoHitTest(p) {
    var R = 14;
    for (var i = 0; i < FORGE_NODOS.length; i++) {
        var n = FORGE_NODOS[i];
        if (Math.abs(n.x - p.x) <= R && Math.abs(n.y - p.y) <= R) return n;
    }
    return null;
}
function YunqueCrearSendero(nodoA, nodoB) {
    var estilo = Yunque.estilo;
    var puntos = [];
    if (estilo === "ortogonal") {
        puntos.push([nodoA.x, nodoB.y]);
    } else if (estilo === "curvo") {
        var mx = Math.round((nodoA.x + nodoB.x) / 2), my = Math.round((nodoA.y + nodoB.y) / 2);
        var dx = nodoB.x - nodoA.x, dy = nodoB.y - nodoA.y;
        puntos.push([mx + Math.round(-dy * 0.2), my + Math.round(dx * 0.2)]);
    }
    fetch("pages/config/acciones_ajax.php?a=16", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            origen_tipo: nodoA.tipo, origen_id: nodoA.ref_id,
            destino_tipo: nodoB.tipo, destino_id: nodoB.ref_id,
            estilo: estilo, puntos: puntos
        })
    }).then(function (r) { return r.json(); }).then(function (d) {
        if (!d || !d.ok) { if (typeof rfToast === "function") rfToast("No se pudo guardar el sendero.", "err"); return; }
        FORGE_SENDEROS.push({ id: d.id, origen_tipo: nodoA.tipo, origen_id: nodoA.ref_id, destino_tipo: nodoB.tipo, destino_id: nodoB.ref_id, estilo: estilo, nombre: "", puntos: puntos });
        Yunque.nodoSel1 = null;
        YunqueDibujar();
        if (typeof rfToast === "function") rfToast("Sendero creado.", "ok");
    }).catch(function () {});
}
function YunqueGuardarSendero(s) {
    fetch("pages/config/acciones_ajax.php?a=17", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: s.id, estilo: s.estilo, puntos: s.puntos })
    }).then(function (r) { return r.text(); }).then(function (t) {
        if (t.indexOf("error") !== -1 && typeof rfToast === "function") rfToast("No se pudo actualizar el sendero.", "err");
    }).catch(function () {});
}
function YunqueBorrarSendero(id) {
    if (!confirm("¿Eliminar este sendero?")) return;
    fetch("pages/config/acciones_ajax.php?a=18", {
        method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: id })
    }).then(function (r) { return r.text(); }).then(function (t) {
        if (t.indexOf("error") !== -1) { if (typeof rfToast === "function") rfToast("No se pudo eliminar el sendero.", "err"); return; }
        FORGE_SENDEROS = FORGE_SENDEROS.filter(function (s) { return s.id !== id; });
        YunqueDibujar();
    }).catch(function () {});
}
function YunqueSenderoHitTest(p) {
    var R = 12;
    for (var i = 0; i < FORGE_SENDEROS.length; i++) {
        var s = FORGE_SENDEROS[i];
        for (var j = 0; j < s.puntos.length; j++) {
            if (Math.abs(s.puntos[j][0] - p.x) <= R && Math.abs(s.puntos[j][1] - p.y) <= R) return { sid: i, pi: j };
        }
    }
    return null;
}

/* Despacho de clic sobre el lienzo de El Yunque. */
function YunqueOnMouseDown(e) {
    var p = ForgeCoord(Yunque.canvas, e);
    if (Yunque.modoSenderos) {
        var n = YunqueNodoHitTest(p);
        if (n) {
            if (!Yunque.nodoSel1) {
                Yunque.nodoSel1 = n;
            } else {
                if (Yunque.nodoSel1.tipo === n.tipo && Yunque.nodoSel1.ref_id === n.ref_id) {
                    Yunque.nodoSel1 = null;
                } else {
                    YunqueCrearSendero(Yunque.nodoSel1, n);
                }
            }
            YunqueRender();
            return;
        }
        // clic sobre punto intermedio de un sendero → borrarlo (shift) o arrastrar
        var hit = YunqueSenderoHitTest(p);
        if (hit) {
            if (e.shiftKey) {
                YunqueBorrarSendero(FORGE_SENDEROS[hit.sid].id);
            } else {
                Yunque.senderoDrag = hit;
                Yunque.canvas.style.cursor = "grabbing";
            }
            return;
        }
        Yunque.nodoSel1 = null;
        YunqueRender();
        return;
    }

    // modo plano normal: clic en cámara → seleccionar (panel líneas); clic en línea → arrastrar extremo
    var ci = YunqueCamHitTest(p);
    if (ci >= 0) {
        Yunque.camSeleccionada = FORGE_CAMS[ci].id;
        YunqueRenderLineasPanel();
        YunqueRender();
        return;
    }
    var lh = YunqueLineaHitTest(p);
    if (lh) {
        Yunque.lineDrag = lh;
        Yunque.canvas.style.cursor = "grabbing";
        return;
    }
    Yunque.camSeleccionada = null;
    YunqueRenderLineasPanel();
    YunqueRender();
}

function YunqueOnMouseMove(e) {
    var p = ForgeCoord(Yunque.canvas, e);
    if (Yunque.camDrag) {
        var c = FORGE_CAMS[Yunque.camDrag];
        c.x = Math.round(p.x - 6); c.y = Math.round(p.y - 6);
        YunqueClampCam(c);
        YunqueDibujar();
        return;
    }
    if (Yunque.lineDrag) {
        var L = FORGE_LINEAS_PLANO[Yunque.lineDrag.i];
        if (Yunque.lineDrag.ext === 1) { L.x1 = Math.round(p.x); L.y1 = Math.round(p.y); }
        else { L.x2 = Math.round(p.x); L.y2 = Math.round(p.y); }
        YunqueLineaClamp(L, Yunque.lineDrag.ext);
        YunqueRenderNodos();
        YunqueDibujar();
        return;
    }
    if (Yunque.senderoDrag) {
        var s = FORGE_SENDEROS[Yunque.senderoDrag.sid];
        s.puntos[Yunque.senderoDrag.pi] = [Math.round(p.x), Math.round(p.y)];
        YunqueDibujar();
        return;
    }
    // hover
    if (!Yunque.modoSenderos) {
        var ci = YunqueCamHitTest(p);
        Yunque.canvas.style.cursor = (ci >= 0) ? "pointer" : "default";
    } else {
        Yunque.canvas.style.cursor = YunqueNodoHitTest(p) ? "crosshair" : "default";
    }
}

function YunqueOnMouseUp() {
    if (Yunque.camDrag) {
        var c = FORGE_CAMS[Yunque.camDrag];
        YunqueGuardarCamPos(c.id, c.x, c.y);
        Yunque.camDrag = null;
        Yunque.canvas.style.cursor = "";
    }
    if (Yunque.lineDrag) {
        var L = FORGE_LINEAS_PLANO[Yunque.lineDrag.i];
        YunqueLineaGuardar(L.id, L.x1, L.y1, L.x2, L.y2);
        Yunque.lineDrag = null;
        Yunque.canvas.style.cursor = "";
        YunqueRenderNodos();
        YunqueDibujar();
    }
    if (Yunque.senderoDrag) {
        var s = FORGE_SENDEROS[Yunque.senderoDrag.sid];
        YunqueGuardarSendero(s);
        Yunque.senderoDrag = null;
        Yunque.canvas.style.cursor = "";
    }
}

/* =========================================================================
 * Trazador de líneas (modal con snapshot de cámara)
 * ========================================================================= */
var Trazador = {
    camId: 0, lineaEditId: null,
    canvas: null, ctx: null,
    punto: 1,
    x_lineas: [], y_lineas: [], nombres_lineas: [], id_lineas: [],
    lineas_nuevas: 0,
    voypocolores: 0,
};
var listado_colores = [
    "#e69c8c","#c58f21","#7987ff","#000b6d","#ffed00","#5c7a04","#59ff00","#215306","#8bd7ff","#617c8a","#0060ff",
    "#beffb7","#4e5c4d","#00ffb9","#006d75","#00eeff","#af381e","#004163","#7a7104",
    "#6800ff","#1f004c","#beff00","#d800ff","#710385","#ff0074","#ff0000","#a54747","#ffbebe"
];

function TrazadorLimpiar() {
    Trazador.punto = 1; Trazador.lineas_nuevas = 0; Trazador.voypocolores = 0;
    Trazador.x_lineas = []; Trazador.y_lineas = []; Trazador.nombres_lineas = []; Trazador.id_lineas = [];
    var capa = document.getElementById("nombres_lineas_capa");
    if (capa) capa.innerHTML = "";
}

function TrazadorAbrirModal() {
    var m = document.getElementById("lineaModal");
    m.classList.add("show");
    m.style.marginTop = "0"; m.style.marginLeft = "0"; m.style.zIndex = "99999";
    if (m.parentNode !== document.body) document.body.appendChild(m);
    document.body.classList.add("overflow-y-hidden");
}

function TrazadorCerrar() {
    var m = document.getElementById("lineaModal");
    if (!m) return;
    m.classList.remove("show");
    m.style.marginTop = ""; m.style.marginLeft = ""; m.style.zIndex = "";
    document.body.classList.remove("overflow-y-hidden");
}

function TrazadorAbrir(camId) {
    Trazador.camId = camId; Trazador.lineaEditId = null;
    TrazadorAbrirModal();
    TrazadorCargarFoto(camId, null);
}

function TrazadorAbrirCorregir(val) {
    var p = String(val).split("-");
    if (p.length < 2 || !p[0] || !p[1]) return;
    Trazador.camId = parseInt(p[1], 10);
    Trazador.lineaEditId = p[0];
    TrazadorAbrirModal();
    TrazadorCargarFoto(Trazador.camId, p[0]);
}

function TrazadorCargarFoto(camId, lineaEditId) {
    Trazador.camId = camId;
    Trazador.lineaEditId = lineaEditId || null;
    TrazadorLimpiar();
    var titulo = document.getElementById("lineaTitulo");
    var sub = document.getElementById("lineaSub");
    var cam = ForgeCamById(camId);
    if (titulo) titulo.textContent = lineaEditId ? "Corregir línea" : "Trazar líneas";
    if (sub) sub.textContent = cam ? cam.desc : "";

    var ajax = nuevoAjax();
    ajax.open("GET", "pages/config/acciones_ajax.php?a=3&camara=" + camId, true);
    ajax.send(null);

    var ctx = Trazador.ctx, W = Trazador.canvas.width, H = Trazador.canvas.height;
    var tries = 0;
    var img = new Image();
    (function intenta() {
        img.onload = function () {
            ctx.clearRect(0, 0, W, H);
            ctx.drawImage(img, 0, 0, W, H);
            TrazadorCargarLineas(camId, lineaEditId);
        };
        img.onerror = function () {
            if (++tries < 12) setTimeout(intenta, 1500);
            else { ctx.fillStyle = "#16121a"; ctx.fillRect(0, 0, W, H); }
        };
        img.src = "fotos_camara/" + camId + ".png?t=" + Math.floor(Date.now() / 1000);
    })();
}

function TrazadorCargarLineas(camId, lineaEditId) {
    var ajax = nuevoAjax();
    ajax.open("GET", "pages/config/acciones_ajax.php?a=4&camara=" + camId, true);
    ajax.onreadystatechange = function () {
        if (ajax.readyState != 4) return;
        var lineas = [];
        try { lineas = JSON.parse(ajax.responseText) || []; } catch (e) { lineas = []; }
        var ctx = Trazador.ctx;
        var capa = document.getElementById("nombres_lineas_capa");
        Trazador.voypocolores = 0;
        for (var i = 0; i < lineas.length; i++) {
            var l = lineas[i];
            var col = listado_colores[Trazador.voypocolores % listado_colores.length];
            ctx.strokeStyle = col; ctx.fillStyle = col;
            ctx.fillRect(l.x1, l.y1, 10, 10);
            ctx.fillRect(l.x2, l.y2, 10, 10);
            ctx.fillText(l.nombre, l.x1, l.y1);
            ctx.beginPath(); ctx.moveTo(l.x1, l.y1); ctx.lineTo(l.x2, l.y2); ctx.stroke();
            Trazador.x_lineas.push(l.x1); Trazador.x_lineas.push(l.x2);
            Trazador.y_lineas.push(l.y1); Trazador.y_lineas.push(l.y2);
            Trazador.nombres_lineas.push(l.nombre);
            Trazador.id_lineas.push(String(l.id));
            if (capa) {
                capa.innerHTML += '<div class="flex items-center gap-2">'
                    + '<span style="display:inline-block;width:10px;height:10px;background:' + col + '"></span>'
                    + '<input type="text" name="nombre_linea_' + l.id + '" id="nombre_linea_' + l.id + '" value="'
                    + String(l.nombre).replace(/"/g, "&quot;") + '" class="input border" style="border-color:' + col + '">'
                    + '<a href="?page=config&tab=lineas&sub=editar&accion=eliminar_linea&id_linea=' + l.id + '" class="text-red-400">(X)</a></div>';
            }
            Trazador.voypocolores++;
        }
        if (lineaEditId) {
            // en corregir solo se edita la línea seleccionada: marcar sus extremos
        }
    };
    ajax.send(null);
}

function TrazadorDibujaLinea(p) {
    var ctx = Trazador.ctx;
    var col = listado_colores[Trazador.voypocolores % listado_colores.length];
    var x = Math.round(p.x), y = Math.round(p.y);
    ctx.strokeStyle = col; ctx.fillStyle = col;
    ctx.fillRect(x - 5, y - 5, 10, 10);
    if (Trazador.punto === 2) {
        ctx.beginPath();
        ctx.moveTo(x, y);
        ctx.lineTo(Trazador.x_lineas[Trazador.x_lineas.length - 1], Trazador.y_lineas[Trazador.y_lineas.length - 1]);
        ctx.stroke();
        var capa = document.getElementById("nombres_lineas_capa");
        if (capa) {
            capa.innerHTML += '<div class="flex items-center gap-2"><span style="display:inline-block;width:10px;height:10px;background:' + col + '"></span>'
                + '<input type="text" name="nombre_linea_nueva_' + Trazador.lineas_nuevas + '" id="nombre_linea_nueva_' + Trazador.lineas_nuevas + '" value="" class="input border" placeholder="nombre de la línea"></div>';
        }
        Trazador.voypocolores++;
        Trazador.lineas_nuevas++;
    }
    Trazador.x_lineas.push(x);
    Trazador.y_lineas.push(y);
    Trazador.punto = (Trazador.punto === 1) ? 2 : 1;
}

function TrazadorGuardar() {
    if (Trazador.lineaEditId) {
        // corregir una línea existente
        var idx = Trazador.id_lineas.indexOf(String(Trazador.lineaEditId));
        if (idx === -1) { alert("Línea no encontrada. Vuelve a cargarla."); return; }
        var lasx = Trazador.x_lineas[idx * 2] + ",,," + Trazador.x_lineas[(idx * 2) + 1];
        var lasy = Trazador.y_lineas[idx * 2] + ",,," + Trazador.y_lineas[(idx * 2) + 1];
        var url = "?page=config&tab=lineas&sub=editar&accion=editar_lineas&linea_id=" + Trazador.lineaEditId
            + "&lasx=" + encodeURIComponent(lasx) + "&lasy=" + encodeURIComponent(lasy)
            + "&losnombres=0&losids=0&camara_id=" + Trazador.camId + "&mostrar_foto=" + Trazador.camId + "&editar_linea=" + Trazador.lineaEditId + "-" + Trazador.camId;
        location.href = url;
        return;
    }

    // guardar líneas nuevas
    var lasx = "", lasy = "", losnombres = "", losids = "";
    for (var i = 0; i < Trazador.id_lineas.length; i++) {
        if (lasx !== "") { lasx += ",,,"; lasy += ",,,"; losids += ",,,"; losnombres += ",,,"; }
        lasx += Trazador.x_lineas[i * 2] + ",,," + Trazador.x_lineas[(i * 2) + 1];
        lasy += Trazador.y_lineas[i * 2] + ",,," + Trazador.y_lineas[(i * 2) + 1];
        losids += Trazador.id_lineas[i];
        var nel = document.getElementById("nombre_linea_" + Trazador.id_lineas[i]);
        losnombres += nel ? nel.value : "";
    }
    for (var j = 0; j < Trazador.lineas_nuevas; j++) {
        if (lasx !== "") { lasx += ",,,"; lasy += ",,,"; losids += ",,,"; losnombres += ",,,"; }
        lasx += Trazador.x_lineas[(Trazador.id_lineas.length + j) * 2] + ",,," + Trazador.x_lineas[(Trazador.id_lineas.length + j) * 2 + 1];
        lasy += Trazador.y_lineas[(Trazador.id_lineas.length + j) * 2] + ",,," + Trazador.y_lineas[(Trazador.id_lineas.length + j) * 2 + 1];
        losids += "0";
        var nnel = document.getElementById("nombre_linea_nueva_" + j);
        losnombres += nnel ? nnel.value : "";
    }
    var url = "?page=config&tab=lineas&sub=trazar&accion=guardar_lineas&lasx=" + encodeURIComponent(lasx)
        + "&lasy=" + encodeURIComponent(lasy) + "&losnombres=" + encodeURIComponent(losnombres)
        + "&losids=" + encodeURIComponent(losids) + "&camara_id=" + Trazador.camId + "&mostrar_foto=" + Trazador.camId;
    location.href = url;
}

/* =========================================================================
 * Acciones de formulario legacy (cámaras, plano)
 * ========================================================================= */
function crear() {
    var nombre_nueva = document.getElementById("nombre_nueva").value;
    var url_conexion = document.getElementById("url_conexion_nueva").value;

    var puerta = document.getElementById("entrada1").checked ? 1 : 0;
    var salida = document.getElementById("salida1").checked ? 1 : 0;
    var encendida_nueva = document.getElementById("encendida_nueva").checked ? 1 : 0;

    url_conexion = url_conexion.replace(/&/g, "--jos--");

    var uri = "?page=config&tab=camaras&sub=crear&accion=crear&nombre_nueva=" + encodeURIComponent(nombre_nueva)
        + "&puerta=" + puerta + "&salida=" + salida + "&encendida_nueva=" + encendida_nueva
        + "&url_conexion=" + encodeURIComponent(url_conexion) + "&sistema=0";
    location.href = uri;
}

function guardar() {
    var camara = document.getElementById("camara").value;
    var nombre = document.getElementById("nombre").value;
    var url_conexion = document.getElementById("url_conexion").value;
    var url_desdeserver = document.getElementById("url_desdeserver").value;

    var segundos_analizar = document.getElementById("segundos_analizar").value;
    var porcentaje_mov = document.getElementById("porcentaje_mov").value;
    var dontCare = document.getElementById("dontCare").value;
    var fps = document.getElementById("fps").value;
    var maximo_videos = document.getElementById("maximo_videos").value;
    var redimesionframe = document.getElementById("redimesionframe").value;
    var sensibilidad = document.getElementById("sensibilidad").value;

    var puerta = document.getElementById("entrada2").checked ? 1 : 0;
    var salida = document.getElementById("salida2").checked ? 1 : 0;
    var encendida = document.getElementById("encendida").checked ? 1 : 0;

    url_conexion = url_conexion.replace(/&/g, "--jos--");
    url_desdeserver = url_desdeserver.replace(/&/g, "--jos--");

    var uri = "?page=config&tab=camaras&sub=editar&accion=guardar&camara=" + camara
        + "&nombre=" + encodeURIComponent(nombre) + "&encendida=" + encendida
        + "&puerta=" + puerta + "&salida=" + salida
        + "&url_conexion=" + encodeURIComponent(url_conexion)
        + "&url_desdeserver=" + encodeURIComponent(url_desdeserver) + "&sistema=0"
        + "&segundos_analizar=" + segundos_analizar + "&porcentaje_mov=" + porcentaje_mov
        + "&dontCare=" + dontCare + "&fps=" + fps + "&maximo_videos=" + maximo_videos
        + "&redimesionframe=" + redimesionframe + "&sensibilidad=" + sensibilidad;
    location.href = uri;
}

function seleccionar_camara() {
    var camara = document.getElementById("camara").value;
    if (!camara || camara === "-") return;
    var ajax = nuevoAjax();
    ajax.open("GET", "pages/config/acciones_ajax.php?a=1&camara=" + camara, true);
    ajax.onreadystatechange = function () {
        if (ajax.readyState == 4) {
            var res = ajax.responseText.split(";;;");
            document.getElementById("nombre").value = res[0];
            if (res[4] == 1) document.getElementById("entrada2").checked = true; else document.getElementById("entrada2").checked = false;
            if (res[5] == 1) document.getElementById("salida2").checked = true; else document.getElementById("salida2").checked = false;
            if (res[6] == 1) document.getElementById("encendida").checked = true; else document.getElementById("encendida").checked = false;
            document.getElementById("url_conexion").value = String(res[7]).replace(/--jos--/g, "&");
            document.getElementById("url_desdeserver").value = String(res[10]).replace(/--jos--/g, "&");
            document.getElementById("segundos_analizar").value = res[11];
            document.getElementById("porcentaje_mov").value = res[12];
            document.getElementById("dontCare").value = res[13];
            document.getElementById("fps").value = res[14];
            document.getElementById("maximo_videos").value = res[15];
            document.getElementById("redimesionframe").value = res[16];
            document.getElementById("sensibilidad").value = res[17];
        }
    };
    ajax.send(null);
}

function cargarplano() {
    document.getElementById("formplano").submit();
}

/* =========================================================================
 * Editor de croquis a mano alzada (tipo Paint) — plano_dibujo_<local>.png
 * ========================================================================= */
var dibujo = {
    abierto: false, canvas: null, ctx: null, capa: null, capaCtx: null,
    fondo: null, base: null, dibujando: false, cargando: false, ultimo: null,
    color: "#1e1e1e", grosor: 3, borrador: false, undo: []
};

function dibujoCoord(e) {
    var rect = dibujo.canvas.getBoundingClientRect();
    return { x: (e.clientX - rect.left) * dibujo.canvas.width / rect.width, y: (e.clientY - rect.top) * dibujo.canvas.height / rect.height };
}
function dibujoRedibujar() {
    var ctx = dibujo.ctx, w = dibujo.canvas.width, h = dibujo.canvas.height;
    ctx.fillStyle = "#ffffff"; ctx.fillRect(0, 0, w, h);
    if (dibujo.fondo && document.getElementById("dibujoFondo").checked) {
        ctx.save(); ctx.globalAlpha = 0.45; ctx.drawImage(dibujo.fondo, 0, 0, w, h); ctx.restore();
    }
    if (dibujo.capa) ctx.drawImage(dibujo.capa, 0, 0);
}
function dibujoGuardarSnapshot() {
    var w = dibujo.canvas.width, h = dibujo.canvas.height;
    if (dibujo.undo.length >= 20) dibujo.undo.shift();
    dibujo.undo.push(dibujo.capaCtx.getImageData(0, 0, w, h));
}
function dibujoPincel(p) {
    var ctx = dibujo.capaCtx;
    ctx.save();
    ctx.strokeStyle = dibujo.borrador ? "#ffffff" : dibujo.color;
    ctx.lineWidth = dibujo.borrador ? dibujo.grosor * 2 : dibujo.grosor;
    ctx.lineCap = "round"; ctx.lineJoin = "round";
    if (dibujo.borrador) ctx.globalCompositeOperation = "destination-out";
    ctx.beginPath(); ctx.moveTo(dibujo.ultimo.x, dibujo.ultimo.y); ctx.lineTo(p.x, p.y); ctx.stroke();
    ctx.restore();
}
function dibujoToggleBorrador() {
    dibujo.borrador = !dibujo.borrador;
    document.getElementById("dibujoBorrador").classList.toggle("is-activo", dibujo.borrador);
}
function dibujoDeshacer() {
    if (!dibujo.undo.length) return;
    dibujo.capaCtx.putImageData(dibujo.undo.pop(), 0, 0);
    dibujoRedibujar();
}
function dibujoLimpiar() {
    if (!confirm("¿Borrar todo el croquis y empezar de nuevo?")) return;
    dibujo.base = null; dibujo.undo = [];
    dibujo.capaCtx.clearRect(0, 0, dibujo.canvas.width, dibujo.canvas.height);
    dibujoRedibujar();
}
function cargarDibujoFondo() {
    var usaFondo = document.getElementById("dibujoFondo").checked;
    if (usaFondo && PLANO_ACTIVO_URL) {
        var img = new Image();
        img.onload = function () { dibujo.fondo = img; dibujoRedibujar(); };
        img.onerror = function () { dibujo.fondo = null; dibujoRedibujar(); };
        img.src = PLANO_ACTIVO_URL;
    } else { dibujo.fondo = null; dibujoRedibujar(); }
}
function abrirDibujo() {
    dibujo.canvas = document.getElementById("canvasDibujo");
    dibujo.ctx = dibujo.canvas.getContext("2d");
    var plan = document.getElementById("canvasID");
    if (plan) {
        var r = plan.getBoundingClientRect();
        if (r.width > 0 && r.height > 0) { dibujo.canvas.style.width = r.width + "px"; dibujo.canvas.style.height = "auto"; }
    }
    if (!dibujo.capa) {
        dibujo.capa = document.createElement("canvas");
        dibujo.capa.width = dibujo.canvas.width; dibujo.capa.height = dibujo.canvas.height;
        dibujo.capaCtx = dibujo.capa.getContext("2d");
    }
    dibujo.base = null; dibujo.fondo = null; dibujo.undo = []; dibujo.borrador = false;
    document.getElementById("dibujoBorrador").classList.remove("is-activo");
    document.getElementById("dibujoGrosor").value = 3;
    document.getElementById("dibujoGrosorVal").textContent = 3;
    dibujo.grosor = 3;
    document.getElementById("dibujoFondo").checked = true;
    dibujo.capaCtx.clearRect(0, 0, dibujo.canvas.width, dibujo.canvas.height);

    if (PLANO_DIBUJO_URL) {
        document.getElementById("dibujoFondoWrap").classList.add("dibujo-fondo--oculto");
        dibujo.cargando = true;
        var img = new Image();
        img.onload = function () {
            dibujo.base = img;
            dibujo.capaCtx.drawImage(img, 0, 0, dibujo.canvas.width, dibujo.canvas.height);
            dibujoGuardarSnapshot(); dibujo.cargando = false; dibujoRedibujar();
        };
        img.onerror = function () { dibujo.base = null; dibujo.cargando = false; dibujoRedibujar(); alert("No se pudo cargar el croquis existente."); };
        img.src = PLANO_DIBUJO_URL + "?v=" + Date.now();
    } else {
        document.getElementById("dibujoFondoWrap").classList.remove("dibujo-fondo--oculto");
        cargarDibujoFondo();
        dibujoRedibujar();
    }
    dibujo.abierto = true;
    var modal = document.getElementById("planoDibujoModal");
    modal.classList.add("show");
    modal.style.marginTop = "0"; modal.style.marginLeft = "0"; modal.style.zIndex = "99999";
    if (modal.parentNode !== document.body) document.body.appendChild(modal);
    document.body.classList.add("overflow-y-hidden");
}
function cerrarDibujo() {
    dibujo.abierto = false;
    var modal = document.getElementById("planoDibujoModal");
    if (!modal) return;
    modal.classList.remove("show");
    modal.style.marginTop = ""; modal.style.marginLeft = ""; modal.style.zIndex = "";
    document.body.classList.remove("overflow-y-hidden");
}
function guardarDibujo() {
    if (!dibujo.abierto) return;
    var salida = document.createElement("canvas");
    salida.width = dibujo.canvas.width; salida.height = dibujo.canvas.height;
    var sctx = salida.getContext("2d");
    sctx.fillStyle = "#ffffff"; sctx.fillRect(0, 0, salida.width, salida.height);
    if (dibujo.capa) sctx.drawImage(dibujo.capa, 0, 0);
    var dataURL = salida.toDataURL("image/png");
    var fd = new FormData();
    fd.append("plano_dibujo", dataURL);
    fetch("?page=config&tab=plano&accion=plano_dibujo", { method: "POST", body: fd })
        .then(function (res) {
            if (!res.ok) throw new Error("HTTP " + res.status);
            if (res.redirected) { location.href = "?page=config&tab=plano"; return null; }
            return res.text();
        })
        .then(function (txt) {
            if (txt === null) return;
            if (txt.indexOf("Error") !== -1) { alert(txt); return; }
            location.href = "?page=config&tab=plano";
        })
        .catch(function (err) { alert("No se pudo guardar el croquis: " + err.message); });
}

/* =========================================================================
 * Init
 * ========================================================================= */
document.addEventListener("DOMContentLoaded", function () {
    /* ---------- El Yunque (tab=plano) ---------- */
    if (FORGE_TAB === "plano") {
        Yunque.canvas = document.getElementById("canvasID");
        if (Yunque.canvas) {
            Yunque.ctx = Yunque.canvas.getContext("2d");
            Yunque.canvas.addEventListener("mousedown", YunqueOnMouseDown);
            Yunque.canvas.addEventListener("mousemove", YunqueOnMouseMove);
            Yunque.canvas.addEventListener("mouseup", YunqueOnMouseUp);
            Yunque.canvas.addEventListener("mouseleave", YunqueOnMouseUp);

            // cargar plano activo
            if (PLANO_ACTIVO_URL) {
                Yunque.planoImg = new Image();
                Yunque.planoImg.onload = function () { YunqueDibujar(); };
                Yunque.planoImg.onerror = function () { YunqueDibujar(); };
                Yunque.planoImg.src = PLANO_ACTIVO_URL;
            } else {
                YunqueDibujar();
            }
            YunqueRenderSidebar();
            YunqueRenderEstado();
        }

        // toggle modo senderos + estilo
        var toggle = document.getElementById("yunqueModoSenderos");
        if (toggle) toggle.addEventListener("change", function () {
            Yunque.modoSenderos = toggle.checked;
            Yunque.nodoSel1 = null;
            Yunque.camSeleccionada = null;
            YunqueRenderLineasPanel();
            YunqueRender();
        });
        var estilo = document.getElementById("yunqueEstilo");
        if (estilo) estilo.addEventListener("change", function () { Yunque.estilo = estilo.value; });

        // HTML5 DnD: cámaras desde la barra lateral + líneas desde el panel
        var canvasEl = Yunque.canvas;
        if (canvasEl) {
            canvasEl.addEventListener("dragover", function (e) { e.preventDefault(); });
            canvasEl.addEventListener("drop", function (e) {
                e.preventDefault();
                var p = ForgeCoord(Yunque.canvas, e);
                var camId = e.dataTransfer.getData("text/camara");
                var lineaId = e.dataTransfer.getData("text/linea");
                if (camId) YunqueColocarCamara(parseInt(camId, 10), p);
                if (lineaId) YunqueColocarLinea(parseInt(lineaId, 10), p);
            });
        }
        document.addEventListener("dragstart", function (e) {
            var camCard = e.target.closest ? e.target.closest(".yunque-cam-fuera") : null;
            if (camCard) { e.dataTransfer.setData("text/camara", camCard.getAttribute("data-cam-id")); return; }
            var lineaChip = e.target.closest ? e.target.closest(".yunque-linea--pend") : null;
            if (lineaChip) { e.dataTransfer.setData("text/linea", lineaChip.getAttribute("data-linea-id")); }
        });
    }

    /* ---------- Trazador de líneas (tab=lineas) ---------- */
    if (FORGE_TAB === "lineas") {
        Trazador.canvas = document.getElementById("canvasLineas");
        if (Trazador.canvas) {
            Trazador.ctx = Trazador.canvas.getContext("2d");
            Trazador.canvas.addEventListener("mousedown", function (e) {
                TrazadorDibujaLinea(ForgeCoord(Trazador.canvas, e));
            });
        }
        // deep-link de corregir
        if (FORGE_SUB === "editar" && <?= json_encode($_GET["editar_linea"] ?? ""); ?>) {
            TrazadorAbrirCorregir(<?= json_encode($_GET["editar_linea"] ?? ""); ?>);
        }
    }

    /* ---------- Editor de croquis (modal) ---------- */
    var canvas = document.getElementById("canvasDibujo");
    if (canvas) {
        var color = document.getElementById("dibujoColor");
        var grosor = document.getElementById("dibujoGrosor");
        color.addEventListener("input", function () { dibujo.color = color.value; dibujo.borrador = false; document.getElementById("dibujoBorrador").classList.remove("is-activo"); });
        grosor.addEventListener("input", function () { dibujo.grosor = parseInt(grosor.value, 10) || 3; document.getElementById("dibujoGrosorVal").textContent = dibujo.grosor; });
        document.getElementById("dibujoFondo").addEventListener("change", cargarDibujoFondo);
        document.addEventListener("keydown", function (e) { if (e.key === "Escape" && dibujo.abierto) cerrarDibujo(); });

        canvas.addEventListener("mousedown", function (e) {
            if (!dibujo.abierto || dibujo.cargando) return;
            dibujo.dibujando = true;
            dibujo.ultimo = dibujoCoord(e);
            dibujoGuardarSnapshot();
            dibujoPincel(dibujo.ultimo);
            dibujoRedibujar();
        });
        canvas.addEventListener("mousemove", function (e) {
            if (!dibujo.abierto || !dibujo.dibujando) return;
            var p = dibujoCoord(e);
            dibujoPincel(p); dibujo.ultimo = p; dibujoRedibujar();
        });
        canvas.addEventListener("mouseup", function () { dibujo.dibujando = false; });
        canvas.addEventListener("mouseleave", function () { dibujo.dibujando = false; });

        document.querySelectorAll(".rf-tab.is-empty").forEach(function (tab) {
            tab.addEventListener("click", function (e) { e.preventDefault(); alert("Ese plano todavía no existe. Súbelo o dibújalo primero."); });
        });
    }
});
</script>
