<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 06/08/2020
 */
?>

<!-- BEGIN: Content -->
<div class="content">
<?php

switch($_GET["page"]){
    case "visitantes":
        require_once "./pages/visitantes/index.php";
        break;
    case "accesos":
        require_once "./pages/accesos/index.php";
        break;
    case "rutas":
        require_once "./pages/rutas/index.php";
        break;
    case "config":
        require_once "./pages/config/index.php";
        break;
    case "ayuda":
        require_once "./pages/ayuda/index.php";
        break;
    case "fichajes":
        require_once "./pages/fichajes/index.php";
        break;
    case "locales":
        require_once "./pages/locales/index.php";
        break;
    case "camaras":
        require_once "./pages/camaras/index.php";
        break;
    case "lineas":
        require_once "./pages/lineas/index.php";
        break;
    case "alarmas":
        require_once "./pages/alarmas/index.php";
        break;
    default:
        require_once "./pages/dashboard/index.php";
        break;
}


?>
</div>
<!-- END: Content -->

