<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 06/08/2020
 * 
 * REFACTOR: barra móvil superior eliminada; ahora es un DRAWER lateral
 * (panel deslizante) que abre la hamburguesa de la top-bar en responsive
 * (<768px). Solo existe en móvil (md:hidden).
 * 
 * MEJORA 2026-08-19 (reordenación del menú):
 *   - "La Torre" (👁️ dash) abre el drawer en PRIMERA posición; "El Ojo en
 *     Vivo" (camaras) le sigue en segunda con el ojo de Sauron destacado
 *     y "La Forja" (⚒️ config) en tercera con tratamiento hero.
 *   - Se retiran "Fortalezas" y "Fichajes" (accesibles vía la pestaña
 *     "Fortalezas" de La Forja y el dashboard respectivamente).
 */

?>

<!-- BEGIN: Drawer lateral (menú principal en móvil) -->
<div id="panel-drawer-backdrop" class="panel-drawer-backdrop md:hidden" aria-hidden="true"></div>
<aside id="panel-drawer" class="panel-drawer md:hidden" aria-hidden="true" aria-label="Menú principal del panel">
    <div class="panel-drawer__header">
        <a href="?" class="baradur-brand">
            <span class="menu__emoji" style="font-size:1.6rem">👁️</span>
            <span class="baradur-brand__word">Barad-<span class="font-medium">dûr</span></span>
        </a>
        <a href="javascript:;" id="panel-drawer-close" class="panel-drawer__close" aria-label="Cerrar menú">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
        </a>
    </div>
    <ul class="panel-drawer__menu">

        <li>
            <a href="?page=dash" class="menu menu<?php if(!isset($_GET["page"]) or $_GET["page"]=="" or $_GET["page"]=="dash"){ echo "--active"; } ?>">

                <div class="menu__icon menu__emoji">👁️</div>

                <div class="menu__title"> La Torre </div>
            </a>
        </li>

        <li>
            <a href="?page=camaras" class="menu menu--featured menu<?php if(isset($_GET["page"]) and $_GET["page"]=="camaras"){ echo "--active"; } ?>">

                <div class="menu__icon">
                    <svg class="sauron-eye sauron-eye--menu" viewBox="0 0 48 48" aria-hidden="true" focusable="false">
                        <defs>
                            <radialGradient id="sauron-iris-drawer" cx="50%" cy="38%" r="75%">
                                <stop offset="0%" stop-color="#ffd9a0"/>
                                <stop offset="45%" stop-color="#ff5a1f"/>
                                <stop offset="100%" stop-color="#8c1f00"/>
                            </radialGradient>
                        </defs>
                        <!-- anillo exterior orco -->
                        <circle cx="24" cy="24" r="22" fill="none" stroke="rgba(201,162,39,0.6)" stroke-width="1.6"/>
                        <!-- contorno superior (ceño de Sauron) -->
                        <path d="M9 16 C 14 10, 20 7.5, 24 7.5 C 28 7.5, 34 10, 39 16" fill="none" stroke="rgba(255,90,31,0.8)" stroke-width="1.8" stroke-linecap="round"/>
                        <!-- forma del ojo (rendija) -->
                        <path d="M4.5 24 C 8 16.5, 15 12.5, 24 12.5 C 33 12.5, 40 16.5, 43.5 24 C 40 31.5, 33 35.5, 24 35.5 C 15 35.5, 8 31.5, 4.5 24 Z" fill="rgba(255,90,31,0.12)" stroke="#ff5a1f" stroke-width="1.4"/>
                        <!-- iris -->
                        <ellipse class="sauron-eye__iris" cx="24" cy="24" rx="11.5" ry="8.5" fill="url(#sauron-iris-drawer)"/>
                        <!-- pupila vertical (se mueve con el cursor) -->
                        <path class="sauron-eye__pupil" d="M24 16.5 C 26.6 16.5 27.4 22 27.4 24 C 27.4 26 26.6 31.5 24 31.5 C 21.4 31.5 20.6 26 20.6 24 C 20.6 22 21.4 16.5 24 16.5 Z" fill="#0d0503"/>
                        <!-- brillo -->
                        <circle class="sauron-eye__shine" cx="27.4" cy="20.5" r="1.5" fill="rgba(255,235,205,0.95)"/>
                    </svg>
                </div>

                <div class="menu__title"> El Ojo en Vivo <span class="live-dot live-dot--menu" aria-hidden="true"></span></div>
            </a>
        </li>

        <li>
            <a href="?page=config" class="menu menu--hero menu<?php if(isset($_GET["page"]) and $_GET["page"]=="config"){ echo "--active"; } ?>">

                <div class="menu__icon menu__emoji">⚒️</div>

                <div class="menu__title"> La Forja </div>
            </a>
        </li>

        <li class="panel-drawer__sep" aria-hidden="true"></li>

        <li>
            <a href="?page=accesos" class="menu menu<?php if(isset($_GET["page"]) and $_GET["page"]=="accesos"){ echo "--active"; } ?>">
                <div class="menu__icon menu__emoji">⚔️</div>
                <div class="menu__title"> Movimientos </div>
            </a>
        </li>

        <li>
            <a href="?page=visitantes" class="menu menu<?php if(isset($_GET["page"]) and $_GET["page"]=="visitantes"){ echo "--active"; } ?>">

                <div class="menu__icon menu__emoji">👹</div>
                
                <div class="menu__title"> Pueblos </div>
            </a>
        </li>

        <li>
            <a href="?page=rutas" class="menu menu<?php if(isset($_GET["page"]) and $_GET["page"]=="rutas"){ echo "--active"; } ?>">
                <div class="menu__icon menu__emoji">🗺️</div>
                <div class="menu__title"> Caminos </div>
            </a>
        </li>

        <li>
            <a href="?page=lineas" class="menu menu<?php if(isset($_GET["page"]) and $_GET["page"]=="lineas"){ echo "--active"; } ?>">
                <div class="menu__icon">
                    <svg class="menu__svg" viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                        <!-- rejilla del plano (apagada) -->
                        <path d="M5 5h14M5 12h14M5 19h14" stroke="currentColor" stroke-width="1.1" stroke-dasharray="2 2.4" opacity="0.5"/>
                        <!-- línea de cruce virtual -->
                        <path d="M4.5 20.5 19.5 3.5" stroke="var(--mordor-brasa)" stroke-width="1.8"/>
                        <!-- ménsulas de anclaje -->
                        <path d="M5.5 5.5 8.5 8.5M15.5 15.5 18.5 18.5" stroke="var(--mordor-oro)" stroke-width="1.3"/>
                        <!-- nodo de cruce -->
                        <circle cx="12" cy="12" r="1.7" fill="var(--mordor-oro)"/>
                    </svg>
                </div>
                <div class="menu__title"> Líneas </div>
            </a>
        </li>

        <li class="panel-drawer__sep" aria-hidden="true"></li>

        <li>
            <a href="?page=ayuda" class="menu menu<?php if(isset($_GET["page"]) and $_GET["page"]=="ayuda"){ echo "--active"; } ?>">
                <div class="menu__icon menu__emoji">📜</div>
                <div class="menu__title"> El Concilio </div>
            </a>
        </li>


    </ul>
</aside>
<!-- END: Drawer lateral -->
