<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 06/08/2020
 */

?>

<!-- BEGIN: Top Menu -->
<nav class="top-nav">
    <ul>
        <li>
            <a href="?page=dash" class="top-menu top-menu<?php if(!isset($_GET["page"]) or $_GET["page"]=="" or $_GET["page"]=="dash"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="monitor"></div>
                <div class="top-menu__title"> Dashboard </div>
            </a>
        </li>
        
        <?php
        if($_SESSION["admin"]==1){
        ?>
        <li>
            <a href="?page=locales" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="locales"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="home"></div>
                <div class="top-menu__title"> Locales </div>
            </a>
        </li>
        <?php
        }
        ?>
        
        <li>
            <a href="?page=visitantes" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="visitantes"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="users"></div>
                <div class="top-menu__title"> Personas </div>
            </a>
        </li>
        
        
        <li>
            <a href="?page=accesos" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="accesos"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="thumbs-up"></div>
                <div class="top-menu__title"> Movimientos </div>
            </a>
        </li>
        <li>
            <a href="?page=lineas" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="lineas"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="thumbs-up"></div>
                <div class="top-menu__title"> Lineas </div>
            </a>
        </li>
        
        <li>
            <a href="?page=rutas" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="rutas"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="repeat"></div>
                <div class="top-menu__title"> Rutas </div>
            </a>
        </li>
        
        <li>
            <a href="?page=config" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="config"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="settings"></div>
                <div class="top-menu__title"> Config. </div>
            </a>
        </li>
        
        <li>
            <a href="?page=camaras" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="camaras"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="camera"></div>
                <div class="top-menu__title"> En Directo </div>
            </a>
        </li>
        
        
        <li>
            <a href="?page=fichajes" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="fichajes"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="clock"></div>
                <div class="top-menu__title"> Fichajes </div>
            </a>
        </li>

        
        <li>
            <a href="?page=ayuda" class="top-menu top-menu<?php if(isset($_GET["page"]) and $_GET["page"]=="ayuda"){ echo "--active"; } ?>">
                <div class="menu__icon" data-feather="heart"></div>
                <div class="top-menu__title"> Ayuda </div>
            </a>
        </li>
        
        
        
        
    </ul>
</nav>
<!-- END: Top Menu -->
