<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 22-jul-2021, 12:05:25.
 */

header('Access-Control-Allow-Origin: *');


?>
<!-- include jquery + source -->
    <script language="javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script> 
    <script language="javascript" src="http://revolunet.github.com/VLCcontrols/src/jquery-vlc.js"></script> 
    <link rel="stylesheet" type="text/css" href="http://revolunet.github.com/VLCcontrols/src/styles.css" /> 
    <!-- embed the player and play a file -->
    <script language="javascript">
        var player = VLCobject.embedPlayer('vlc1', 400, 300);
        player.play('rtsp://admin:bakcAse4@nouesmalt.duckdns.org:777/cam/realmonitor?channel=1&subtype=0');
    </script>