<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 06/08/2020
 */
if(isset($_GET["desconectar"]) and $_GET["desconectar"]=="1"){
    $_SESSION["user"]="";
    $_SESSION["local_id"]="";
    $_SESSION["admin"]="";
    unset($_SESSION["user"]);
    unset($_SESSION["local_id"]);
    unset($_SESSION["admin"]);
    echo "<script>location.href='login.php';</script>";
    exit;
}
if(isset($_GET["local"]) and $_GET["local"]!=""){
    $_SESSION["local_id"]=$_GET["local"];
    echo "<script>location.href='index.php';</script>";
    exit;
}
        


?>
<!-- BEGIN: Account Menu -->
<div class="intro-x dropdown w-8 h-8 relative">
    <div class="dropdown-toggle w-8 h-8 rounded-full overflow-hidden shadow-lg image-fit zoom-in scale-110">
        <img alt="<?= $local["nombre"]; ?>" src="<?= $local["url_logo"]; ?>">
    </div>
    <div class="dropdown-box mt-10 absolute w-56 top-0 right-0 z-20">
        <div class="dropdown-box__content box bg-theme-38 dark:bg-dark-6 text-white">
            <div class="p-4 border-b border-theme-40 dark:border-dark-3">
                <div class="font-medium"><?= $local["nombre"]; ?></div>
            </div>
            <div class="p-2">
                
                <?php
                if($_SESSION["admin"]==1){
                    $sql->Consultar('locales','*',"id>0");
                    if($sql->num>0){
                        do{
                            echo '<a href="?local='.$sql->row["id"].'" class="flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-1 dark:hover:bg-dark-3 rounded-md"> <img src="'.$sql->row["url_logo"].'" style="width:30px">'.$sql->row["nombre"].' </a>';
                        }while($sql->Siguiente());
                    }
                }
                ?>
                
                
            </div>
            <div class="p-2 border-t border-theme-40 dark:border-dark-3">
                <a href="?desconectar=1" class="flex items-center block p-2 transition duration-300 ease-in-out hover:bg-theme-1 dark:hover:bg-dark-3 rounded-md"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-toggle-right w-4 h-4 mr-2"><rect x="1" y="5" width="22" height="14" rx="7" ry="7"></rect><circle cx="16" cy="12" r="3"></circle></svg> Desconectar </a>
            </div>
        </div>
    </div>
</div>
<!-- END: Account Menu -->

