<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 10/08/2020
 */
require_once '../../../includes/rutas.php';
require_once '../../../libs/mysql.class.php';

$tmp = new Conectar();
$tmp2 = new Conectar();

switch ($_GET["a"]) {
    case "1": //guarda el nombre del usuario
        $persona_id=$_GET["persona_id"];
        $valor=$_GET["valor"];
        $tmp->Actualizar("personas", ["nombre"], [$valor], "id=".$persona_id);
        echo "ok";
        break;
    case "2": //si es trabajador
        $persona_id=$_GET["persona_id"];
        $valor=$_GET["valor"];
        $tmp->Actualizar("personas", ["trabajador"], [$valor], "id=".$persona_id);
        echo "ok";
        break;
        
    case "3": //subir imagen y cmprobar que esta en una determomnada posicion
        
        
        break;
    
    
    default:
        break;
        
}
?>