<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 29-jul-2021, 11:06:53.
 */
if(isset($_GET["este"]) and $_GET["este"]!=""){
    $original=$_GET["este"];
    $copia=$_GET["coneste"];
    
    $sql->Actualizar("estancias",["persona_id"],[$original],"persona_id=".$copia);
    
    $sql->Consultar('personas','*',"id=".$original);
    $cod_interno_original=$sql->row["cod_interno"];
    
    $sql->Consultar('personas','*',"id=".$copia);
    $cod_interno_copia=$sql->row["cod_interno"];
    
    
    $cmd="python3.7 ../motor/juntar_personas.py ".$_SESSION["local_id"]." ".$cod_interno_original." ".$cod_interno_copia;
    //echo $cmd;
    exec($cmd);
    
    $sql->Eliminar("personas","id=".$copia);
    
}

if(isset($_GET["mover"]) and $_GET["mover"]!=""){
    
    $foto_id_origen=$_GET["mover"];
    $persona_id_destino=$_GET["aeste"];
    
    $sql->Consultar('fotos','*',"id=".$foto_id_origen);
    $foto_identificador_unico=$sql->row["identificador_unico"];
    $estancia_id_inicial=$sql->row["estancia_id"];
    
    
    $sql->Consultar('estancias','*',"id=".$estancia_id_inicial);
    $camara_id=$sql->row["camara_id"];
    $fecha_ini=$sql->row["fecha_ini"];
    $fecha_fin=$sql->row["fecha_fin"];
    $notificacion_vista=$sql->row["notificacion_vista"];

    if($persona_id_destino==0){
        $sql->Consultar('camaras','*',"id=".$camara_id);
        $local_id=$sql->row["local_id"];
        $persona=file_get_contents(URL_BASE_SERVER."ws.php?accion=nombreunico");    
        
        $campos=["local_id","cod_interno"];
        $valores=[$local_id,$persona];
        $sql->Insertar("personas",$campos,$valores,false);
        $persona_id_destino=$sql->id;
    }
    
    $sql->Insertar('estancias',
            ["persona_id","camara_id","fecha_ini","fecha_fin","notificacion_vista"],
            [$persona_id_destino,$camara_id,$fecha_ini,$fecha_fin,$notificacion_vista]);
    
    $sql->Actualizar('fotos',["estancia_id"],[$sql->id],"id=".$foto_id_origen);
    
    $sql->Consultar('fotos','*',"estancia_id=".$estancia_id_inicial);
    if($sql->num==0){
        $sql->Eliminar("estancias","id=".$estancia_id_inicial);
    }
    
    $sql->Consultar('personas','*',"id=".$persona_id_destino);
    $persona_cod_interno=$sql->row["cod_interno"];

    $cmd="python3.7 ../motor/cambiar_foto_de_persona.py ".$_SESSION["local_id"]." ".$foto_identificador_unico." ".$persona_cod_interno;
    //echo $cmd;
    exec($cmd);
     
}


if(isset($_GET["info"]) and $_GET["info"]=="subir_video"){
    //$video=$_FILES["video"];
    $uploads_dir="files/videos_registro";
    
    $tmp_name = $_FILES["video"]["tmp_name"];
    //$tmp_name = $_FILES["video2"]["tmp_name"];
    //$name = basename($_FILES["video"]["name"]);
    $name = $_GET["nombre"];
    
    echo "Mover de:".$tmp_name."----"."$uploads_dir/$name.avi";
    
    if(move_uploaded_file($tmp_name, "$uploads_dir/$name.avi")){
        echo "Subido correctamente";
        exec(RUTA_PROYECTO."procesa_video_registro.php ".$_SESSION["local_id"]);

    }else{
        echo "NO subido";
    }
    exit;
}



//http://localhost/reconocimientoFacial/proyecto_definitivo/admin/index.php?page=visitantes&mode=registrar&info=checkearPosicionCara_test&posicion=1&debug=1
if(isset($_GET["info"]) and $_GET["info"]=="checkearPosicionCara_test"){
    
        $uploads_dir="files/videos_registro";
    
    
        echo "checkearPosicionCara_test<br />";
        
        $terminado=false;
        $fichero_respuesta=$uploads_dir."/".$_SESSION["local_id"].".txt";
        
        echo "fichero de respuesta:".$fichero_respuesta."<br />";
        while(!$terminado){
            echo "No terminado<br />";
            if(file_exists($fichero_respuesta)){
                echo "El fichero existe<br />";
                $respuesta= file_get_contents($fichero_respuesta);
                echo "la respuesta en el fichero es:->".$respuesta."<-<br />";
                $terminado=true;
                exec("chmod 777 ".$fichero_respuesta);
                exec("rm ".$fichero_respuesta);
                exec("rm ".$imagen_jpg);
            }else{
                echo "El fichero NO existe<br />";
                sleep(1);
            }
        }
        echo "llego al final<br />";
        exit;
}


if(isset($_GET["info"]) and $_GET["info"]=="checkearPosicionCara"){
    $uploads_dir="files/videos_registro";
    $pos_dir="files/videos_registro_posiciones";
    $res_dir="files/videos_registro_resultados";
    
    $tmp_name = $_FILES["imagen"]["tmp_name"];
    $name = $_SESSION["local_id"];
    $posicion= $_GET["posicion"];
  
    
    $file_posicion=$pos_dir."/".$_SESSION["local_id"].".txt";
    file_put_contents($file_posicion, $posicion);
    exec("chmod 777 ".$file_posicion);

    
    $imagen="$uploads_dir/$name.png";
    $imagen_jpg="$uploads_dir/$name.jpg";
    if(move_uploaded_file($tmp_name, $imagen)){

        $image = imagecreatefrompng($imagen);
        imagejpeg($image, $imagen_jpg, 80);
        imagedestroy($image);
        exec("rm ".$imagen);
        exec("chmod 777 ".$imagen_jpg);
        
        $respuesta=0;
        
        $terminado=false;
        $fichero_respuesta=$res_dir."/".$_SESSION["local_id"].".txt";
        while(!$terminado){
            if(file_exists($fichero_respuesta)){
                $respuesta= file_get_contents($fichero_respuesta);
                $terminado=true;
                exec("chmod 777 ".$fichero_respuesta);
                exec("rm ".$fichero_respuesta);
            }else{
                sleep(1);
            }
        }
        //echo "---resp>82<---";
        echo "---resp>".$respuesta."<---";
        
    }else{
        //echo "NO subido";
        
        echo "---resp>NOOK<---";
    }
    exit;
}
