<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07/08/2020
 */

?>

<script>
    function mover_img(este,aeste){
        location.href="?page=visitantes&mode=editar&id=<?= $_GET["id"]; ?>&mover="+este+"&aeste="+aeste;
    }
    
    
   function buscar(){
       camara=document.getElementById("camara").value;
       desde=document.getElementById("desde").value;
       hasta=document.getElementById("hasta").value;
       trabajador=document.getElementById("trabajador");
       
       aux=0;
       if(document.getElementById("trabajador").checked){
        aux=1;
       }
       
       location.href='?page=visitantes&buscar=1&camara='+camara+'&desde='+desde+'&hasta='+hasta+'&trabajador='+aux;
       
   } 
   
      scalado=false;
   ultimo_escalado="";
   function scale(img,id,mode){
       alert("paso0");
       if(scalado){
           alert("paso1");
           scalado=false;
           img=document.getElementById(id);
           img.style.transform = 'scale(1)';
           if(mode==1){
            img.setAttribute("style","position:relative;left:-10px;z-index:1");    
           }else{
            img.setAttribute("style","position:relative;left:30px;top:-40px;z-index:1");       
           }
           
       }else{
           alert("paso2");
           ultimo_escalado=id;
           scalado=true;
           img.setAttribute("style","position:relative;left:-280px;z-index:99");
           img.style.transform = 'scale(10)';
       }
       
       
   }
   
   function cambiar_nombre(valor,persona_id){
       //medianbte ajax guardo el nombre mientras, muestro el iocono de cargando
            
            cargador=document.getElementById("cargador"+persona_id);
            cargador.setAttribute("style","display:inline");
            
            ajax = nuevoAjax();
            urlllamada="pages/visitantes/acciones_ajax.php?a=1&persona_id="+persona_id+"&valor="+valor;
            ajax.open("GET", urlllamada, true);
            ajax.onreadystatechange = function () {
                if (ajax.readyState == 4) {
                    
                    sleep(2000);
                    cargador.setAttribute("style","display:none");
                }
            }
            ajax.send(null);
       
   }
   
   function cambiar_trabajador(persona_id){
       
        cargador=document.getElementById("cargador2"+persona_id);
        cargador.setAttribute("style","display:inline");

       
        trabajador_edit=document.getElementById("trabajador_edit");
       
       trabajador=0;
       if(trabajador_edit.checked){
           trabajador=1;
       }else{
           trabajador=0;
       }
       
       
        ajax = nuevoAjax();
        urlllamada="pages/visitantes/acciones_ajax.php?a=2&persona_id="+persona_id+"&valor="+trabajador;
        ajax.open("GET", urlllamada, true);
        ajax.onreadystatechange = function () {
            if (ajax.readyState == 4) {

                sleep(2000);
                cargador.setAttribute("style","display:none");
            }
        }
        ajax.send(null);
       
       
   }
   
    function sleep(ms) {
      return new Promise(resolve => setTimeout(resolve, ms));
    }
    
    
    
    
    
    
    function startRecording(){
        alert("hola")
    }
    
    
    /*Para la web registrar*/
    /*
    const webCamContainer = document.getElementById("web-cam-container");
    let chunks = [];
    
    
    function startRecording(){
        const selectedMedia="vid";
    
	navigator.mediaDevices.getUserMedia(

                const MediaConstraints = {
                    audio: true,
                    video: true,
                };

		// Create a new MediaRecorder instance
		const mediaRecorder = new MediaRecorder(MediaConstraints);

		//Make the mediaStream global
		window.mediaStream = mediaStream;
		//Make the mediaRecorder global
		window.mediaRecorder = mediaRecorder;

		mediaRecorder.start();

		// Whenever (here when the recorder
		// stops recording) data is available
		// the MediaRecorder emits a "dataavailable"
		// event with the recorded media data.
		mediaRecorder.ondataavailable = (e) => {

			// Push the recorded media data to
			// the chunks array
			chunks.push(e.data);
		};

		// When the MediaRecorder stops
		// recording, it emits "stop"
		// event
		mediaRecorder.onstop = () => {

			/* A Blob is a File like object.
			In fact, the File interface is
			based on Blob. File inherits the
			Blob interface and expands it to
			support the files on the user's
			systemThe Blob constructor takes
			the chunk of media data as the
			first parameter and constructs
			a Blob of the type given as the
			second parameter*/
			const blob = new Blob(
				chunks, {
					type: selectedMedia === "vid" ?
						"video/mp4" : "audio/mpeg"
				});
			chunks = [];

			// Create a video or audio element
			// that stores the recorded media
			const recordedMedia = document.createElement("video");
			recordedMedia.controls = true;

			// You can not directly set the blob as
			// the source of the video or audio element
			// Instead, you need to create a URL for blob
			// using URL.createObjectURL() method.
			const recordedMediaURL = URL.createObjectURL(blob);

			// Now you can use the created URL as the
			// source of the video or audio element
			recordedMedia.src = recordedMediaURL;

			// Create a download button that lets the
			// user download the recorded media
			const downloadButton = document.createElement("a");

			// Set the download attribute to true so that
			// when the user clicks the link the recorded
			// media is automatically gets downloaded.
			downloadButton.download = "Recorded-Media";

			downloadButton.href = recordedMediaURL;
			downloadButton.innerText = "Download it!";

			downloadButton.onclick = () => {

				/* After download revoke the created URL
				using URL.revokeObjectURL() method to
				avoid possible memory leak. Though,
				the browser automatically revokes the
				created URL when the document is unloaded,
				but still it is good to revoke the created
				URLs */
				URL.revokeObjectURL(recordedMedia);
			};

			document.getElementById("padescargar").append(
				recordedMedia, downloadButton);
		};

		if (selectedMedia === "vid") {

			// Remember to use the srcObject
			// attribute since the src attribute
			// doesn't support media stream as a value
			webCamContainer.srcObject = mediaStream;
		}

       
        
    }
    */
    
    
</script>