<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07/08/2020
 */

?>


<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Listado Visitantes 
    </h2>
    <div class="w-full sm:w-auto flex mt-4 sm:mt-0" >
        
        Trabajadores&nbsp;<input type="checkbox" name="trabajador" id="trabajador" value="1" <?php if($_GET["trabajador"]==1){ echo "checked='checked'"; } ?>>&nbsp;&nbsp;&nbsp;
        
    Cámara:&nbsp;
    <select class="input border mr-2" id="camara" >
        <option value="-" <?php if(!isset($_GET["camara"]) or $_GET["camara"]=="-"){ echo "selected='selected'"; } ?>>Todas</option>
        <?php
        $sql->Consultar('camaras','*',"local_id=".$_SESSION["local_id"]);
        if($sql->num>0){
            do {
                echo '<option ';
                if(isset($_GET["camara"]) and $_GET["camara"]==$sql->row["id"]){ echo "selected='selected'"; } 
                echo ' value="'.$sql->row["id"].'">'.$sql->row["descripcion"].'</option>';
            }while($sql->Siguiente());
        }
        ?>
    </select>    

    <?php
    $horas=array("01"=>"13","02"=>"14","03"=>"15","04"=>"16","05"=>"17","06"=>"18","07"=>"19","08"=>"20","09"=>"21","10"=>"22","11"=>"23","12"=>"00");
            
    if(isset($_GET["desde"]) and $_GET["desde"]!=""){
        $desde=$_GET["desde"];
            
        $v_fecha= explode(" ", $desde);
        $v_fecha2= explode("/",$v_fecha[0] );
        $mes=$v_fecha2[0];
        $dia=$v_fecha2[1];
        
        $v_fecha2= explode(":",$v_fecha[1] );
        $hora=$v_fecha2[0];
        $minuto=$v_fecha2[1];
        
        $rango=$v_fecha[0];

        if($mes<10){ $mes="0".$mes; }    
        if($rango=="PM"){ $hora=$horas[$hora]; }
        
        $desde_sql=date("Y")."-".$mes."-".$dia." ".$hora.":".$minuto.':00';
        
        
    }else{
        $desde=date("n/d")." 12:01 AM";
        $desde_sql=date("Y-m-d 00:00:00");
    }
    if(isset($_GET["hasta"]) and $_GET["hasta"]!=""){
        $hasta=$_GET["hasta"];
           
        $v_fecha= explode(" ", $hasta);
        $v_fecha2= explode("/",$v_fecha[0] );
        $mes=$v_fecha2[0];
        $dia=$v_fecha2[1];
        
        $v_fecha2= explode(":",$v_fecha[1] );
        $hora=$v_fecha2[0];
        $minuto=$v_fecha2[1];
        
        $rango=$v_fecha[0];

        if($mes<10){ $mes="0".$mes; }    
        if($rango=="PM"){ $hora=$horas[$hora]; }
        
        $hasta_sql=date("Y")."-".$mes."-".$dia." ".$hora.":".$minuto.':00';
    }else{
        $hasta=date("n/d")." 12:59 PM";
        $hasta_sql=date("Y-m-d 23:59:59");
    }
    ?>
    Desde:&nbsp;<input data-timepicker="true" class="datepicker input w-56 border mx-auto" id="desde" value="<?= $desde; ?>">
    Hasta:&nbsp;<input data-timepicker="true" class="datepicker input w-56 border mx-auto" id="hasta" value="<?= $hasta; ?>">
    <button class="button text-white bg-theme-1 shadow-md mr-2" onclick="buscar()">Buscar</button>
    
    <button class="button text-white bg-theme-1 shadow-md mr-2" onclick="location.href='?page=visitantes&mode=registrar'">Registrar</button>
        
    </div>
</div>
<!-- BEGIN: Datatable -->
<div class="intro-y datatable-wrapper box p-5 mt-5">
    
    
    <table class="table table-report table-report--bordered display datatable w-full dataTable no-footer dtr-inline" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info" style="width: 792px;">
        <thead>
            <tr role="row">
                <th class="border-b-2 text-center whitespace-no-wrap sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 30%;" aria-label="IMAGES: activate to sort column ascending">IMAGEN</th>
                <th class="border-b-2 text-center whitespace-no-wrap sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 20%;" aria-label="REMAINING STOCK: activate to sort column ascending">COD_INTERNO</th>
                <th class="border-b-2 text-center whitespace-no-wrap sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 20%;" aria-label="STATUS: activate to sort column ascending">NOMBRE</th>
                <th class="border-b-2 text-center whitespace-no-wrap sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 10%;" aria-label="ACTIONS: activate to sort column ascending">ESTANCIAS</th>
            <th class="border-b-2 text-center whitespace-no-wrap sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" style="width: 20%;" aria-label="ACTIONS: activate to sort column ascending">ACCIONES</th></tr>
        </thead>
        
        <tbody>
        <?php
            if(isset($_GET["camara"]) and $_GET["camara"]!="-" and $_GET["camara"]!=""){
                $where_camara="c.id=".$_GET["camara"];
                $camara="camara_id=".$_GET["camara"];
            }else{
                $where_camara="1=1";
                $camara="camara_id in (0,";
                $tmp->Consultar("camaras","*","local_id=".$_SESSION["local_id"]);
                if($tmp->num>0){
                    do{
                       $camara.=$tmp->row["id"].","; 
                    }while($tmp->Siguiente());
                }
                $camara= substr($camara, 0,-1);
                $camara.=")";
            }
            
            $where_trabajador="";
            if($_GET["trabajador"]!="" and $_GET["trabajador"]==1){
                $where_trabajador=" and u.trabajador=1";
            }
            
            
            
            if(isset($_GET["buscador"]) and $_GET["buscador"]!=""){ //de todas las fechas de todas las camaras por nombre
                $query="select distinct(persona_id) from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c, personas u where a.camara_id=c.id and a.persona_id=u.id and (u.nombre like '%".$_GET["buscador"]."%' or u.cod_interno like '%".$_GET["buscador"]."%') order by persona_id desc";
            }else{
                $query="select distinct(persona_id) from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c , ".PREFIJO_TABLAS."personas u where a.camara_id=c.id and a.persona_id=u.id and c.local_id=".$_SESSION["local_id"]." and a.fecha_ini>='".$desde_sql."' and a.fecha_ini<='".$hasta_sql."' and ".$where_camara.$where_trabajador." order by persona_id desc";
            }
            //echo $query;
            $sql->Ejecutar($query);
            
            
        if($sql->num>0){
            $par="odd";
            do{
                
                $tmp->Consultar("personas","*","id=".$sql->row["persona_id"]);
                $cod_interno=$tmp->row["cod_interno"];
                $nombre=$tmp->row["nombre"];
                
                $tmp->Consultar("estancias","min(id) as mind","persona_id=".$sql->row["persona_id"],"id",false);
                $tmp->Consultar("fotos","min(id) as mind","estancia_id=".$tmp->row["mind"],"id",false);
                
                $imagen="./caras_procesadas/".$tmp->row["mind"].".jpg";
                
                
                $tmp->Consultar("estancias","count(*) as veces","persona_id=".$sql->row["persona_id"]." and ".$camara);
                $veces=$tmp->row["veces"];
                
        ?>
            
        <tr role="row" class="<?= $par; ?>" 
            <?php
            if($sql->row["persona_id"]==$_GET["unir"] and $_GET["unir"]!=""){
                echo "style='background-color:yellow'";
            }
            ?>
            >
                <td class="text-center border-b">
                    <div class="flex sm:justify-center">
                        <div class="intro-x w-10 h-10 image-fit">
                            <img alt="" id="<?= $imagen; ?>" onclick="scale(this,this.id,1) class="" src="<?= $imagen ?>">
                        </div>
                        
                    </div>
                </td>
                
            
                <td class="border-b sorting_1" tabindex="0" align="center">
                    <div class="font-medium whitespace-no-wrap"><?= $cod_interno; ?></div>
                    <!--<div class="text-gray-600 text-xs whitespace-no-wrap">Apple MacBook Pro 13</div>-->
                </td>
                <td class="border-b sorting_1" tabindex="0" align="center">
                    <div class="font-medium whitespace-no-wrap">
                        <input type="text" value="<?= $nombre; ?>" onblur="cambiar_nombre(this.value,<?= $sql->row["persona_id"]; ?>)" style="width:75%;<?php
            if($par!="odd"){
                echo "border-style:solid;border-width:1px;border-color:#EDF2F7";
            }           
                        ?>">
                        <span style="display:none" id="cargador<?= $sql->row["persona_id"]; ?>">
                        <i data-loading-icon="spinning-circles" class="w-8 h-8"  ></i>
                        </span>
                        
                    </div>
                </td>
                
                <td class="text-center border-b" align="center"><?= $veces; ?></td>
                

                <td class="border-b w-5">
                    <div class="flex sm:justify-center items-center">
                        <a class="flex items-center mr-3" href="?page=visitantes&mode=editar&id=<?= $sql->row["persona_id"]; ?>"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-square w-4 h-4 mr-1"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg> Ver </a>
                        
                        <a class="flex items-center mr-3" href="?page=accesos&persona_id=<?= $sql->row["persona_id"]; ?>"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-square w-4 h-4 mr-1"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg> Movimientos </a>
                        
                        <a class="flex items-center mr-3" href="?page=rutas&persona_id=<?= $sql->row["persona_id"]; ?>"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-square w-4 h-4 mr-1"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg> Rutas </a>
                        
                        
                        <?php
                        
                        
                                
                                
                            if(!isset($_GET["unir"])){
                                $txt="Unir";
                                $enlace="&unir=".$sql->row["persona_id"]."&camara=".$_GET["camara"]."&desde=".$_GET["desde"]."&hasta=".$_GET["hasta"]."&trabajador=".$_GET["trabajador"];
                            }else{
                                $txt="Con este";
                                $enlace="&este=".$_GET["unir"]."&coneste=".$sql->row["persona_id"];
                            }
                            
                            ?>
                        
                        
                        <a class="flex items-center mr-3" href="?page=visitantes<?= $enlace; ?>"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-check-square w-4 h-4 mr-1"><polyline points="9 11 12 14 22 4"></polyline><path d="M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"></path></svg> 
                                <?= $txt; ?>
                             </a>

                    </div>
                </td>
        </tr>
        <?php    
            if($par=="odd"){
                $par="pair";
            }else{
               $par="odd";
            }
            }while($sql->Siguiente());
        }    
        ?>

            
            
        </tbody>
    </table>            </div>
<!-- END: Datatable -->



<?php
if(isset($_GET["unir"])){
?>
<div style="width:500px;height:220px;background-color:white;position:fixed;left:50%;margin-left: -250px; top:10px;z-index:999;border-radius:20px;padding:20px">
    <?php
    $sql->Consultar('personas','*',"id=".$_GET["unir"]);
    
    $cod_interno=$sql->row["cod_interno"];
    $nombre=$sql->row["nombre"];

    $tmp->Consultar("estancias","min(id) as mind","persona_id=".$sql->row["id"],"id",false);
    $tmp->Consultar("fotos","min(id) as mind","estancia_id=".$tmp->row["mind"],"id",false);

    $imagen="./caras_procesadas/".$tmp->row["mind"].".jpg";
    
    ?>
    <table style="width:100%;height:100%">
        <tr style="background-color:cyan"><td colspan="2" align="center"><b>Unir usuario</b> <i>(Selecciona con quien)</i></td></tr>
        <tr>
            <td style="width:60%"><img src="<?= $imagen ?>" style="height:100%"></td>
            <td style="width:40%" valign="top"><?= $cod_interno ?><br /><?= $nombre ?></td>
        </tr>
    </table>
</div>
<?php
}

?>
