<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 21-jul-2022, 13:18:08.
 */
                
?>

<div class="intro-y flex items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Registrar nuevo usuario
    </h2>
</div>

<div class="intro-y box px-5 pt-5 mt-5">
    <div class="flex flex-col lg:flex-row border-b border-gray-200 dark:border-dark-5 pb-5 -mx-5">
        <div class="flex flex-1 px-5 items-center justify-center lg:justify-start">
                <table style="width:100%">
                    <tr><td>
                        Nombre:&nbsp;<input type="text" name="nombre" id="nombre" placeholder="Nombre" style="border-color:blue;border-style:solid;border-width:2px;border-radius:15px;width:70%">
                    </td></tr>
                    
                    <tr><td align="center">
                        <button class="button text-white bg-theme-1 shadow-md mr-2" onclick="startRecording()">Empezar a capturar</button>
                        <button class="button text-white bg-theme-1 shadow-md mr-2" onclick="stopRecording()">Parar captura</button>
                    </td></tr>
                
                    
                    <tr><td align="center">
                            <div id="webcam" ></div>        
                            
                            
                            
                            <video autoplay id="web-cam-container" 
                                style="background-color: black;width: 70%;height:800px;border-color:blue;border-style:solid;border-width:2px;">
                                Your browser doesn't support 
                                the video tag
                            </video>
                            
                            <span id="padescargar"></span>
                            
                    </td></tr>        
        </div>
        
        
       
        
    </div>
</div>


