<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 21-jul-2022, 13:18:08.
 */

?>

<div class="intro-y flex items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Registrar nuevo usuario
    </h2>
</div>

<div class="intro-y box px-5 pt-5 mt-5">
    <div class="flex flex-col lg:flex-row border-b border-gray-200 dark:border-dark-5 pb-5 -mx-5">
        <div class="flex flex-1 px-5 items-center justify-center lg:justify-start">
                <table style="width:100%">
                    <tr><td>
                        Nombre:&nbsp;<input type="text" name="nombre" id="nombre" placeholder="Nombre" style="border-color:blue;border-style:solid;border-width:2px;border-radius:15px;width:70%">
                    </td></tr>
                    
                    <tr><td align="center">
                        <button id="btn_grabar" class="button text-white bg-theme-1 shadow-md mr-2" onclick="grabarParar()">Empezar a capturar</button>
                        
                        
                        <button id="btn_pruebas" class="button text-white bg-theme-1 shadow-md mr-2" onclick="pruebaAjax()">Pruebas</button>
                        
                    </td></tr>
                
                   
                    <tr><td align="center">
                            
                            <table style="width:100%" border="1"><tr>
                            
                            <td style="width:50%">
                                <video autoplay id="web-cam-container" 
                                    style="background-color: black;width: 100%;height:800px;border-color:blue;border-style:solid;border-width:2px; transform: rotateY(180deg); -webkit-transform:rotateY(180deg); -moz-transform:rotateY(180deg);">
                                    Your browser doesn't support 
                                    the video tag
                                </video>

                                <span id="padescargar"></span>
                            </td>
                            <td>
                                <img src="" id="sigueme" style="width:100%">
                                <center><span id="textocabeza" style="text-align:center;font-size:25px;width:100%;color:blue;font-weight:bold;border-color:blue;border-style:solid;border-width:2px;padding:10px"></span></center>
                            </td>
                            
                            
                            </tr></table>
                            
                    </td></tr>        
        </div>
        
        
       
        
    </div>
</div>



<script>
    const webCamContainer = document.getElementById("web-cam-container");
    
    let chunks = [];
    var mode="start";
    const selectedMedia="vid";
    const audioMediaConstraints = {
            audio: true,
            video: false,
    };
    const videoMediaConstraints = {
            audio: true,
            video: true,
    };
    
    function grabarParar(){
        //alert("grabar_o_parar");
        if(mode=="start"){
            mode="stop";
            document.getElementById("btn_grabar").innerHTML="Detener la Captura";
            //sigueme();
            startRecording();
        }else{ //mode=="stop"
            mode="stop";
            document.getElementById("btn_grabar").innerHTML="Empezar a capturar";
            stopRecording();
        }
        
    }
    
    
    var cabeza=1;
    function cabezon(posicion){
        
        style="background-color: black;width: 100%;height:800px; transform: rotateY(180deg); -webkit-transform:rotateY(180deg); -moz-transform:rotateY(180deg);";
        style+="border-left:  5px solid red;";
        style+="border-top:    5px solid red;";
        style+="border-right:  5px solid red;";
        style+="border-bottom: 5px solid red;";
        webCamContainer.setAttribute("style",style);
        
        switch(posicion){
            case 1:
                texto="Ponga la cabeza de frente";
                imagen="01-front-Head-set.jpg";
                break;
            case 2:
                texto="Gira 2..";
                imagen="02-right-Head-set.jpg";
                break;
            case 3:
                texto="Gira3 ..";
                imagen="03-right-Head-set.jpg";
                break;
            case 4:
                texto="Gira4..";
                imagen="04-left-Head-set.jpg";
                break;
            case 5:
                texto="Gira5..";
                imagen="05-left-Head-set.jpg";
                break;
            case 6:
                texto="Gira6..";
                imagen="06-up-Head-set.jpg";
                break;
            case 7:
                texto="Gira7..";
                imagen="07-down-Head-set.jpg";
                break;
            default:
                alert("Esto no puede pasar");
                break;
        }
          
        document.getElementById("sigueme").setAttribute("src","files/images/" + imagen);
        document.getElementById("textocabeza").innerHTML=texto;
        
    }
    
    /*
    sigue=1;
    function sigueme(){
        document.getElementById("sigueme").setAttribute("src","files/images/" + sigue + ".png");
        sigue=sigue+1;
        
        if(sigue<=12){
            tiempo=3000;
            if(sigue<=5){
                tiempo=1000;    
            }
            setTimeout(sigueme, tiempo);
            
        }else{
            
        }

    }
    */
    
    let subidor_caras=true;
    
    function startRecording(){
        //
        
        if(document.getElementById("nombre").value==""){
            alert("Rellena el nombre del usuario a registrar");
        }else{
        
        
        
            navigator.mediaDevices.getUserMedia(
                    selectedMedia === "vid" ?
                    videoMediaConstraints :
                    audioMediaConstraints)
                    .then((mediaStream) => {
                        
                    cabezon(cabeza);
                    
                    // Create a new MediaRecorder instance
                    const mediaRecorder = new MediaRecorder(mediaStream);

                    //Make the mediaStream global
                    window.mediaStream = mediaStream;
                    //Make the mediaRecorder global
                    window.mediaRecorder = mediaRecorder;

                    mediaRecorder.start();


                    setTimeout(subeCaras, 1000);

                    
                    
                    let blob;
                    // When the MediaRecorder stops
                    // recording, it emits "stop"
                    // event
                    //mediaRecorder.onstop = () => {
                    mediaRecorder.onstop = async () => {

                            blob = new Blob(
                                    chunks, {
                                            type: selectedMedia === "vid" ?
                                                    "video/mp4" : "audio/mpeg"
                                    });
                            chunks = [];

                            // Create a video or audio element
                            // that stores the recorded media
                            const recordedMedia = document.createElement("video");
                            recordedMedia.controls = true;

                            // You can not directly set the blob as
                            // the source of the video or audio element
                            // Instead, you need to create a URL for blob
                            // using URL.createObjectURL() method.
                            const recordedMediaURL = URL.createObjectURL(blob);

                            // Now you can use the created URL as the
                            // source of the video or audio element
                            recordedMedia.src = recordedMediaURL;




                            // Create a download button that lets the
                            // user download the recorded media
                            const downloadButton = document.createElement("a");

                            // Set the download attribute to true so that
                            // when the user clicks the link the recorded
                            // media is automatically gets downloaded.
                            downloadButton.download = "Recorded-Media";

                            downloadButton.href = recordedMediaURL;
                            //downloadButton.innerText = "Download it!";

                            downloadButton.onclick = () => {
                                    URL.revokeObjectURL(recordedMedia);
                            };

                            //document.getElementById("padescargar").append(recordedMedia, downloadButton);
                            //alert(recordedMediaURL + "---" + document.getElementById("nombre").value);

                            //downloadButton.click();
                            //recordedMediaURL


/*
                            for(i=0;i<5;i++){
                                console.log("LISTO(" + i + "):" + blob.size);
                                await sleep(2000);
                            }
*/                            
                            subidor_caras=false;
                            
                            var fd = new FormData();
                            fd.append("video",blob);
                            //fd.append("video2",recordedMediaURL);
                            var request = new XMLHttpRequest();
                            request.open("POST", "<?= URL_PROGRAMA_SERVER ?>admin/index.php?page=visitantes&mode=registrar&info=subir_video&nombre=" + document.getElementById("nombre").value);
                            request.send(fd);

                            //aki habria que hacer overlay que se muestre como procesando asta que que consultas ajax recibir respuesta 
                            //del procesardor del video que es: procesa_video_registro.php
                    };


                    // Whenever (here when the recorder
                    // stops recording) data is available
                    // the MediaRecorder emits a "dataavailable"
                    // event with the recorded media data.
                    mediaRecorder.ondataavailable = (e) => {

                            // Push the recorded media data to
                            // the chunks array
                            chunks.push(e.data);
                            
                            
                            

                    };

                    if (selectedMedia === "vid") {

                        // Remember to use the srcObject
                        // attribute since the src attribute
                        // doesn't support media stream as a value
                        webCamContainer.srcObject = mediaStream;

                        
                    }

            });
        }
    }



    function stopRecording() {

            // Stop the recording
            window.mediaRecorder.stop();

            // Stop all the tracks in the
            // received media stream
            window.mediaStream.getTracks()
            .forEach((track) => {
                    track.stop();
            });

            //document.getElementById("padescargar").innerText = "Recording done!";
            
            subidor_caras=false;
    }


    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
    
    
    
    let contadorCaras=0;
    function subeCaras(){
        if(subidor_caras){
            contadorCaras++;
            console.log(contadorCaras);
            if(contadorCaras==2){
                //alert("Voy a allamar a checkearPosicionCara");
                checkearPosicionCara(cabeza);
                //alert("llamado y analizado checkearPosicionCara!")
                contadorCaras=0;
            }
            setTimeout(subeCaras, 1000);
        }
    }
    
    
    function checkearPosicionCara(posicion){
        
        
        
        const canvas = document.createElement("canvas");
        const ctx = canvas.getContext("2d");

        
        canvas.height = webCamContainer.videoHeight;
        canvas.width = webCamContainer.videoWidth;
        ctx.drawImage(webCamContainer, 0, 0);
        
        console.log("checkearPosicionCara1");
        canvas.toBlob(blob=> {
            console.log("checkearPosicionCara2");
            
            console.log(blob);
            
            console.log("checkearPosicionCara3");
            
            var fd = new FormData();
            fd.append("imagen",blob,"imagen");
            //fd.append("video2",recordedMediaURL);
            var request = new XMLHttpRequest();
            
            request.open("POST", "index.php?page=visitantes&mode=registrar&info=checkearPosicionCara&posicion=" + posicion+"&debug=1", false);
            request.setRequestHeader('Content-Type', 'multipart/form-data');
            request.send(fd);
            
            
            console.log("checkearPosicionCara4");
            
            request.onreadystatechange = () => {
                console.log("checkearPosicionCara5");
                
                if (request.readyState === 4) {
                  console.log("checkearPosicionCara6");
                    
                  //alert(request.response);
                  respuesta=request.response;
                  posicion=respuesta.indexOf("---resp>");
                  respuesta=respuesta.substr(posicion+8);
                  posicion=respuesta.indexOf("<---");
                  respuesta=respuesta.substr(0,posicion);
                  //alert("Dentro de checar caras, la respuesta obtenida es:"+respuesta);
                  
                  interpretaRespuesta(respuesta);
                  
                }
              }
            request.onerror = function (err) {
                console.error('Error uploading file  to server')
                console.error(err)
                if (typeof callback === 'function') { callback(err) }
              }  
            
            console.log("checkearPosicionCara7");
            
            //request.open("POST", "<?= URL_PROGRAMA_SERVER ?>admin/index.php?page=visitantes&mode=registrar&info=checkearPosicionCara&posicion=" + posicion+"&debug=1", false);

            //request.send();
            
            console.log("checkearPosicionCara8");
            
            
        });
        
  
    }
    
    

    
    async function interpretaRespuesta(respuesta){

       console.log("interpretaRespuesta:"+respuesta);

        style="background-color: black;width: 100%;height:800px; transform: rotateY(180deg); -webkit-transform:rotateY(180deg); -moz-transform:rotateY(180deg);";
        if(respuesta=="NOOK"){
            style+="border-color:red;border-style:solid;border-width:5px";

        }else{
            console.log("Voy a analizar");
            //alert(respuesta);
            resp=parseInt(respuesta);

            //if(resp>=80 && resp<85){
            if(resp>=50 && resp<60){
                console.log("paso1");
                style+="border-left:  5px solid red;";
                style+="border-top:    5px solid red;";
                style+="border-right:  7px solid green;";
                style+="border-bottom: 5px solid red;";
            //}else if(resp>=85 && resp<90){
            }else if(resp>=60 && resp<70){
                console.log("paso2");
                style+="border-left:  5px solid red;";
                style+="border-top:    7px solid green;";
                style+="border-right:  7px solid green;";
                style+="border-bottom: 5px solid red;";
            //}else if(resp>=90 && resp<95){
            }else if(resp>=70 && resp<80){
                console.log("paso3");
                style+="border-left:  7px solid green;";
                style+="border-top:    7px solid green;";
                style+="border-right:  7px solid green;";
                style+="border-bottom: 5px solid red;";
            //}else if(resp>=95 && resp<=100){
            }else if(resp>=80){
                console.log("reconocido!!!!!!!!!");
                style+="border-left:  7px dotted green;";
                style+="border-top:    7px dotted green;";
                style+="border-right:  7px dotted green;";
                style+="border-bottom: 7px dotted green;";
                cabeza++;
                console.log("la siguiebte cabeza es:"+cabeza);
                if(cabeza<=7){
                    console.log("voy a llamar al siguiente cabezon");
                    await sleep(2000);
                    cabezon(cabeza);
                }else{
                    alert("Voy a parar");
                    stopRecording();
                }
            //}else if(resp>=60 && resp<80){
            }else if(resp>=40 && resp<50){
                console.log("paso5");
                style+="border-left:  5px solid red;";
                style+="border-top:    5px solid red;";
                style+="border-right:  5px solid red;";
                style+="border-bottom: 5px solid red;";
            }else{
                console.log("paso6");
                style+="border-left:  7px solid red;";
                style+="border-top:    7px solid red;";
                style+="border-right:  7px solid red;";
                style+="border-bottom: 7px solid red;";
            }
            console.log("analziado1");
        }
        webCamContainer.setAttribute("style",style);
        console.log("analziado2");
        
    }

//

    function pruebaAjax(){
        console.log("pruebaAjax1");
        var request = new XMLHttpRequest();
        console.log("pruebaAjax2");

        
        request.onprogress = () => {
            console.log('LOADING', request.readyState); // readyState will be 3
        };

        request.onreadystatechange = () => {
            console.log("pruebaAjax3:" + request.readyState);
            if (request.readyState === 4) {
              alert(request.response);
              console.log("pruebaAjax4");

            }
          }
        console.log("pruebaAjax5");

        //tcmd="<?= URL_PROGRAMA_SERVER ?>admin/index.php?page=visitantes&mode=registrar&info=pruebaAjax&debug=1";
        tcmd="index.php?page=visitantes&mode=registrar&info=pruebaAjax&debug=1";
        console.log("pruebaAjax21:" + tcmd);
        request.open("GET", tcmd, false);
        console.log("pruebaAjax22");
        request.send();
        console.log("pruebaAjax223");
        
        
        
    }


</script>

