<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 07-jul-2021, 13:04:37.
 */

class Jos_Thread{
    
    var $id;
    var $comando;
    var $identificador_unico;
    var $process_id;
    var $file_aux;
    var $debug;
    var $tiempo_inicial;
    function __construct($id="0",$comando="",$debug=false){
        $this->id=$id;
        $this->comando=$comando;
        $this->identificador_unico=$this->crearIdentificador();
        $this->file_aux="libs/threads_files_aux/aux_".$this->id.".txt";
        $this->debug=$debug;
        $this->tiempo_inicial = microtime(true);
        
        if($this->debug){ echo "Hilo creado con identificador unico:".$this->identificador_unico."\n"; }
        if($this->debug){ echo "El file aux es:".$this->file_aux."\n"; }
        
    }
    function start(){
        $cmd=$this->comando.' '.$this->identificador_unico.' > /dev/null &';
        if($this->debug){ echo "start cmd:".$cmd."\n"; }
        
        exec($cmd);
        
        $this->vuelca_procesos();
        $archivo = fopen($this->file_aux,'r');
        $encontrado=false;
        while ($linea = fgets($archivo) and !$encontrado) {
            $pos= strpos($linea, $this->identificador_unico);
            if($pos!==false){
                
                $vaux= explode(" ", $linea);
                
                $contador=0;
                for($i=0;$i<count($vaux);$i++){
                    if($vaux[$i]!=""){
                        $contador++;
                    }
                    if($contador==2){
                        $this->process_id=$vaux[$i];
                        break;
                    }
                }
                if($this->debug){ echo "El process id del proceso es:".$this->process_id."\n";  }
                $encontrado=true;
            }
        }
        fclose($archivo);
        if($this->debug){ echo "Hilo starteado\n"; }
        //exit;
    }
    function stop(){
        if($this->debug){ echo "Voy a matar un proceso:".$this->process_id."\n"; }
        $cmd="kill -9 ".$this->process_id;
        if($this->debug){ echo $cmd."\n"; }
        exec($cmd);
        if($this->debug){ echo "Hilo parado\n"; }
    }
    function isrunning(){
        $running=false;
        $this->vuelca_procesos();
        $aux= file_get_contents($this->file_aux);
        $vaux= explode(" ", $aux);
        for($i=0;$i<count($vaux);$i++){
            $pos= strpos($vaux[$i], $this->identificador_unico);
            if($pos!==false){
                $running=true;
                break;
            }
        }
        return $running;
    }
    function crearIdentificador(){
        $codigos=[
            "a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",
            "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z",
            "0","1","2","3","4","5","6","7","8","9"
        ];
        $repetido=true;
        while($repetido){
            $codigo="";
            for($i=0;$i<12;$i++){
                $codigo.=$codigos[rand(0,count($codigos)-1)];
            }
            
            $this->vuelca_procesos();
            $aux= file_get_contents($this->file_aux);
            $vaux= explode(" ", $aux);
            $repetido=false;
            for($i=0;$i<count($vaux);$i++){
                $pos= strpos($vaux[$i], $codigo);
                if($pos!==false){
                    $repetido=true;
                    break;
                }
            }
        }
        return $codigo;
    }

    function vuelca_procesos(){
        $cmd1="ps aux > ".$this->file_aux;
        $cmd2="chmod -R 777 ".$this->file_aux;
        if($this->debug){ echo "vuelca_procesos1:".$cmd1."\n"; }
        if($this->debug){ echo "vuelca_procesos2:".$cmd2."\n"; }
        exec($cmd1);
        exec($cmd2);
    }
    
    
    function queda_ram($umbral=80){
        $queda=false;
        
        $file_aux="libs/threads_files_aux/ram.txt";
        exec("free > ".$file_aux);
        
        $handle = fopen($file_aux, "r");
        if ($handle) {
            $linea=0;
            while (($line = fgets($handle)) !== false) {
                $linea++;
                if($linea==2){
                    $aux= explode(" ", $line);
                    $campos=[];
                    for($i=0;$i<count($aux);$i++){
                        if($aux[$i]!=""){
                            $campos[]=$aux[$i];
                        }
                    }
                    $memoria_total= intval(trim($campos[1]));
                    //echo "memoria_total:".$memoria_total."\n";
                    $memoria_ocupada=intval(trim($campos[2]))+intval(trim($campos[4]));
                    //echo "memoria_ocupada:".$memoria_ocupada."\n";
                    $maximo_permitido=$memoria_total*$umbral/100;
                    //echo "maximo_permitido:".$maximo_permitido."\n";
                    if($memoria_ocupada<$maximo_permitido){
                        $queda=true;
                    }
                    //var_dump($campos);
                }
            }

            fclose($handle);
        } else {
            echo "error opening the file RAM\n.";
        } 
        
        return $queda;
        
    }
    
    
    function test_ram(){
        while(!$this->queda_ram()){
            echo "Esperando.. no queda ram...\n";
            sleep(5);
        }

    }
    
    function queda_espacio(){
        
        $queda=true;
        $identificador_linea="sda1";
        
        $file_aux="libs/threads_files_aux/dfh.txt";
        exec("df -h > ".$file_aux);
        
        $handle = fopen($file_aux, "r");
        if ($handle) {
            while (($line = fgets($handle)) !== false) {
                $aux= explode(" ", $line);
                $campos=[];
                for($i=0;$i<count($aux);$i++){
                    if($aux[$i]!=""){
                        $campos[]=$aux[$i];
                    }
                }
                $disponible= str_replace("G", "", $campos[3]);
                        
                if($disponible<10){
                    $queda=false;
                }
            }

            fclose($handle);
        } else {
            echo "error opening the file RAM\n.";
        } 
        
        return $queda;
        
        
    }
    
    function libera_espacio(){
        $directorios=[
            "/home/testuser/motor/videos/1/1/",
            "/home/testuser/motor/videos/1/2/",
            "/home/testuser/motor/videos/1/3/",
            "/home/testuser/motor/videos/1/4/",
            "/home/testuser/motor/videos/1/5/",
            "/home/testuser/motor/videos/2/6/",
            "/home/testuser/motor/videos/2/7/",
            "/home/testuser/motor/videos/2/8/",
            "/home/testuser/motor/videos/2/9/"
        ];
        for($i=0;$i<count($directorios);$i++){
            $this->recorre_y_libera($directorios[$i]);
        }
    }
    
    function recorre_y_libera($directorio){
        $videos=[];
        $dir = opendir($directorio);
        while ($elemento = readdir($dir)){
            if( $elemento != "." && $elemento != ".."){
                $videos[]=$elemento;
            }
        }
        if(count($videos)>15){
            asort($videos);
            for($i=5;$i<15;$i++){
                exec("rm ".$directorio.$videos[$i]);
            }
        }
    }
    
}


