<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 18/08/2020
 */


switch($_GET["accion"]){
    case "cambiar_aforo":
        $sql->Actualizar("locales",["aforo_actual"],[$_GET["nuevo_aforo"]],"id=".$_SESSION["local_id"]);
        break;
}

