<?php

/* 
 * Generated by Nou Esmalt
 * Author: Josué García Juan
 * 17/08/2020
 */


$aforo_actual=0;
$visitas_hoy=0;
$visitas_medias_diarias=0;
$visitantes_recurrentes=0;



$aforo_actual=0;
//el aforo del local a pelo
$sql->Consultar("locales","aforo_actual","id=".$_SESSION["local_id"]);
$aforo_actual=$sql->row["aforo_actual"];


$visitas_hoy=0;
$sql->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00")."' and a.created<='".date("Y-m-d 23:59:59")."'");
$visitas_hoy=$sql->row["cuenta"];


$visitas_medias_diarias=0;
$sql->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." GROUP BY year(a.created), month(a.created), day(a.created)", false, false);
$totales=0;
$count=0;
if($sql->num>0){
    do{
        $totales+=$sql->row["cuenta"];
        $count++;
    }while($sql->Siguiente());
}
$visitas_medias_diarias=round($totales/$count);



$sql->Ejecutar("select a.persona_id as person, a.fecha_ini lafecha from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]);

$visitantes_recurrentes=0;
if($sql->num>0){
    do{
        $tmp->Consultar("estancias","id","persona_id=".$sql->row["person"]);
        $primera=true;
        if($tmp->num>0){
            do{
                $aux= explode(" ", $tmp->row["lafecha"]);
                $fecha=$aux[0];
                if($primera){
                    $primera=false;
                    $fecha_inicial=$fecha;
                }else{
                    if($fecha!=$fecha_inicial){
                        $visitantes_recurrentes++;
                        break;
                    }
                }
            }while($tmp->Siguiente());
        }
        
    }while($sql->Siguiente());
}

?>

<div class="col-span-12 mt-8">
    <div class="intro-y flex items-center h-10">
        <h2 class="text-lg font-medium truncate mr-5">
            Reporte General
        </h2>
        <a href="?page=dash" class="ml-auto flex text-theme-1 dark:text-theme-10"> <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-refresh-ccw w-4 h-4 mr-3"><polyline points="1 4 1 10 7 10"></polyline><polyline points="23 20 23 14 17 14"></polyline><path d="M20.49 9A9 9 0 0 0 5.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 0 1 3.51 15"></path></svg> Recargar Datos </a>
    </div>
    <div class="grid grid-cols-12 gap-6 mt-5">
        <div class="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
            <div class="report-box zoom-in">
                <div class="box p-5">
                    <div class="flex">
                        <div class="menu__icon" data-feather="box" style="color:orange"></div>
                        
                        <div class="ml-auto">
                            <!--
                            <div class="report-box__indicator bg-theme-9 tooltip cursor-pointer tooltipstered"> 33% <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-up w-4 h-4"><polyline points="18 15 12 9 6 15"></polyline></svg> </div>
                            -->
                            <input type="text" name="aforo_input" id="aforo_input" style="background-color:#F0F4F7;width:100px" placeholder="<?= $aforo_actual; ?>">
                            <button class="button text-white bg-theme-1 shadow-md mr-2" onclick="cambiar_aforo()">Actualizar</button>    
                            
                        </div>
                    </div>
                    <div class="text-3xl font-bold leading-8 mt-6"><?= $aforo_actual; ?></div>
                    <div class="text-base text-gray-600 mt-1">Aforo Actual</div>
                </div>
            </div>
        </div>
        <div class="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
            <div class="report-box zoom-in">
                <div class="box p-5">
                    <div class="flex">
                        <div class="menu__icon" data-feather="codepen" style="color:green"></div>
                        <div class="ml-auto">
                            <!--
                            <div class="report-box__indicator bg-theme-6 tooltip cursor-pointer tooltipstered"> 2% <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down w-4 h-4"><polyline points="6 9 12 15 18 9"></polyline></svg> </div>
                            -->
                        </div>
                    </div>
                    <div class="text-3xl font-bold leading-8 mt-6"><?= $visitas_hoy; ?></div>
                    <div class="text-base text-gray-600 mt-1">Visitas Hoy</div>
                </div>
            </div>
        </div>
        <div class="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
            <div class="report-box zoom-in">
                <div class="box p-5">
                    <div class="flex">
                        <div class="menu__icon" data-feather="copy" style="color:purple"></div>
                        <div class="ml-auto">
                            <!--
                            <div class="report-box__indicator bg-theme-9 tooltip cursor-pointer tooltipstered"> 12% <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-up w-4 h-4"><polyline points="18 15 12 9 6 15"></polyline></svg> </div>
                            -->
                        </div>
                    </div>
                    <div class="text-3xl font-bold leading-8 mt-6"><?= $visitas_medias_diarias; ?></div>
                    <div class="text-base text-gray-600 mt-1">Visitas Medias Diarias</div>
                </div>
            </div>
        </div>
        <div class="col-span-12 sm:col-span-6 xl:col-span-3 intro-y">
            <div class="report-box zoom-in">
                <div class="box p-5">
                    <div class="flex">
                        <div class="menu__icon" data-feather="monitor" style="color:red"></div>
                        <div class="ml-auto">
                            <!--
                            <div class="report-box__indicator bg-theme-9 tooltip cursor-pointer tooltipstered"> 22% <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-up w-4 h-4"><polyline points="18 15 12 9 6 15"></polyline></svg> </div>
                            -->
                        </div>
                    </div>
                    <div class="text-3xl font-bold leading-8 mt-6"><?= $visitantes_recurrentes; ?></div>
                    <div class="text-base text-gray-600 mt-1">Visitantes Recurrentes</div>
                </div>
            </div>
        </div>
    </div>
</div>


<!------------------------------------------>


<div class="col-span-12 lg:col-span-6 mt-8">
    <div class="intro-y block sm:flex items-center h-10">
        <h2 class="text-lg font-medium truncate mr-5">
            Gráfico Visitas 
            <?php
            switch($_GET["filtro"]){
                case "dia":
                    echo "hoy";
                    $txt1="Hoy";
                    $txt2="Ayer";
                    
                    $sql->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00")."' and a.created<='".date("Y-m-d 23:59:59")."'",false,false);
                    
                    $tmp->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00",strtotime("-1 days"))."' and a.created<='".date("Y-m-d 23:59:59",strtotime("-1 days"))."'",false,false);
                    
                    break;
                case "semana":
                    echo "esta semana";
                    $txt1="Esta semana";
                    $txt2="Semana pasada";
                    
                    $sql->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00",strtotime("monday this week"))."' and a.created<='".date("Y-m-d 23:59:59",strtotime("sunday this week"))."'",false,false);
                    
                    $tmp->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00",strtotime("monday last week"))."' and a.created<='".date("Y-m-d 23:59:59",strtotime("sunday last week"))."'",false,false);
                    
                    break;
                case "mes":
                    echo "este mes";
                    $txt1="Este mes";
                    $txt2="Mes pasado";
                    
                    $sql->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00",strtotime("first day of this month"))."' and a.created<='".date("Y-m-d 23:59:59",strtotime("last day of this month"))."'",false,false);
                    
                    $tmp->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00",strtotime("first day of previous month"))."' and a.created<='".date("Y-m-d 23:59:59",strtotime("last day of previous month"))."'",false,false);
                    
                    break;
                case "anyo":
                    echo "este año";
                    $txt1="Este año";
                    $txt2="Año pasado";
                    
                    $sql->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-01-01 00:00:00")."' and a.created<='".date("Y-12-31 23:59:59")."'",false,false);
                    
                    $tmp->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-01-01 00:00:00",strtotime("-1 year"))."' and a.created<='".date("Y-12-31 23:59:59",strtotime("-1 year"))."'",false,false);
                    
                    break;
                default:
                    echo "este mes";
                    $txt1="Este mes";
                    $txt2="Mes pasado";
                    
                    $sql->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00",strtotime("first day of this month"))."' and a.created<='".date("Y-m-d 23:59:59",strtotime("last day of this month"))."'",false,false);
                    
                    $tmp->Ejecutar("select distinct(count(a.persona_id)) as cuenta from ".PREFIJO_TABLAS."estancias a, ".PREFIJO_TABLAS."camaras c,".PREFIJO_TABLAS."personas p where a.camara_id=c.id and p.id=a.persona_id and p.trabajador=0 and c.puerta=1 and c.local_id=".$_SESSION["local_id"]." and a.created>='".date("Y-m-d 00:00:00",strtotime("first day of previous month"))."' and a.created<='".date("Y-m-d 23:59:59",strtotime("last day of previous month"))."'",false,false);
                    
                    break;
            }
            $txt1_1=$sql->row["cuenta"];
            $txt2_2=$tmp->row["cuenta"];
            
            ?>
            
        </h2>
        
        <!--
        <div class="sm:ml-auto mt-3 sm:mt-0 relative text-gray-700 dark:text-gray-300">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar w-4 h-4 z-10 absolute my-auto inset-y-0 ml-3 left-0"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg> 
            <input type="text" data-daterange="true" class="datepicker input w-full sm:w-56 box pl-10">
        </div>
        -->
        
    </div>
    <div class="intro-y box p-5 mt-12 sm:mt-5">
        <div class="flex flex-col xl:flex-row xl:items-center">
            <div class="flex">
                <div>
                    <div class="text-theme-20 dark:text-gray-300 text-lg xl:text-xl font-bold" id="datos_actual"><?= $txt1_1; ?></div>
                    <div class="text-gray-600 dark:text-gray-600" id="etiqueta_actual"><?= $txt1; ?></div>
                </div>
                <div class="w-px h-12 border border-r border-dashed border-gray-300 dark:border-dark-5 mx-4 xl:mx-6"></div>
                <div>
                    <div class="text-gray-600 dark:text-gray-600 text-lg xl:text-xl font-medium" id="datos_pasado"><?= $txt2_2; ?></div>
                    <div class="text-gray-600 dark:text-gray-600" id="etiqueta_pasado"><?= $txt2; ?></div>
                </div>
            </div>
            <div class="dropdown relative xl:ml-auto mt-5 xl:mt-0">
                <button class="dropdown-toggle button font-normal border dark:border-dark-5 text-white dark:text-gray-300 relative flex items-center text-gray-700"> Elegir periodo <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down w-4 h-4 ml-2"><polyline points="6 9 12 15 18 9"></polyline></svg> </button>
                
                
                <div class="dropdown-box mt-10 absolute w-40 top-0 xl:right-0 z-20">
                    <div class="dropdown-box__content box dark:bg-dark-1 p-2 overflow-y-auto h-32"> 
                        
                        
                        <a href="?page=dash&filtro=dia" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md">Un dia</a> 
                        <a href="?page=dash&filtro=semana" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md">Una semana </a> 
                        <a href="?page=dash&filtro=mes" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md">Un mes</a> 
                        <a href="?page=dash&filtro=anyo" class="flex items-center block p-2 transition duration-300 ease-in-out bg-white dark:bg-dark-1 hover:bg-gray-200 dark:hover:bg-dark-2 rounded-md">Un año</a> 
                    
                        
                    </div>
                </div>
                
                
            </div>
        </div>
        <div class="report-chart"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
            <canvas id="report-line-chart" height="263" class="mt-6 chartjs-render-monitor" style="display: block; width: 494px; height: 263px;" width="494"></canvas>
        </div>
    </div>
</div>